#!moo verb raise wave --on $sceptre --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: SCEPTRE-FUNCTION

if player_verb in ["wave", "raise"]:
    if context.player.location == _.get_property("aragain_falls") or context.player.location == _.get_property(
        "end_of_rainbow"
    ):
        if not _.zil_sdk.zstate_get("RAINBOW-FLAG"):
            _.zil_sdk.set_flag(_.get_property("pot_of_gold"), "invisible", False)
            print(
                "Suddenly, the rainbow appears to become solid and, I venture,\nwalkable (I think the giveaway was the stairs and bannister)."
            )
            if context.player.location == _.get_property("end_of_rainbow") and _.get_property(
                "pot_of_gold"
            ).location == _.get_property("end_of_rainbow"):
                print("A shimmering pot of gold appears at the end of the rainbow.")
            return _.zil_sdk.zstate_set("RAINBOW-FLAG", True)
        else:
            # ZIL: <ROB ...>
            _.zork_thing.invoke_verb("rob", _.get_property("on_rainbow"), _.get_property("wall"))
            print("The rainbow seems to have become somewhat run-of-the-mill.")
            _.zil_sdk.zstate_set("RAINBOW-FLAG", None)
            return True
    elif context.player.location == _.get_property("on_rainbow"):
        _.zil_sdk.zstate_set("RAINBOW-FLAG", None)
        return _.zil_sdk.jigs_up(
            "The structural integrity of the rainbow is severely compromised,\nleaving you hanging in midair, supported only by water vapor. Bye."
        )
    else:
        return print("A dazzling display of color briefly emanates from the sceptre.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
