#!moo verb chalice_fcn --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: CHALICE-FCN

parser = context.parser

if verb_name in ["open", "close", "shut", "look-inside"]:
    print("You can't do that.")
    return
elif verb_name in ["examine", "x", "describe", "what"]:
    print("It looks pretty much like a " + parser.get_dobj().desc() + ".")
    return
return passthrough()
