#!moo verb look-under --on "trap door" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: TRAP-DOOR-FCN (look-under branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.here() == lookup("living_room"):
    if this.flag("open"):
        print("You see a rickety staircase descending into darkness.")
        return
    else:
        print("It's closed.")
        return
return passthrough()
