# Generated by extras/zil_import
import pytest
from moo.sdk import lookup


@pytest.mark.django_db(transaction=True, reset_sequences=True)
@pytest.mark.parametrize("t_init", ["zork1"], indirect=True)
@pytest.mark.parametrize(
    "routine_name",
    [
        "MAIN-LOOP",
        "MAIN-LOOP-1",
        "QUEUE",
        "INT",
        "CLOCKER",
        "PARSER",
        "STUFF",
        "INBUF-STUFF",
        "INBUF-ADD",
        "WT?",
        "CLAUSE",
        "NUMBER?",
        "ORPHAN-MERGE",
        "ACLAUSE-WIN",
        "NCLAUSE-WIN",
        "WORD-PRINT",
        "UNKNOWN-WORD",
        "CANT-USE",
        "SYNTAX-CHECK",
        "CANT-ORPHAN",
    ],
)
def test_translated_verb_loaded(t_init, routine_name):
    """Each translated ACTION routine should be loadable (no syntax errors)."""
    zork_room = lookup("Zork Room")
    assert zork_room is not None
    # Verb files are loaded by bootstrap.load_verbs — if they loaded, no SyntaxError.
    # Full dispatch testing requires individual test cases per verb.
