#!moo verb get insert pick place put take --on "quantity of water" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: WATER-F
# aux: AV, W, PI?

player = context.player
parser = context.parser
global_water = lookup("global_water")
river = lookup("river")
av = 0
w = 0
pi_p = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if parser.get_dobj() == global_water or parser.get_dobj() == this:
    w = parser.get_dobj()
    pi_p = None
else:
    w = parser.get_iobj() if parser.has_iobj() else None
    if w:
        pi_p = True
if w == global_water:
    w = this
    if the_player_verb in ["take", "get", "pick", "put", "place", "insert"]:
        return _.remove(w)
if pi_p:
    # SETG of parser-state slot is a no-op in DjangoMOO
    pass
else:
    # SETG of parser-state slot is a no-op in DjangoMOO
    pass
av = player.location
if not av.flag("vehicle"):
    av = None
if pi_p:
    if the_player_verb in ["put", "place", "insert"] and river.global_in(player.here()):
        _.perform(player.zstate_get("V?PUT"), parser.get_dobj(), river)
    else:
        print("Nice try.")
    return True
return passthrough()
