#!moo verb through board --on "quantity of water" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: WATER-F (through/board branch)

player = context.player
av = 0
w = 0
pi_p = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print(_.pick(player.zstate_get("SWIMYUKS")))
return True
