#!moo verb pre-board --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: PRE-BOARD
# aux: AV

av = None

av = context.player.location
if _.zork_thing.invoke_verb("null-f"):
    return True
elif _.zil_sdk.flag(context.parser.get_dobj(), "vehicle"):
    if not context.parser.get_dobj().location == context.player.location:
        print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " must be on the ground to be boarded.")
    elif _.zil_sdk.flag(av, "vehicle"):
        print("You are already in the " + _.zil_sdk.desc(av) + "!")
    else:
        return False
elif context.parser.get_dobj() in (_.get_property("water"), _.get_property("global_water")):
    _.zil_sdk.perform(_.zil_sdk.zstate_get("V?SWIM"), context.parser.get_dobj(), None)
    return True
else:
    print("You have a theory on how to board a " + _.zil_sdk.desc(context.parser.get_dobj()) + ", perhaps?")
# ZIL: <RFATAL ...>
return 2
