#!moo verb pre-take --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: PRE-TAKE

if context.parser.get_dobj().location == context.player:
    if _.zil_sdk.flag(context.parser.get_dobj(), "wearbit"):
        return print("You are already wearing it.")
    else:
        return print("You already have that!")
elif _.zil_sdk.flag(context.parser.get_dobj().location, "contbit") and not _.zil_sdk.flag(
    context.parser.get_dobj().location, "open"
):
    print("You can't reach something that's inside a closed container.")
    return True
elif context.parser.get_iobj():
    if context.parser.get_iobj() == _.get_property("ground"):
        _.zil_sdk.zstate_set("PRSI", None)
        return False
    if _.zil_sdk.zstate_get("ZORK-NUMBER") == 2:
        if context.parser.get_dobj() == _.zil_sdk.zstate_get("DOOR-KEEPER"):
            _.zil_sdk.zstate_set("PRSI", None)
            return False
    else:
        # ZIL: <NULL-F ...>
        return _.zork_thing.invoke_verb("null-f")
    if not context.parser.get_iobj() == context.parser.get_dobj().location:
        return print(
            "The "
            + _.zil_sdk.desc(context.parser.get_dobj())
            + " isn't in the "
            + _.zil_sdk.desc(context.parser.get_iobj())
            + "."
        )
    else:
        _.zil_sdk.zstate_set("PRSI", None)
        return False
elif context.parser.get_dobj() == context.player.location:
    return print("You're inside of it!")
