#!moo verb pre-put --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: PRE-PUT

if _.zork_thing.invoke_verb("null-f"):
    return False
else:
    # ZIL: <PRE-GIVE ...>
    return _.zork_thing.invoke_verb("pre-give")
