#!moo verb pre-drop --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: PRE-DROP

if context.parser.get_dobj() == context.player.location:
    _.zil_sdk.perform(_.zil_sdk.zstate_get("V?DISEMBARK"), context.parser.get_dobj(), None)
    return True
