#!moo verb break crack describe destroy examine get give hear hello hi listen move mung pick smash take throw toss what x --on "troll" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

import random
from moo.sdk import context, lookup
# ZIL routine: TROLL-FCN
# params: MODE

player = context.player
parser = context.parser
axe = lookup("axe")
knife = lookup("knife")
sword = lookup("sword")
mode = args[0] if len(args) > 0 else None
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if mode == player.zstate_get("F-BUSY?"):
    if axe.location == this:
        pass
    elif axe.location == player.here() and random.randint(1, 100) <= 75:
        axe.set_flag("obvious", True)
        axe.set_flag("weapon", False)
        axe.moveto(this)
        this.set_property(
            "description", "A nasty-looking troll, brandishing a bloody axe, blocks all passages out\nof the room."
        )
        if this.location == player.here():
            print(
                "The troll, angered and humiliated, recovers his weapon. He appears to have\nan axe to grind with you."
            )
        return True
    elif this.location == player.here():
        this.set_property("description", "A pathetically babbling troll is here.")
        print("The troll, disarmed, cowers in terror, pleading for his life in\nthe guttural tongue of the trolls.")
        return True
elif mode == player.zstate_get("F-DEAD"):
    if axe.location == this:
        axe.moveto(player.here())
        axe.set_flag("obvious", False)
        axe.set_flag("weapon", True)
    return player.zstate_set("TROLL-FLAG", True)
elif mode == player.zstate_get("F-UNCONSCIOUS"):
    this.set_flag("hostile", False)
    if axe.location == this:
        axe.moveto(player.here())
        axe.set_flag("obvious", False)
        axe.set_flag("weapon", True)
    this.set_property(
        "description", "An unconscious troll is sprawled on the floor. All passages\nout of the room are open."
    )
    return player.zstate_set("TROLL-FLAG", True)
elif mode == player.zstate_get("F-CONSCIOUS"):
    if this.location == player.here():
        this.set_flag("hostile", True)
        print("The troll stirs, quickly resuming a fighting stance.")
    if axe.location == this:
        this.set_property(
            "description", "A nasty-looking troll, brandishing a bloody axe, blocks\nall passages out of the room."
        )
    elif axe.location == lookup("troll_room"):
        axe.set_flag("obvious", True)
        axe.set_flag("weapon", False)
        axe.moveto(this)
        this.set_property(
            "description", "A nasty-looking troll, brandishing a bloody axe, blocks\nall passages out of the room."
        )
    else:
        this.set_property("description", "A troll is here.")
    return player.zstate_set("TROLL-FLAG", None)
elif mode == player.zstate_get("F-FIRST?"):
    if random.randint(1, 100) <= 33:
        this.set_flag("hostile", True)
        player.zstate_set("P-CONT", None)
        return True
elif not mode:
    if the_player_verb in ["examine", "x", "describe", "what"]:
        print(this.getp("description"))
        return
    elif (
        the_player_verb in ["throw", "toss", "give"]
        and parser.get_dobj()
        and (parser.get_iobj() if parser.has_iobj() else None) == this
        or the_player_verb in ["take", "get", "pick", "move", "mung", "destroy", "break", "smash", "crack"]
    ):
        # ZIL: <AWAKEN ...>
        _.zork_thing.awaken(this)
        if the_player_verb in ["throw", "toss", "give"]:
            if parser.get_dobj() == axe and axe.location == player:
                print("The troll scratches his head in confusion, then takes the axe.")
                this.set_flag("hostile", True)
                axe.moveto(this)
                return True
            elif parser.get_dobj() in (this, axe):
                print("You would have to get the " + parser.get_dobj().desc() + " first, and that seems unlikely.")
                return True
            if the_player_verb in ["throw", "toss"]:
                print("The troll, who is remarkably coordinated, catches the " + parser.get_dobj().desc(), end="")
                return
            else:
                print("The troll, who is not overly proud, graciously accepts the gift", end="")
                return
            if random.randint(1, 100) <= 20 and parser.get_dobj() in (knife, sword, axe):
                _.remove(parser.get_dobj())
                print(
                    " and eats it hungrily. Poor troll, he dies from an internal hemorrhage\nand his carcass disappears in a sinister black fog."
                )
                _.remove(this)
                # ZIL: <APPLY ...>
                apply(this.getp("action"), player.zstate_get("F-DEAD"))
                return player.zstate_set("TROLL-FLAG", True)
            elif parser.get_dobj() in (knife, sword, axe):
                parser.get_dobj().moveto(player.here())
                print(
                    " and, being for the moment sated, throws it back. Fortunately, the\ntroll has poor control, and the "
                    + parser.get_dobj().desc()
                    + " falls to the floor. He does\nnot look pleased."
                )
                return this.set_flag("hostile", True)
            else:
                print(" and not having the most discriminating tastes, gleefully eats it.")
                return _.remove(parser.get_dobj())
        elif the_player_verb in ["take", "get", "pick", "move"]:
            print('The troll spits in your face, grunting "Better luck next time" in a\nrather barbarous accent.')
            return
        elif the_player_verb in ["mung", "destroy", "break", "smash", "crack"]:
            print("The troll laughs at your puny gesture.")
            return
    elif the_player_verb in ["listen", "hear"]:
        print("Every so often the troll says something, probably uncomplimentary, in\nhis guttural tongue.")
        return
    elif player.zstate_get("TROLL-FLAG") and the_player_verb in ["hello", "hi"]:
        print("Unfortunately, the troll can't hear you.")
        return
return passthrough()
