#!moo verb insert oil place put --on $putty --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: PUTTY-FCN

if (
    player_verb in ["oil"]
    and context.parser.get_iobj() == _.get_property("putty")
    or player_verb in ["put", "place", "insert"]
    and context.parser.get_dobj() == _.get_property("putty")
):
    return print("The all-purpose gunk isn't a lubricant.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
