#!moo verb describe examine get insert open pick place put take what x --on $tool_chest --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: TOOL-CHEST-FCN

if player_verb in ["examine", "x", "describe", "what"]:
    return print("The chests are all empty.")
elif player_verb in ["take", "get", "pick", "open", "put", "place", "insert"]:
    _.zil_sdk.remove(_.get_property("tool_chest"))
    return print("The chests are so rusty and corroded that they crumble when you\ntouch them.")
elif player_verb in ["open"]:
    return print("The chests are already open.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
