#!moo verb curses --on "Zork Actor" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-CURSES

parser = context.parser

if parser.get_dobj():
    if parser.get_dobj().flag("actorbit"):
        print("Insults of this nature won't help you.")
        return
    else:
        print("What a loony!")
        return
else:
    print("Such language in a high-class establishment like this!")
    return
