#!moo verb inventory --on "Zork Actor" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-INVENTORY

player = context.player

if player.contents.first():
    # ZIL: <PRINT-CONT ...>
    return _.zork_thing.print_cont(player)
else:
    print("You are empty-handed.")
    return
