#!moo verb pray --on "Zork Actor" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: V-PRAY

player = context.player

if player.here() == lookup("south_temple"):
    return _.goto(lookup("forest_1"))
else:
    print("If you pray enough, your prayers may be answered.")
    return
