#!moo verb quit --on "Zork Actor" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

# ZIL routine: V-QUIT
# aux: SCOR

scor = 0

# ZIL: <V-SCORE ...>
_.zork_thing.score()
print("Do you wish to leave the game? (Y is affirmative): ", end="")
if _.zork_thing.is_yes():
    print("Goodbye.")
    return
else:
    print("Ok.")
    return
