#!moo verb swim --on "Zork Actor" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-SWIM

player = context.player

if player.here() in (player.zstate_get("ON-LAKE"), player.zstate_get("IN-LAKE")):
    print("What do you think you're doing?")
    return
elif _.zork_thing.null_f():
    return False
else:
    print("Go jump in a lake!")
    return
