#!moo verb treasure --on "Zork Actor" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: V-TREASURE

player = context.player
north_temple = lookup("north_temple")
treasure_room = lookup("treasure_room")

if player.here() == north_temple:
    return _.goto(treasure_room)
elif player.here() == treasure_room:
    return _.goto(north_temple)
else:
    print("Nothing happens.")
    return
