#!moo verb unscript --on "Zork Actor" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

# ZIL routine: V-UNSCRIPT

print("Here ends a transcript of interaction with")
# ZIL: <V-VERSION ...>
_.zork_thing.version()
# ZIL: <PUT ...>
_.table_put(0, 8, (((_.table_get(0, 8)) or 0) & ((-2) or 0)))
return True
