#!moo verb version --on "Zork Actor" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-VERSION
# aux: CNT

player = context.player
cnt = 17

if player.zstate_get("ZORK-NUMBER") == 1:
    print(
        "ZORK I: The Great Underground Empire\n\nInfocom interactive fiction - a fantasy story\n\nCopyright (c) 1981, 1982, 1983, 1984, 1985, 1986",
        end="",
    )
elif player.zstate_get("ZORK-NUMBER") == 2:
    print(
        "ZORK II: The Wizard of Frobozz\n\nInfocom interactive fiction - a fantasy story\n\nCopyright (c) 1981, 1982, 1983, 1986",
        end="",
    )
elif player.zstate_get("ZORK-NUMBER") == 3:
    print(
        "ZORK III: The Dungeon Master\n\nInfocom interactive fiction - a fantasy story\n\nCopyright 1982, 1983, 1984, 1986",
        end="",
    )
print(" Infocom, Inc. All rights reserved.")
print(
    "ZORK is a registered trademark of Infocom, Inc.\n\nRelease "
    + str((((_.table_get(0, 1)) or 0) & ((player.zstate_get("*3777*")) or 0)))
    + " / Serial number ",
    end="",
)
while True:
    if (cnt := cnt + 1) > 23:
        break
    else:
        print(chr(_.table_get(0, cnt)), end="")
print()
return
