#!moo verb wish --on "Zork Actor" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-WISH

player = context.player

if player.zstate_get("ZORK-NUMBER") == 2:
    return _.perform(player.zstate_get("V?MAKE"), player.zstate_get("WISH"), None)
else:
    print("With luck, your wish will come true.")
    return
