#!moo verb bottle_function --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: BOTTLE-FUNCTION
# aux: E?

parser = context.parser
water = lookup("water")
e_p = 0

if e_p and water.location == parser.get_dobj():
    print("The water spills to the floor and evaporates.")
    _.remove(water)
    return True
elif e_p:
    return True
return passthrough()
