#!moo verb throw toss --on "glass bottle" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: BOTTLE-FUNCTION (throw branch)

parser = context.parser
e_p = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if parser.get_dobj() == this:
    _.remove(parser.get_dobj())
    e_p = True
    print("The bottle hits the far wall and shatters.")
    return
return passthrough()
