#!moo verb axe_f --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: AXE-F

player = context.player

if player.zstate_get("TROLL-FLAG"):
    pass
else:
    # ZIL: <WEAPON-FUNCTION ...>
    return _.zork_thing.weapon_function(this, lookup("troll"))
