#!moo verb look --on $reservoir_south
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL: RESERVOIR-SOUTH-FCN / M-LOOK

if _.zil_sdk.zstate_get("LOW-TIDE") and _.zil_sdk.zstate_get("GATES-OPEN"):
    print(
        "You are in a long room, to the north of which was formerly a lake.\nHowever, with the water level lowered, there is merely a wide stream\nrunning through the center of the room.",
        end="",
    )
elif _.zil_sdk.zstate_get("GATES-OPEN"):
    print(
        "You are in a long room. To the north is a large lake, too deep\nto cross. You notice, however, that the water level appears to be\ndropping at a rapid rate. Before long, it might be possible to cross\nto the other side from here.",
        end="",
    )
elif _.zil_sdk.zstate_get("LOW-TIDE"):
    print(
        "You are in a long room, to the north of which is a wide area which\nwas formerly a reservoir, but now is merely a stream. You notice,\nhowever, that the level of the stream is rising quickly and that\nbefore long it will be impossible to cross here.",
        end="",
    )
else:
    print("You are in a long room on the south shore of a large lake, far\ntoo deep and wide for crossing.", end="")
print()
print(
    "There is a path along the stream to the east or west, a steep pathway\nclimbing southwest along the edge of a chasm, and a path leading into a\ncanyon to the southeast."
)
