#!moo verb rivr4-room --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: RIVR4-ROOM
# params: RARG

rarg = args[0] if len(args) > 0 else None

if rarg == "M-END":
    if _.get_property("buoy").location == context.player and _.zil_sdk.zstate_get("BUOY-FLAG"):
        print("You notice something funny about the feel of the buoy.")
        return _.zil_sdk.zstate_set("BUOY-FLAG", None)
