#!moo verb turnfunc --on $river_4
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL: RIVR4-ROOM / M-END

if _.get_property("buoy").location == context.player and _.zil_sdk.zstate_get("BUOY-FLAG"):
    print("You notice something funny about the feel of the buoy.")
    _.zil_sdk.zstate_set("BUOY-FLAG", None)
