#!moo verb buffer-print --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: BUFFER-PRINT
# params: BEG, END, CP
# aux: NOSP, WRD, FIRST??, PN, Q?

beg = args[0] if len(args) > 0 else None
end = args[1] if len(args) > 1 else None
cp = args[2] if len(args) > 2 else None
nosp = True
wrd = None
first_p_p = True
pn = None
q_p = None

while True:
    if beg == end:
        break
    else:
        wrd = _.zil_sdk.table_get(beg, 0)
        if wrd == _.zil_sdk.zstate_get("W?COMMA"):
            print(", ", end="")
        elif nosp:
            nosp = None
        else:
            print(" ", end="")
        if wrd in (_.zil_sdk.zstate_get("W?PERIOD"), _.zil_sdk.zstate_get("W?COMMA")):
            nosp = True
        elif wrd == _.zil_sdk.zstate_get("W?ME"):
            # ZIL: <PRINTD ...>
            printd(_.get_property("me"))
            pn = True
        elif wrd == _.zil_sdk.zstate_get("W?INTNUM"):
            print(str(_.zil_sdk.zstate_get("P-NUMBER")), end="")
            pn = True
        else:
            if first_p_p and not pn and cp:
                print("the ", end="")
            if _.zil_sdk.zstate_get("P-OFLAG") or _.zil_sdk.zstate_get("P-MERGED"):
                print(str(wrd), end="")
            elif wrd == _.zil_sdk.zstate_get("W?IT") and _.zork_thing.invoke_verb(
                "accessible?", _.zil_sdk.zstate_get("P-IT-OBJECT")
            ):
                # ZIL: <PRINTD ...>
                printd(_.zil_sdk.zstate_get("P-IT-OBJECT"))
            else:
                # ZIL: <WORD-PRINT ...>
                _.zork_thing.invoke_verb("word-print", _.zil_sdk.table_get(beg, 2), _.zil_sdk.table_get(beg, 3))
            first_p_p = None
    beg = rest(beg, _.zil_sdk.zstate_get("P-WORDLEN"))
