#!moo verb describe-object --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: DESCRIBE-OBJECT
# params: OBJ, V?, LEVEL
# aux: STR, AV

obj = args[0] if len(args) > 0 else None
v_p = args[1] if len(args) > 1 else None
level = args[2] if len(args) > 2 else None
str_v = None
av = None

_.zil_sdk.zstate_set("DESC-OBJECT", obj)
if level == 0 and apply(_.zil_sdk.getp(obj, "descfcn"), "M-OBJDESC"):
    return True
elif (
    level == 0
    and not _.zil_sdk.flag(obj, "touchbit")
    and (str_v := _.zil_sdk.getp(obj, "first_description"))
    or (str_v := _.zil_sdk.getp(obj, "description"))
):
    return print(str_v, end="")
elif level == 0:
    print("There is a " + _.zil_sdk.desc(obj) + " here", end="")
    if _.zil_sdk.flag(obj, "onbit"):
        print(" (providing light)", end="")
    return print(".", end="")
else:
    print(_.zil_sdk.table_get(_.zil_sdk.zstate_get("INDENTS"), level), end="")
    print("A " + _.zil_sdk.desc(obj), end="")
    if _.zil_sdk.flag(obj, "onbit"):
        return print(" (providing light)", end="")
    elif _.zil_sdk.flag(obj, "wearbit") and obj.location == context.player:
        return print(" (being worn)", end="")
if _.zil_sdk.zstate_get("ZORK-NUMBER") == 2:
    if obj == _.zil_sdk.zstate_get("SPELL-VICTIM") and _.zil_sdk.zstate_get("SPELL-USED") == _.zil_sdk.zstate_get(
        "W?FLOAT"
    ):
        return print(" (floating in midair)", end="")
else:
    # ZIL: <NULL-F ...>
    return _.zork_thing.invoke_verb("null-f")
if level == 0 and (av := context.player.location) and _.zil_sdk.flag(av, "vehicle"):
    return print(" (outside the " + _.zil_sdk.desc(av) + ")", end="")
print()
if _.zork_thing.invoke_verb("see-inside?", obj) and obj.contents.first():
    # ZIL: <PRINT-CONT ...>
    return _.zork_thing.invoke_verb("print-cont", obj, v_p, level)
