#!moo verb describe-room --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: DESCRIBE-ROOM
# params: LOOK?
# aux: V?, STR, AV

look_p = args[0] if len(args) > 0 else None
v_p = None
str_v = None
av = None

v_p = look_p or _.zil_sdk.zstate_get("VERBOSE")
if not _.zil_sdk.zstate_get("LIT"):
    print("It is pitch black.", end="")
    if not _.zil_sdk.zstate_get("SPRAYED?"):
        print(" You are likely to be eaten by a grue.", end="")
    print()
    if _.zil_sdk.zstate_get("ZORK-NUMBER") == 3:
        if context.player.location == _.zil_sdk.zstate_get("DARK-2"):
            print(
                "The ground continues to slope upwards away from the lake. You can barely\ndetect a dim light from the east."
            )
    else:
        # ZIL: <NULL-F ...>
        _.zork_thing.invoke_verb("null-f")
    return False
if not _.zil_sdk.flag(context.player.location, "touchbit"):
    _.zil_sdk.set_flag(context.player.location, "touchbit", True)
    v_p = True
if _.zil_sdk.zstate_get("ZORK-NUMBER") == 1:
    if _.zil_sdk.flag(context.player.location, "maze"):
        _.zil_sdk.set_flag(context.player.location, "touchbit", False)
else:
    # ZIL: <NULL-F ...>
    _.zork_thing.invoke_verb("null-f")
if context.player.location.location == _.zil_sdk.zstate_get("ROOMS"):
    print(_.zil_sdk.desc(context.player.location), end="")
    if _.zil_sdk.flag((av := context.player.location), "vehicle"):
        print(", in the " + _.zil_sdk.desc(av), end="")
    print()
if cond(
    [["==?", "ZORK-NUMBER", 2], ["OR", ".LOOK?", ["NOT", "SUPER-BRIEF"], ["EQUAL?", "HERE", "ZORK3"]]],
    ["ELSE", ["OR", ".LOOK?", ["NOT", "SUPER-BRIEF"]]],
):
    av = context.player.location
    if v_p and apply(context.player.location.get_property("action"), "M-LOOK"):
        return True
    elif v_p and (str_v := context.player.location.get_property("description")):
        print(str_v)
    else:
        # ZIL: <APPLY ...>
        apply(context.player.location.get_property("action"), "M-FLASH")
    if not context.player.location == av and _.zil_sdk.flag(av, "vehicle"):
        # ZIL: <APPLY ...>
        apply(av.get_property("action"), "M-LOOK")
return True
