#!moo verb print-contents --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: PRINT-CONTENTS
# params: OBJ
# aux: F, N, 1ST?, IT?, TWO?

obj = args[0] if len(args) > 0 else None
f = None
n = None
v_1st_p = True
it_p = None
two_p = None

if f := obj.contents.first():
    while True:
        n = _.zil_sdk.next_sibling(f)
        if v_1st_p:
            v_1st_p = None
        else:
            print(", ", end="")
            if not n:
                return print("and ", end="")
        print("a " + _.zil_sdk.desc(f), end="")
        if not it_p and not two_p:
            it_p = f
        else:
            two_p = True
            it_p = None
        f = n
        if not f:
            if it_p and not two_p:
                # ZIL: <THIS-IS-IT ...>
                _.zork_thing.invoke_verb("this-is-it", it_p)
            return True
