#!moo verb thing-print --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: THING-PRINT
# params: PRSO?, THE?
# aux: BEG, END

prso_p = args[0] if len(args) > 0 else None
the_p = args[1] if len(args) > 1 else None
beg = None
end = None

if prso_p:
    beg = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1"))
    end = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1L"))
else:
    beg = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC2"))
    end = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC2L"))
# ZIL: <BUFFER-PRINT ...>
return _.zork_thing.invoke_verb("buffer-print", beg, end, the_p)
