#!moo verb word-print --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: WORD-PRINT
# params: CNT, BUF

cnt = args[0] if len(args) > 0 else None
buf = args[1] if len(args) > 1 else None

while True:
    if dless_p(cnt, 0):
        break
    else:
        print(chr(_.zil_sdk.table_get(_.zil_sdk.zstate_get("P-INBUF"), buf)), end="")
        buf = buf + 1
