---
stages:
  - release

release:
  stage: release
  tags:
    - shacklyn
  image: registry.gitlab.com/bubblehouse/runner-base:1.1.0
  variables:
    GIT_COMMITTER_EMAIL: phil@bubblehouse.org
    GIT_COMMITTER_NAME: Phil Christensen
    GIT_AUTHOR_EMAIL: phil@bubblehouse.org
    GIT_AUTHOR_NAME: Phil Christensen
    GIT_CREDENTIALS: philchristensen:${GITLAB_TOKEN}
    DOCKER_REGISTRY_USER: philchristensen
    DOCKER_REGISTRY_PASSWORD: ${GITLAB_TOKEN}
    DOCKER_BUILDKIT: 1
  script:
    - npm install
    - docker buildx install
    - docker buildx create --bootstrap --use --name=$CI_PROJECT_NAME --driver=kubernetes '--driver-opt="nodeselector=kubernetes.io/arch=amd64"'
    - docker buildx create --bootstrap --append --name=$CI_PROJECT_NAME --driver=kubernetes '--driver-opt="nodeselector=kubernetes.io/arch=arm64","tolerations=key=kubernetes.io/arch,value=arm64,operator=Equal,effect=NoSchedule"'
    - npx semantic-release
  only:
    - main
  cache:
    paths:
      - .venv
      - .cache/pip
      - node_modules/
