version: '3.7'
services:
  nginx:
    build:
      context: extras/nginx
      dockerfile: Dockerfile
    image: nginx:1.23.2-snakeoil
    volumes:
      - ./extras/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
     - "443:443"
    links:
     - webapp
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: philchristensen/termiverse:latest
    ports:
     - "8443:8443"
    links:
     - postgres
     - redis
    environment:
      DJANGO_SETTINGS_MODULE: termiverse.settings.docker
  postgres:
    image: postgres
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: termiverse
      POSTGRES_USER: termiverse
      POSTGRES_DB: termiverse
  redis:
    image: redis
    ports:
     - "6379:6379"
