---
services:
  nginx:
    build:
      context: extras/nginx
      dockerfile: Dockerfile
    image: nginx:1.27.3-snakeoil
    volumes:
      - ./extras/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 443:443
    links:
      - webapp
  webssh:
    build:
      context: .
      dockerfile: Dockerfile
    image: philchristensen/moo:latest
    command: [webssh]
    ports:
      - 8422:8422
    links:
      - shell
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: philchristensen/moo:latest
    ports:
      - 8443:8443
    links:
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: moo.settings.local
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: philchristensen/moo:latest
    command: [celery]
    links:
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: moo.settings.local
  shell:
    build:
      context: .
      dockerfile: Dockerfile
    image: philchristensen/moo:latest
    command: [manage.py, moo_shell]
    ports:
      - 8022:8022
    links:
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: moo.settings.local
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: moo
      POSTGRES_USER: moo
      POSTGRES_DB: moo
  redis:
    image: redis
    ports:
      - 6379:6379
