FROM python:3.11.12-slim-bookworm AS builder
LABEL Maintainer="Phil Christensen <phil@bubblehouse.org>"
LABEL Name="django-moo"
LABEL Version="0.94.8"

# Install builder dependencies
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
       apt-transport-https curl unzip gnupg2 gcc g++ libc-dev libssl-dev libpq-dev \
       python3-pip ca-certificates cmake make \
    && rm -rf /var/lib/apt/lists/*

# Build liboqs shared library for post-quantum SSH key exchange
ARG LIBOQS_VERSION=0.12.0
RUN curl -L "https://github.com/open-quantum-safe/liboqs/archive/refs/tags/${LIBOQS_VERSION}.tar.gz" \
      | tar -xz \
    && cmake -S liboqs-${LIBOQS_VERSION} -B liboqs-build \
         -DOQS_BUILD_ONLY_LIB=ON \
         -DBUILD_SHARED_LIBS=ON \
         -DCMAKE_BUILD_TYPE=Release \
         -DCMAKE_INSTALL_PREFIX=/usr/local \
    && cmake --build liboqs-build \
    && cmake --install liboqs-build \
    && rm -rf liboqs-${LIBOQS_VERSION} liboqs-build

# Install uv, the build tool.
ARG TARGETARCH
RUN case "${TARGETARCH}" in \
      amd64) UV_ARCH="x86_64" ;; \
      arm64) UV_ARCH="aarch64" ;; \
      *) echo "Unsupported architecture: ${TARGETARCH}" && exit 1 ;; \
    esac \
    && curl -L "https://github.com/astral-sh/uv/releases/download/0.10.4/uv-${UV_ARCH}-unknown-linux-gnu.tar.gz" -o uv.tar.gz \
    && tar -xzf uv.tar.gz \
    && mv "uv-${UV_ARCH}-unknown-linux-gnu/uv" /usr/local/bin/uv \
    && chmod 0755 /usr/local/bin/uv \
    && rm -rf uv.tar.gz

ENV UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    UV_PYTHON_DOWNLOADS=never \
    UV_PYTHON=/usr/local/bin/python3.11 \
    UV_PROJECT_ENVIRONMENT=/usr/app

RUN --mount=type=cache,target=/root/.cache \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync \
        --frozen \
        --no-install-project \
        --no-binary-package uwsgi

COPY . /usr/app/src
WORKDIR /usr/app/src
RUN --mount=type=cache,target=/root/.cache \
    uv sync \
        --frozen \
        --no-editable \
        --no-binary-package uwsgi

RUN export SITE_PACKAGES=`../bin/python -c 'import sys; print(sys.path[-1])'` \
    && cp /usr/app/src/extras/webssh/index.html $SITE_PACKAGES/webssh/templates/index.html.tmpl

FROM python:3.11.12-slim-bookworm

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
       git ssl-cert ssh net-tools gettext-base \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#TODO: This line should be generated by the entrypoint script, which would let it use env vars like WEBSSH_HOSTNAME (which should be renamed to SHELL_HOSTNAME)
RUN echo "[shell]:8022 $(cat /etc/ssh/ssh_host_ecdsa_key.pub | cut -d ' ' -f 1,2)" >> /etc/ssh/pregenerated_known_hosts
RUN echo "[django-moo-django-moo-chart-shell]:8022 $(cat /etc/ssh/ssh_host_ecdsa_key.pub | cut -d ' ' -f 1,2)" >> /etc/ssh/pregenerated_known_hosts

# Setup directories and permissions
RUN chgrp www-data /etc/ssl/private/ \
    && chmod g+rx /etc/ssl/private/ \
    && chgrp www-data /etc/ssl/private/ssl-cert-snakeoil.key \
    && chmod g+r /etc/ssl/private/ssl-cert-snakeoil.key \
    && mkdir -p /usr/app \
    && chown www-data:www-data /usr/app \
    && mkdir -p /usr/app/src \
    && chgrp www-data /usr/app/src \
    && mkdir -p /usr/app/static \
    && chgrp www-data /usr/app/static/ \
    && chmod ug+rwx /usr/app/static/ \
    && chgrp www-data /etc/ssh/ssh_host_ecdsa_key \
    && chmod ug+rw /etc/ssh/ssh_host_ecdsa_key \
    && chgrp www-data /etc/ssh/ssh_host_ecdsa_key.pub \
    && chmod ug+rw /etc/ssh/ssh_host_ecdsa_key.pub

WORKDIR /usr/app
RUN usermod -d /usr/app www-data

ADD extras/entrypoint.sh /entrypoint.sh
ADD extras/uwsgi/uwsgi.ini /etc/uwsgi.ini
ADD extras/healthchecks/*ness.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/*ness.sh

COPY --from=builder /usr/local/lib/liboqs.so* /usr/local/lib/
RUN ldconfig

COPY --from=builder /usr/app /usr/app

RUN chown -R www-data /usr/app/lib/python3.11/site-packages/webssh/templates/

ENV PATH="/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/app/bin"

# Custom entrypoint for improved ad-hoc command support
ENTRYPOINT ["/entrypoint.sh"]
# See <https://hynek.me/articles/docker-signals/>.
STOPSIGNAL SIGINT
