#!moo verb burn count describe examine insert lamp-off lamp-on light place put what x --on $candles --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: CANDLES-FCN

if not _.zil_sdk.flag(_.get_property("candles"), "touchbit"):
    return _.zil_sdk.queue("i-candles", 0)
if _.get_property("candles") == context.parser.get_iobj():
    return False
else:
    if player_verb in ["lamp-on", "burn", "light"]:
        if _.zil_sdk.flag(_.get_property("candles"), "rmungbit"):
            return print("Alas, there's not much left of the candles. Certainly not enough to\nburn.")
        elif not context.parser.get_iobj():
            if _.zil_sdk.flag(_.get_property("match"), "flamebit"):
                print("(with the match)")
                _.zil_sdk.perform(_.zil_sdk.zstate_get("V?LAMP-ON"), _.get_property("candles"), _.get_property("match"))
                return True
            else:
                print("You should say what to light them with.")
                # ZIL: <RFATAL ...>
                return 2
        elif context.parser.get_iobj() == _.get_property("match") and _.zil_sdk.flag(_.get_property("match"), "onbit"):
            print("The candles are ", end="")
            if _.zil_sdk.flag(_.get_property("candles"), "onbit"):
                return print("already lit.")
            else:
                _.zil_sdk.set_flag(_.get_property("candles"), "onbit", True)
                print("lit.")
                return _.zil_sdk.queue("i-candles", 0)
        elif context.parser.get_iobj() == _.get_property("torch"):
            if _.zil_sdk.flag(_.get_property("candles"), "onbit"):
                return print("You realize, just in time, that the candles are already lighted.")
            else:
                print("The heat from the torch is so intense that the candles are vaporized.")
                return _.zil_sdk.remove(_.get_property("candles"))
        else:
            return print("You have to light them with something that's burning, you know.")
    elif player_verb in ["count"]:
        return print("Let's see, how many objects in a pair? Don't tell me, I'll get it.")
    elif player_verb in ["lamp-off"]:
        _.zil_sdk.cancel("i-candles")
        if _.zil_sdk.flag(_.get_property("candles"), "onbit"):
            print("The flame is extinguished.", end="")
            _.zil_sdk.set_flag(_.get_property("candles"), "onbit", False)
            _.zil_sdk.set_flag(_.get_property("candles"), "touchbit", True)
            _.zil_sdk.zstate_set("LIT", _.zork_thing.invoke_verb("lit?", context.player.location))
            if not _.zil_sdk.zstate_get("LIT"):
                print(" It's really dark in here....", end="")
            print()
            return True
        else:
            return print("The candles are not lighted.")
    elif player_verb in ["put", "place", "insert"] and _.zil_sdk.flag(context.parser.get_iobj(), "flammable"):
        return print("That wouldn't be smart.")
    elif player_verb in ["examine", "x", "describe", "what"]:
        print("The candles are ", end="")
        if _.zil_sdk.flag(_.get_property("candles"), "onbit"):
            print("burning.", end="")
        else:
            print("out.", end="")
        return print()
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
