#!moo verb confunc --on $south_temple
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL: SOUTH-TEMPLE-FCN / M-BEG

_.zil_sdk.zstate_set("COFFIN-CURE", not _.get_property("coffin").location == context.player)
return False
