#!moo verb insert leap place put through --on $river --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: RIVER-FUNCTION

if player_verb in ["put", "place", "insert"]:
    if context.parser.get_iobj() == _.get_property("river"):
        if context.parser.get_dobj() == _.get_property("me"):
            return _.zil_sdk.jigs_up("You splash around for a while, fighting the current, then you drown.")
        elif context.parser.get_dobj() == _.get_property("inflated_boat"):
            return print("You should get in the boat then launch it.")
        elif _.zil_sdk.flag(context.parser.get_dobj(), "flammable"):
            _.zil_sdk.remove(context.parser.get_dobj())
            return print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " floats for a moment, then sinks.")
        else:
            _.zil_sdk.remove(context.parser.get_dobj())
            return print(
                "The " + _.zil_sdk.desc(context.parser.get_dobj()) + " splashes into the water and is gone forever."
            )
elif player_verb in ["leap", "through"]:
    return print(
        "A look before leaping reveals that the river is wide and dangerous,\nwith swift currents and large, half-hidden rocks. You decide to forgo your\nswim."
    )
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
