#!moo verb look --on $entrance_to_hades
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL: LLD-ROOM / M-LOOK

print(
    "You are outside a large gateway, on which is inscribed\n\n\n  Abandon every hope\nall ye who enter here!\n\n\nThe gate is open; through it you can see a desolation, with a pile of\nmangled bodies in one corner. Thousands of voices, lamenting some\nhideous fate, can be heard."
)
if not _.zil_sdk.zstate_get("LLD-FLAG") and not _.zil_sdk.zstate_get("DEAD"):
    print("The way through the gate is barred by evil spirits, who jeer at your\nattempts to pass.")
