#!moo verb accessible? --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: ACCESSIBLE?
# params: OBJ
# aux: L

obj = args[0] if len(args) > 0 else None
l = obj.location

if _.zil_sdk.flag(obj, "invisible"):
    return False
elif not l:
    return False
elif l == _.get_property("global_objects"):
    return True
elif l == _.get_property("local_globals") and _.zil_sdk.global_in(obj, context.player.location):
    return True
elif not _.zork_thing.invoke_verb("meta-loc", obj) in (context.player.location, context.player.location):
    return False
elif l in (context.player, context.player.location, context.player.location):
    return True
elif _.zil_sdk.flag(l, "open") and _.zork_thing.invoke_verb("accessible?", l):
    return True
else:
    return False
