#!moo verb global-in? --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: GLOBAL-IN?
# params: OBJ1, OBJ2
# aux: TX

obj1 = args[0] if len(args) > 0 else None
obj2 = args[1] if len(args) > 1 else None
tx = None

if tx := getpt(obj2, _.zil_sdk.zstate_get("P?GLOBAL")):
    # ZIL: <ZMEMQB ...>
    return _.zork_thing.invoke_verb("zmemqb", obj1, tx, ptsize(tx) - 1)
