#!moo verb lit? --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: LIT?
# params: RM, RMBIT
# aux: OHERE, LIT

rm = args[0] if len(args) > 0 else None
rmbit = args[1] if len(args) > 1 else True
ohere = None
lit = None

if _.zil_sdk.zstate_get("ALWAYS-LIT") and context.player == context.player:
    return True
_.zil_sdk.zstate_set("P-GWIMBIT", _.zil_sdk.zstate_get("ONBIT"))
ohere = context.player.location
_.zil_sdk.zstate_set("HERE", rm)
if rmbit and _.zil_sdk.flag(rm, "onbit"):
    lit = True
else:
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-MERGE"), _.zil_sdk.zstate_get("P-MATCHLEN"), 0)
    _.zil_sdk.zstate_set("P-TABLE", _.zil_sdk.zstate_get("P-MERGE"))
    _.zil_sdk.zstate_set("P-SLOCBITS", -1)
    if ohere == rm:
        # ZIL: <DO-SL ...>
        _.zork_thing.invoke_verb("do-sl", context.player, 1, 1)
        if not context.player == context.player and context.player.location == rm:
            # ZIL: <DO-SL ...>
            _.zork_thing.invoke_verb("do-sl", context.player, 1, 1)
    # ZIL: <DO-SL ...>
    _.zork_thing.invoke_verb("do-sl", rm, 1, 1)
    if _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-TABLE"), _.zil_sdk.zstate_get("P-MATCHLEN")) > 0:
        lit = True
_.zil_sdk.zstate_set("HERE", ohere)
_.zil_sdk.zstate_set("P-GWIMBIT", 0)
return lit
