#!moo verb number? --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: NUMBER?
# params: PTR
# aux: CNT, BPTR, CHR, SUM, TIM

ptr = args[0] if len(args) > 0 else None
cnt = None
bptr = None
chr = None
sum_v = 0
tim = None

cnt = _.zil_sdk.table_get(rest(_.zil_sdk.zstate_get("P-LEXV"), ptr * 2), 2)
bptr = _.zil_sdk.table_get(rest(_.zil_sdk.zstate_get("P-LEXV"), ptr * 2), 3)
while True:
    if (cnt := cnt - 1) < 0:
        break
    else:
        chr = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-INBUF"), bptr)
        if chr == 58:
            tim = sum_v
            sum_v = 0
        elif sum_v > 10000:
            return False
        elif chr < 58 and chr > 47:
            sum_v = sum_v * 10 + chr - 48
        else:
            return False
        bptr = bptr + 1
# ZIL: <PUT ...>
_.zil_sdk.table_put(_.zil_sdk.zstate_get("P-LEXV"), ptr, _.zil_sdk.zstate_get("W?INTNUM"))
if sum_v > 1000:
    return False
elif tim:
    if tim < 8:
        tim = tim + 12
    elif tim > 23:
        return False
    sum_v = sum_v + tim * 60
_.zil_sdk.zstate_set("P-NUMBER", sum_v)
return _.zil_sdk.zstate_get("W?INTNUM")
