#!moo verb stole-light? --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: STOLE-LIGHT?
# aux: OLD-LIT

old_lit = None

old_lit = _.zil_sdk.zstate_get("LIT")
_.zil_sdk.zstate_set("LIT", _.zork_thing.invoke_verb("lit?", context.player.location))
if not _.zil_sdk.zstate_get("LIT") and old_lit:
    print("The thief seems to have left you in the dark.")
return True
