#!moo verb this-it? --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: THIS-IT?
# params: OBJ, TBL
# aux: SYNS

obj = args[0] if len(args) > 0 else None
tbl = args[1] if len(args) > 1 else None
syns = None

if _.zil_sdk.flag(obj, "invisible"):
    return False
elif _.zil_sdk.zstate_get("P-NAM") and not _.zork_thing.invoke_verb(
    "zmemq",
    _.zil_sdk.zstate_get("P-NAM"),
    (syns := getpt(obj, _.zil_sdk.zstate_get("P?SYNONYM"))),
    [["PTSIZE", ".SYNS"], 2] - 1,
):
    return False
elif (
    _.zil_sdk.zstate_get("P-ADJ")
    and not (syns := getpt(obj, _.zil_sdk.zstate_get("P?ADJECTIVE")))
    or not _.zork_thing.invoke_verb("zmemqb", _.zil_sdk.zstate_get("P-ADJ"), syns, ptsize(syns) - 1)
):
    return False
elif not _.zil_sdk.zstate_get("P-GWIMBIT") == 0 and not _.zil_sdk.flag(obj, "p_gwimbit"):
    return False
return True
