#!moo verb winning? --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
# ZIL routine: WINNING?
# params: V
# aux: VS, PS

v = args[0] if len(args) > 0 else None
vs = None
ps = None

vs = v.get_property("strength")
ps = vs - _.zork_thing.invoke_verb("fight-strength")
if ps > 3:
    return random.randint(1, 100) <= 90
elif ps > 0:
    return random.randint(1, 100) <= 75
elif ps == 0:
    return random.randint(1, 100) <= 50
elif vs > 1:
    return random.randint(1, 100) <= 25
else:
    return random.randint(1, 100) <= 10
