#!moo verb bat-d --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: BAT-D

if _.get_property("garlic").location in (context.player, context.player.location):
    return print(
        "In the corner of the room on the ceiling is a large vampire bat who\nis obviously deranged and holding his nose."
    )
else:
    return print("A large vampire bat, hanging from the ceiling, swoops down at you!")
