#!moo verb breathe --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: BREATHE

return _.zil_sdk.perform(_.zil_sdk.zstate_get("V?INFLATE"), context.parser.get_dobj(), _.get_property("lungs"))
