#!moo verb ccount --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: CCOUNT
# params: OBJ
# aux: CNT, X

obj = args[0] if len(args) > 0 else None
cnt = 0
x = None

if x := obj.contents.first():
    while True:
        if not _.zil_sdk.flag(x, "wearbit"):
            cnt = cnt + 1
        if not (x := _.zil_sdk.next_sibling(x)):
            break
return cnt
