#!moo verb clocker --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: CLOCKER
# aux: C, E, TICK, FLG

c = None
e = None
tick = None
flg = None

_.zil_sdk.zstate_get("#DECL")
if _.zil_sdk.zstate_get("CLOCK-WAIT"):
    _.zil_sdk.zstate_set("CLOCK-WAIT", None)
    return False
c = rest(_.zil_sdk.zstate_get("C-TABLE"), cond(["P-WON", "C-INTS"], ["T", "C-DEMONS"]))
e = rest(_.zil_sdk.zstate_get("C-TABLE"), _.zil_sdk.zstate_get("C-TABLELEN"))
while True:
    if c == e:
        _.zil_sdk.zstate_set("MOVES", _.zil_sdk.zstate_get("MOVES") + 1)
        return flg
    elif not _.zil_sdk.table_get(c, _.zil_sdk.zstate_get("C-ENABLED?")) == 0:
        tick = _.zil_sdk.table_get(c, _.zil_sdk.zstate_get("C-TICK"))
        if tick == 0:
            pass
        else:
            # ZIL: <PUT ...>
            _.zil_sdk.table_put(c, _.zil_sdk.zstate_get("C-TICK"), tick - 1)
            if not tick > 1 and apply(_.zil_sdk.table_get(c, _.zil_sdk.zstate_get("C-RTN"))):
                flg = True
    c = rest(c, _.zil_sdk.zstate_get("C-INTLEN"))
