#!moo verb do-sl --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: DO-SL
# params: OBJ, BIT1, BIT2
# aux: BTS

obj = args[0] if len(args) > 0 else None
bit1 = args[1] if len(args) > 1 else None
bit2 = args[2] if len(args) > 2 else None
bts = None

if btst(_.zil_sdk.zstate_get("P-SLOCBITS"), bit1 + bit2):
    # ZIL: <SEARCH-LIST ...>
    return _.zork_thing.invoke_verb(
        "search-list", obj, _.zil_sdk.zstate_get("P-TABLE"), _.zil_sdk.zstate_get("P-SRCALL")
    )
else:
    if btst(_.zil_sdk.zstate_get("P-SLOCBITS"), bit1):
        # ZIL: <SEARCH-LIST ...>
        return _.zork_thing.invoke_verb(
            "search-list", obj, _.zil_sdk.zstate_get("P-TABLE"), _.zil_sdk.zstate_get("P-SRCTOP")
        )
    elif btst(_.zil_sdk.zstate_get("P-SLOCBITS"), bit2):
        # ZIL: <SEARCH-LIST ...>
        return _.zork_thing.invoke_verb(
            "search-list", obj, _.zil_sdk.zstate_get("P-TABLE"), _.zil_sdk.zstate_get("P-SRCBOT")
        )
    else:
        return True
