#!moo verb drop-junk --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
from moo.sdk import context, lookup
# ZIL routine: DROP-JUNK
# params: RM
# aux: X, N, FLG

rm = args[0] if len(args) > 0 else None
x = None
n = None
flg = None

x = lookup("thief").contents.first()
while True:
    if not x:
        return flg
    n = _.zil_sdk.next_sibling(x)
    if x in (_.get_property("stiletto"), _.get_property("large_bag")):
        pass
    elif _.zil_sdk.getp(x, "tvalue") == 0 and random.randint(1, 100) <= 30:
        _.zil_sdk.set_flag(x, "invisible", False)
        _.zil_sdk.move(x, rm)
        if not flg and rm == context.player.location:
            print("The robber, rummaging through his bag, dropped a few items he found\nvalueless.")
            flg = True
    x = n
