#!moo verb find-in --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: FIND-IN
# params: WHERE, WHAT
# aux: W

where = args[0] if len(args) > 0 else None
what = args[1] if len(args) > 1 else None
w = None

w = where.contents.first()
if not w:
    return False
while True:
    if _.zil_sdk.flag(w, ".what") and not w == _.get_property("adventurer"):
        return w
    elif not (w := _.zil_sdk.next_sibling(w)):
        break
