#!moo verb firster --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: FIRSTER
# params: OBJ, LEVEL

obj = args[0] if len(args) > 0 else None
level = args[1] if len(args) > 1 else None

if obj == _.get_property("trophy_case"):
    return print("Your collection of treasures consists of:")
elif obj == context.player:
    return print("You are carrying:")
elif not obj.location == _.zil_sdk.zstate_get("ROOMS"):
    if level > 0:
        return print(_.zil_sdk.table_get(_.zil_sdk.zstate_get("INDENTS"), level), end="")
    if _.zil_sdk.flag(obj, "surfacebit"):
        return print("Sitting on the " + _.zil_sdk.desc(obj) + " is: ")
    elif _.zil_sdk.flag(obj, "actorbit"):
        return print("The " + _.zil_sdk.desc(obj) + " is holding: ")
    else:
        return print("The " + _.zil_sdk.desc(obj) + " contains:")
