#!moo verb fix-maint-leak --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: FIX-MAINT-LEAK

_.zil_sdk.zstate_set("WATER-LEVEL", -1)
# ZIL: <QUEUE ...>
_.zork_thing.invoke_verb("queue", _.zork_thing.invoke_verb("i-maint-room"), 0)
return print("By some miracle of Zorkian technology, you have managed to stop the\nleak in the dam.")
