#!moo verb fly-me --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: FLY-ME

# ZIL: <FWEEP ...>
_.zork_thing.invoke_verb("fweep", 4)
print("The bat grabs you by the scruff of your neck and lifts you away....")
_.zil_sdk.goto(_.zil_sdk.pick(_.zil_sdk.zstate_get("BAT-DROPS")))
if not context.player.location == _.get_property("entrance_to_hades"):
    # ZIL: <V-FIRST-LOOK ...>
    _.zork_thing.invoke_verb("v-first-look")
return True
