#!moo verb get-object --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
from moo.sdk import context, lookup
# ZIL routine: GET-OBJECT
# params: TBL, VRB
# aux: BITS, LEN, XBITS, TLEN, GCHECK, OLEN, OBJ

tbl = args[0] if len(args) > 0 else None
vrb = args[1] if len(args) > 1 else True
bits = None
len_v = None
xbits = None
tlen = None
gcheck = None
olen = 0
obj = None

xbits = _.zil_sdk.zstate_get("P-SLOCBITS")
tlen = _.zil_sdk.table_get(tbl, _.zil_sdk.zstate_get("P-MATCHLEN"))
if btst(_.zil_sdk.zstate_get("P-GETFLAGS"), _.zil_sdk.zstate_get("P-INHIBIT")):
    return True
if not _.zil_sdk.zstate_get("P-NAM") and _.zil_sdk.zstate_get("P-ADJ"):
    if _.zork_thing.invoke_verb(
        "wt?", _.zil_sdk.zstate_get("P-ADJN"), _.zil_sdk.zstate_get("PS?OBJECT"), _.zil_sdk.zstate_get("P1?OBJECT")
    ):
        _.zil_sdk.zstate_set("P-NAM", _.zil_sdk.zstate_get("P-ADJN"))
        _.zil_sdk.zstate_set("P-ADJ", None)
    elif _.zork_thing.invoke_verb("null-f"):
        True
if (
    not _.zil_sdk.zstate_get("P-NAM")
    and not _.zil_sdk.zstate_get("P-ADJ")
    and not _.zil_sdk.zstate_get("P-GETFLAGS") == _.zil_sdk.zstate_get("P-ALL")
    and _.zil_sdk.zstate_get("P-GWIMBIT") == 0
):
    if vrb:
        print("There seems to be a noun missing in that sentence!")
    return False
if not _.zil_sdk.zstate_get("P-GETFLAGS") == _.zil_sdk.zstate_get("P-ALL") or _.zil_sdk.zstate_get("P-SLOCBITS") == 0:
    _.zil_sdk.zstate_set("P-SLOCBITS", -1)
_.zil_sdk.zstate_set("P-TABLE", tbl)
if gcheck:
    # ZIL: <GLOBAL-CHECK ...>
    _.zork_thing.invoke_verb("global-check", tbl)
else:
    if _.zil_sdk.zstate_get("LIT"):
        _.zil_sdk.set_flag(context.player, "transparent", False)
        # ZIL: <DO-SL ...>
        _.zork_thing.invoke_verb(
            "do-sl", context.player.location, _.zil_sdk.zstate_get("SOG"), _.zil_sdk.zstate_get("SIR")
        )
        _.zil_sdk.set_flag(context.player, "transparent", True)
    # ZIL: <DO-SL ...>
    _.zork_thing.invoke_verb("do-sl", context.player, _.zil_sdk.zstate_get("SH"), _.zil_sdk.zstate_get("SC"))
len_v = _.zil_sdk.table_get(tbl, _.zil_sdk.zstate_get("P-MATCHLEN")) - tlen
if btst(_.zil_sdk.zstate_get("P-GETFLAGS"), _.zil_sdk.zstate_get("P-ALL")):
    pass
elif btst(_.zil_sdk.zstate_get("P-GETFLAGS"), _.zil_sdk.zstate_get("P-ONE")) and not len_v == 0:
    if not len_v == 1:
        # ZIL: <PUT ...>
        _.zil_sdk.table_put(tbl, 1, _.zil_sdk.table_get(tbl, random.randint(1, len_v)))
        print("(How about the ", end="")
        # ZIL: <PRINTD ...>
        printd(_.zil_sdk.table_get(tbl, 1))
        print("?)")
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(tbl, _.zil_sdk.zstate_get("P-MATCHLEN"), 1)
elif len_v > 1 or len_v == 0 and not _.zil_sdk.zstate_get("P-SLOCBITS") == -1:
    if _.zil_sdk.zstate_get("P-SLOCBITS") == -1:
        _.zil_sdk.zstate_set("P-SLOCBITS", xbits)
        olen = len_v
        # ZIL: <PUT ...>
        _.zil_sdk.table_put(
            tbl,
            _.zil_sdk.zstate_get("P-MATCHLEN"),
            _.zil_sdk.table_get(tbl, _.zil_sdk.zstate_get("P-MATCHLEN")) - len_v,
        )
        # ZIL: <AGAIN ...>
        lookup("again")
    else:
        if len_v == 0:
            len_v = olen
        if not context.player == context.player:
            # ZIL: <CANT-ORPHAN ...>
            _.zork_thing.invoke_verb("cant-orphan")
            return False
        elif vrb and _.zil_sdk.zstate_get("P-NAM"):
            # ZIL: <WHICH-PRINT ...>
            _.zork_thing.invoke_verb("which-print", tlen, len_v, tbl)
            _.zil_sdk.zstate_set("P-ACLAUSE", cond([["EQUAL?", ".TBL", "P-PRSO"], "P-NC1"], ["T", "P-NC2"]))
            _.zil_sdk.zstate_set("P-AADJ", _.zil_sdk.zstate_get("P-ADJ"))
            _.zil_sdk.zstate_set("P-ANAM", _.zil_sdk.zstate_get("P-NAM"))
            # ZIL: <ORPHAN ...>
            _.zork_thing.invoke_verb("orphan")
            _.zil_sdk.zstate_set("P-OFLAG", True)
        elif vrb:
            print("There seems to be a noun missing in that sentence!")
        _.zil_sdk.zstate_set("P-NAM", None)
        _.zil_sdk.zstate_set("P-ADJ", None)
        return False
if len_v == 0 and gcheck:
    if vrb:
        _.zil_sdk.zstate_set("P-SLOCBITS", xbits)
        if _.zil_sdk.zstate_get("LIT") or player_verb in ["tell"]:
            # ZIL: <OBJ-FOUND ...>
            _.zork_thing.invoke_verb("obj-found", _.get_property("not_here_object"), tbl)
            _.zil_sdk.zstate_set("P-XNAM", _.zil_sdk.zstate_get("P-NAM"))
            _.zil_sdk.zstate_set("P-XADJ", _.zil_sdk.zstate_get("P-ADJ"))
            _.zil_sdk.zstate_set("P-XADJN", _.zil_sdk.zstate_get("P-ADJN"))
            _.zil_sdk.zstate_set("P-NAM", None)
            _.zil_sdk.zstate_set("P-ADJ", None)
            _.zil_sdk.zstate_set("P-ADJN", None)
            return True
        else:
            print("It's too dark to see!")
    _.zil_sdk.zstate_set("P-NAM", None)
    _.zil_sdk.zstate_set("P-ADJ", None)
    return False
elif len_v == 0:
    gcheck = True
    # ZIL: <AGAIN ...>
    lookup("again")
_.zil_sdk.zstate_set("P-SLOCBITS", xbits)
_.zil_sdk.zstate_set("P-NAM", None)
_.zil_sdk.zstate_set("P-ADJ", None)
return True
