#!moo verb go-next --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: GO-NEXT
# params: TBL
# aux: VAL

tbl = args[0] if len(args) > 0 else None
val = None

if val := _.zork_thing.invoke_verb("lkp", context.player.location, tbl):
    if not _.zork_thing.invoke_verb("goto", val):
        return 2
    else:
        return 1
