#!moo verb gwim --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: GWIM
# params: GBIT, LBIT, PREP
# aux: OBJ

gbit = args[0] if len(args) > 0 else None
lbit = args[1] if len(args) > 1 else None
prep = args[2] if len(args) > 2 else None
obj = None

if gbit == _.zil_sdk.zstate_get("RMUNGBIT"):
    return _.zil_sdk.zstate_get("ROOMS")
_.zil_sdk.zstate_set("P-GWIMBIT", gbit)
_.zil_sdk.zstate_set("P-SLOCBITS", lbit)
# ZIL: <PUT ...>
_.zil_sdk.table_put(_.zil_sdk.zstate_get("P-MERGE"), _.zil_sdk.zstate_get("P-MATCHLEN"), 0)
if _.zork_thing.invoke_verb("get-object", _.zil_sdk.zstate_get("P-MERGE")):
    _.zil_sdk.zstate_set("P-GWIMBIT", 0)
    if _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-MERGE"), _.zil_sdk.zstate_get("P-MATCHLEN")) == 1:
        obj = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-MERGE"), 1)
        print("(", end="")
        if not prep == 0 and not _.zil_sdk.zstate_get("P-END-ON-PREP"):
            print(str((prep := _.zork_thing.invoke_verb("prep-find", prep))), end="")
            if prep == _.zil_sdk.zstate_get("W?OUT"):
                print(" of", end="")
            print(" ", end="")
            if obj == _.get_property("hands"):
                print("your hands", end="")
            else:
                print("the " + _.zil_sdk.desc(obj), end="")
            print(")")
        else:
            print(_.zil_sdk.desc(obj) + ")")
        return obj
else:
    _.zil_sdk.zstate_set("P-GWIMBIT", 0)
    return False
