#!moo verb hit-spot --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: HIT-SPOT

if context.parser.get_dobj() == _.get_property("water") and not _.zil_sdk.global_in(
    _.get_property("global_water"), context.player.location
):
    _.zil_sdk.remove(context.parser.get_dobj())
return print("Thank you very much. I was rather thirsty (from all this talking,\nprobably).")
