#!moo verb idrop --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: IDROP

if (
    not context.parser.get_dobj().location == context.player
    and not context.parser.get_dobj().location.location == context.player
):
    print("You're not carrying the " + _.zil_sdk.desc(context.parser.get_dobj()) + ".")
    return False
elif not context.parser.get_dobj().location == context.player and not _.zil_sdk.flag(
    context.parser.get_dobj().location, "open"
):
    print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " is closed.")
    return False
else:
    _.zil_sdk.move(context.parser.get_dobj(), context.player.location)
    return True
