#!moo verb inbuf-add --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: INBUF-ADD
# params: LEN, BEG, SLOT
# aux: DBEG, CTR, TMP

len_v = args[0] if len(args) > 0 else None
beg = args[1] if len(args) > 1 else None
slot = args[2] if len(args) > 2 else None
dbeg = None
ctr = 0
tmp = None

if tmp := _.zil_sdk.table_get(_.zil_sdk.zstate_get("OOPS-TABLE"), _.zil_sdk.zstate_get("O-END")):
    dbeg = tmp
else:
    dbeg = _.zil_sdk.table_get(
        _.zil_sdk.zstate_get("AGAIN-LEXV"),
        (tmp := _.zil_sdk.table_get(_.zil_sdk.zstate_get("OOPS-TABLE"), _.zil_sdk.zstate_get("O-LENGTH"))),
    ) + _.zil_sdk.table_get(_.zil_sdk.zstate_get("AGAIN-LEXV"), tmp + 1)
# ZIL: <PUT ...>
_.zil_sdk.table_put(_.zil_sdk.zstate_get("OOPS-TABLE"), _.zil_sdk.zstate_get("O-END"), dbeg + len_v)
while True:
    # ZIL: <PUTB ...>
    putb(
        _.zil_sdk.zstate_get("OOPS-INBUF"), dbeg + ctr, _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-INBUF"), beg + ctr)
    )
    ctr = ctr + 1
    if ctr == len_v:
        break
# ZIL: <PUTB ...>
putb(_.zil_sdk.zstate_get("AGAIN-LEXV"), slot, dbeg)
# ZIL: <PUTB ...>
return putb(_.zil_sdk.zstate_get("AGAIN-LEXV"), slot - 1, len_v)
