#!moo verb itake-check --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: ITAKE-CHECK
# params: TBL, IBITS
# aux: PTR, OBJ, TAKEN

tbl = args[0] if len(args) > 0 else None
ibits = args[1] if len(args) > 1 else None
ptr = None
obj = None
taken = None

_.zil_sdk.zstate_get("#DECL")
if (
    (ptr := _.zil_sdk.table_get(tbl, _.zil_sdk.zstate_get("P-MATCHLEN")))
    and btst(ibits, _.zil_sdk.zstate_get("SHAVE"))
    or btst(ibits, _.zil_sdk.zstate_get("STAKE"))
):
    while True:
        if (ptr := ptr - 1) < 0:
            break
        else:
            obj = _.zil_sdk.table_get(tbl, ptr + 1)
            if obj == _.get_property("it"):
                if not _.zork_thing.invoke_verb("accessible?", _.zil_sdk.zstate_get("P-IT-OBJECT")):
                    print("I don't see what you're referring to.")
                    return False
                else:
                    obj = _.zil_sdk.zstate_get("P-IT-OBJECT")
            if not _.zork_thing.invoke_verb("held?", obj) and not obj in (
                _.get_property("hands"),
                _.get_property("me"),
            ):
                _.zil_sdk.zstate_set("PRSO", obj)
                if _.zil_sdk.flag(obj, "trytakebit"):
                    taken = True
                elif not context.player == _.get_property("adventurer"):
                    taken = None
                elif btst(ibits, _.zil_sdk.zstate_get("STAKE")) and _.zork_thing.invoke_verb("itake") == True:
                    taken = None
                else:
                    taken = True
                if (
                    taken
                    and btst(ibits, _.zil_sdk.zstate_get("SHAVE"))
                    and context.player == _.get_property("adventurer")
                ):
                    if obj == _.get_property("not_here_object"):
                        print("You don't have that!")
                        return False
                    print("You don't have the ", end="")
                    # ZIL: <PRINTD ...>
                    printd(obj)
                    print(".")
                    return False
                elif not taken and context.player == _.get_property("adventurer"):
                    return print("(Taken)")
else:
    pass
