#!moo verb leaves-appear --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: LEAVES-APPEAR

if not _.zil_sdk.flag(_.get_property("grate"), "open") and not _.zil_sdk.zstate_get("GRATE-REVEALED"):
    if player_verb in ["move", "take", "get", "pick"]:
        print("In disturbing the pile of leaves, a grating is revealed.")
    else:
        print("With the leaves moved, a grating is revealed.")
    _.zil_sdk.set_flag(_.get_property("grate"), "invisible", False)
    return _.zil_sdk.zstate_set("GRATE-REVEALED", True)
