#!moo verb main-loop-1 --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
from moo.sdk import context, lookup
# ZIL routine: MAIN-LOOP-1
# aux: ICNT, OCNT, NUM, CNT, OBJ, TBL, V, PTBL, OBJ1, TMP, O, I

icnt = None
ocnt = None
num = None
cnt = None
obj = None
tbl = None
v = None
ptbl = None
obj1 = None
tmp = None
o = None
i = None

cnt = 0
obj = None
ptbl = True
if _.zil_sdk.zstate_set("P-WON", _.zork_thing.invoke_verb("parser")):
    icnt = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-PRSI"), _.zil_sdk.zstate_get("P-MATCHLEN"))
    ocnt = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-PRSO"), _.zil_sdk.zstate_get("P-MATCHLEN"))
    if _.zil_sdk.zstate_get("P-IT-OBJECT") and _.zork_thing.invoke_verb(
        "accessible?", _.zil_sdk.zstate_get("P-IT-OBJECT")
    ):
        tmp = None
        while True:
            if (cnt := cnt + 1) > icnt:
                break
            else:
                if _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-PRSI"), cnt) == _.get_property("it"):
                    # ZIL: <PUT ...>
                    _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-PRSI"), cnt, _.zil_sdk.zstate_get("P-IT-OBJECT"))
                    tmp = True
                    break
        if not tmp:
            cnt = 0
            while True:
                if (cnt := cnt + 1) > ocnt:
                    break
                else:
                    if _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-PRSO"), cnt) == _.get_property("it"):
                        # ZIL: <PUT ...>
                        _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-PRSO"), cnt, _.zil_sdk.zstate_get("P-IT-OBJECT"))
                        break
        cnt = 0
    num = cond(
        [["0?", ".OCNT"], ".OCNT"],
        [
            ["G?", ".OCNT", 1],
            ["SET", "TBL", "P-PRSO"],
            ["COND", (["0?", ".ICNT"], ["SET", "OBJ"]), ("T", ["SET", "OBJ", ["GET", "P-PRSI", 1]])],
            ".OCNT",
        ],
        [["G?", ".ICNT", 1], ["SET", "PTBL"], ["SET", "TBL", "P-PRSI"], ["SET", "OBJ", ["GET", "P-PRSO", 1]], ".ICNT"],
        ["T", 1],
    )
    if not obj and icnt == 1:
        obj = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-PRSI"), 1)
    if verb_name == _.zil_sdk.zstate_get("V?WALK") and not _.zil_sdk.zstate_get("P-WALK-DIR") == 0:
        v = _.zil_sdk.perform(verb_name, context.parser.get_dobj(), None)
    elif num == 0:
        if (
            band(
                _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-SYNTAX"), _.zil_sdk.zstate_get("P-SBITS")),
                _.zil_sdk.zstate_get("P-SONUMS"),
            )
            == 0
        ):
            v = _.zil_sdk.perform(verb_name, None, None)
            return _.zil_sdk.zstate_set("PRSO", None)
        elif not _.zil_sdk.zstate_get("LIT"):
            return print("It's too dark to see.")
        else:
            print("It's not clear what you're referring to.")
            v = None
    else:
        _.zil_sdk.zstate_set("P-NOT-HERE", 0)
        _.zil_sdk.zstate_set("P-MULT", None)
        if num > 1:
            return _.zil_sdk.zstate_set("P-MULT", True)
        tmp = None
        while True:
            if (cnt := cnt + 1) > num:
                if _.zil_sdk.zstate_get("P-NOT-HERE") > 0:
                    print("The ", end="")
                    if not _.zil_sdk.zstate_get("P-NOT-HERE") == num:
                        print("other ", end="")
                    print("object", end="")
                    if not _.zil_sdk.zstate_get("P-NOT-HERE") == 1:
                        print("s", end="")
                    print(" that you mentioned ", end="")
                    if not _.zil_sdk.zstate_get("P-NOT-HERE") == 1:
                        print("are", end="")
                    else:
                        print("is", end="")
                    print("n't here.")
                elif not tmp:
                    print("There's nothing here you can take.")
                break
            else:
                if ptbl:
                    obj1 = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-PRSO"), cnt)
                else:
                    obj1 = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-PRSI"), cnt)
                o = cond([".PTBL", ".OBJ1"], ["T", ".OBJ"])
                i = cond([".PTBL", ".OBJ"], ["T", ".OBJ1"])
                if num > 1 or _.zil_sdk.table_get(
                    _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1")), 0
                ) == _.zil_sdk.zstate_get("W?ALL"):
                    v = context.player.location
                    if o == _.get_property("not_here_object"):
                        _.zil_sdk.zstate_set("P-NOT-HERE", _.zil_sdk.zstate_get("P-NOT-HERE") + 1)
                        # ZIL: <AGAIN ...>
                        return lookup("again")
                    elif (
                        player_verb in ["take", "get", "pick"]
                        and i
                        and _.zil_sdk.table_get(
                            _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1")), 0
                        )
                        == _.zil_sdk.zstate_get("W?ALL")
                        and not o.location == i
                    ):
                        # ZIL: <AGAIN ...>
                        return lookup("again")
                    elif (
                        _.zil_sdk.zstate_get("P-GETFLAGS") == _.zil_sdk.zstate_get("P-ALL")
                        and player_verb in ["take", "get", "pick"]
                        and not o.location in (context.player, context.player.location, v)
                        and not o.location == i
                        and not _.zil_sdk.flag(o.location, "surfacebit")
                        or not _.zil_sdk.flag(o, "takeable")
                        or _.zil_sdk.flag(o, "trytakebit")
                    ):
                        # ZIL: <AGAIN ...>
                        return lookup("again")
                    else:
                        if obj1 == _.get_property("it"):
                            # ZIL: <PRINTD ...>
                            printd(_.zil_sdk.zstate_get("P-IT-OBJECT"))
                        else:
                            # ZIL: <PRINTD ...>
                            printd(obj1)
                        return print(": ", end="")
                _.zil_sdk.zstate_set("PRSO", o)
                _.zil_sdk.zstate_set("PRSI", i)
                tmp = True
                v = _.zil_sdk.perform(verb_name, context.parser.get_dobj(), context.parser.get_iobj())
                if v == _.zil_sdk.zstate_get("M-FATAL"):
                    break
    if not v == _.zil_sdk.zstate_get("M-FATAL"):
        v = apply(_.zil_sdk.getp(context.player.location, "action"), "M-END")
    if v == _.zil_sdk.zstate_get("M-FATAL"):
        return _.zil_sdk.zstate_set("P-CONT", None)
else:
    return _.zil_sdk.zstate_set("P-CONT", None)
if _.zil_sdk.zstate_get("ZORK-NUMBER") == 3:
    if not _.zil_sdk.zstate_get("CLEFT-QUEUED?"):
        _.zil_sdk.queue("i-cleft", 70 + random.randint(1, 70))
        return _.zil_sdk.zstate_set("CLEFT-QUEUED?", True)
else:
    # ZIL: <NULL-F ...>
    return _.zork_thing.invoke_verb("null-f")
if _.zil_sdk.zstate_get("P-WON"):
    if player_verb in [
        "tell",
        "brief",
        "superbrief",
        "verbose",
        "save",
        "version",
        "quit",
        "q",
        "restart",
        "score",
        "script",
        "unscript",
        "restore",
    ]:
        return True
    else:
        v = _.zork_thing.invoke_verb("clocker")
