#!moo verb meta-loc --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: META-LOC
# params: OBJ

obj = args[0] if len(args) > 0 else None

while True:
    if not obj:
        return False
    elif obj.location == _.get_property("global_objects"):
        return _.get_property("global_objects")
    if obj.location == _.zil_sdk.zstate_get("ROOMS"):
        return obj
    else:
        obj = obj.location
