#!moo verb move-all --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: MOVE-ALL
# params: FROM, TO
# aux: X, N

from_v = args[0] if len(args) > 0 else None
to = args[1] if len(args) > 1 else None
x = None
n = None

if x := from_v.contents.first():
    while True:
        if not x:
            break
        n = _.zil_sdk.next_sibling(x)
        _.zil_sdk.set_flag(x, "invisible", False)
        _.zil_sdk.move(x, to)
        x = n
