#!moo verb mung-room --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: MUNG-ROOM
# params: RM, STR

rm = args[0] if len(args) > 0 else None
str_v = args[1] if len(args) > 1 else None

if _.zil_sdk.zstate_get("ZORK-NUMBER") == 2:
    if rm == _.zil_sdk.zstate_get("INSIDE-BARROW"):
        return False
else:
    True
_.zil_sdk.set_flag(rm, "rmungbit", True)
return rm.set_property("description", str_v)
