#!moo verb obj-found --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: OBJ-FOUND
# params: OBJ, TBL
# aux: PTR

obj = args[0] if len(args) > 0 else None
tbl = args[1] if len(args) > 1 else None
ptr = None

ptr = _.zil_sdk.table_get(tbl, _.zil_sdk.zstate_get("P-MATCHLEN"))
# ZIL: <PUT ...>
_.zil_sdk.table_put(tbl, ptr + 1, obj)
# ZIL: <PUT ...>
return _.zil_sdk.table_put(tbl, _.zil_sdk.zstate_get("P-MATCHLEN"), ptr + 1)
