#!moo verb open-close --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: OPEN-CLOSE
# params: OBJ, STROPN, STRCLS

obj = args[0] if len(args) > 0 else None
stropn = args[1] if len(args) > 1 else None
strcls = args[2] if len(args) > 2 else None

if player_verb in ["open"]:
    if _.zil_sdk.flag(obj, "open"):
        print(_.zil_sdk.pick(_.zil_sdk.zstate_get("DUMMY")), end="")
    else:
        print(stropn, end="")
        _.zil_sdk.set_flag(obj, "open", True)
    return print()
elif player_verb in ["close", "shut"]:
    if _.zil_sdk.flag(obj, "open"):
        print(strcls, end="")
        _.zil_sdk.set_flag(obj, "open", False)
        True
    else:
        print(_.zil_sdk.pick(_.zil_sdk.zstate_get("DUMMY")), end="")
    return print()
