#!moo verb orphan --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: ORPHAN
# params: D1, D2
# aux: CNT

d1 = args[0] if len(args) > 0 else None
d2 = args[1] if len(args) > 1 else None
cnt = -1

if not _.zil_sdk.zstate_get("P-MERGED"):
    # ZIL: <PUT ...>
    return _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-OCLAUSE"), _.zil_sdk.zstate_get("P-MATCHLEN"), 0)
# ZIL: <PUT ...>
_.zil_sdk.table_put(_.zil_sdk.zstate_get("P-OVTBL"), 0, _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-VTBL"), 0))
# ZIL: <PUTB ...>
putb(_.zil_sdk.zstate_get("P-OVTBL"), 2, _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-VTBL"), 2))
# ZIL: <PUTB ...>
putb(_.zil_sdk.zstate_get("P-OVTBL"), 3, _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-VTBL"), 3))
while True:
    if igrtr_p(cnt, _.zil_sdk.zstate_get("P-ITBLLEN")):
        break
    else:
        # ZIL: <PUT ...>
        return _.zil_sdk.table_put(
            _.zil_sdk.zstate_get("P-OTBL"), cnt, _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), cnt)
        )
if _.zil_sdk.zstate_get("P-NCN") == 2:
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(
        _.zil_sdk.zstate_get("P-CCTBL"), _.zil_sdk.zstate_get("CC-SBPTR"), _.zil_sdk.zstate_get("P-NC2")
    )
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(
        _.zil_sdk.zstate_get("P-CCTBL"), _.zil_sdk.zstate_get("CC-SEPTR"), _.zil_sdk.zstate_get("P-NC2L")
    )
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(
        _.zil_sdk.zstate_get("P-CCTBL"), _.zil_sdk.zstate_get("CC-DBPTR"), _.zil_sdk.zstate_get("P-NC2")
    )
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(
        _.zil_sdk.zstate_get("P-CCTBL"), _.zil_sdk.zstate_get("CC-DEPTR"), _.zil_sdk.zstate_get("P-NC2L")
    )
    # ZIL: <CLAUSE-COPY ...>
    return _.zork_thing.invoke_verb("clause-copy", _.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-OTBL"))
if not _.zil_sdk.zstate_get("P-NCN") < 1:
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(
        _.zil_sdk.zstate_get("P-CCTBL"), _.zil_sdk.zstate_get("CC-SBPTR"), _.zil_sdk.zstate_get("P-NC1")
    )
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(
        _.zil_sdk.zstate_get("P-CCTBL"), _.zil_sdk.zstate_get("CC-SEPTR"), _.zil_sdk.zstate_get("P-NC1L")
    )
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(
        _.zil_sdk.zstate_get("P-CCTBL"), _.zil_sdk.zstate_get("CC-DBPTR"), _.zil_sdk.zstate_get("P-NC1")
    )
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(
        _.zil_sdk.zstate_get("P-CCTBL"), _.zil_sdk.zstate_get("CC-DEPTR"), _.zil_sdk.zstate_get("P-NC1L")
    )
    # ZIL: <CLAUSE-COPY ...>
    return _.zork_thing.invoke_verb("clause-copy", _.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-OTBL"))
if d1:
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(
        _.zil_sdk.zstate_get("P-OTBL"),
        _.zil_sdk.zstate_get("P-PREP1"),
        _.zil_sdk.table_get(d1, _.zil_sdk.zstate_get("P-SPREP1")),
    )
    # ZIL: <PUT ...>
    return _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-OTBL"), _.zil_sdk.zstate_get("P-NC1"), 1)
elif d2:
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(
        _.zil_sdk.zstate_get("P-OTBL"),
        _.zil_sdk.zstate_get("P-PREP2"),
        _.zil_sdk.table_get(d2, _.zil_sdk.zstate_get("P-SPREP2")),
    )
    # ZIL: <PUT ...>
    return _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-OTBL"), _.zil_sdk.zstate_get("P-NC2"), 1)
