#!moo verb orphan-merge --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: ORPHAN-MERGE
# aux: CNT, TEMP, VERB, BEG, END, ADJ, WRD

cnt = -1
temp = None
verb = None
beg = None
end = None
adj = None
wrd = None

_.zil_sdk.zstate_set("P-OFLAG", None)
if (
    _.zork_thing.invoke_verb(
        "wt?",
        (
            wrd := _.zil_sdk.table_get(
                _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-VERBN")), 0
            )
        ),
        _.zil_sdk.zstate_get("PS?VERB"),
        _.zil_sdk.zstate_get("P1?VERB"),
    )
    == _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-OTBL"), _.zil_sdk.zstate_get("P-VERB"))
    or not _.zork_thing.invoke_verb("wt?", wrd, _.zil_sdk.zstate_get("PS?ADJECTIVE")) == 0
):
    adj = True
elif (
    not _.zork_thing.invoke_verb("wt?", wrd, _.zil_sdk.zstate_get("PS?OBJECT"), _.zil_sdk.zstate_get("P1?OBJECT")) == 0
    and _.zil_sdk.zstate_get("P-NCN") == 0
):
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-VERB"), 0)
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-VERBN"), 0)
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(
        _.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1"), rest(_.zil_sdk.zstate_get("P-LEXV"), 2)
    )
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(
        _.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1L"), rest(_.zil_sdk.zstate_get("P-LEXV"), 6)
    )
    _.zil_sdk.zstate_set("P-NCN", 1)
if (
    not (verb := _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-VERB"))) == 0
    and not adj
    and not verb == _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-OTBL"), _.zil_sdk.zstate_get("P-VERB"))
):
    return False
elif _.zil_sdk.zstate_get("P-NCN") == 2:
    return False
elif _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-OTBL"), _.zil_sdk.zstate_get("P-NC1")) == 1:
    if (
        temp := _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-PREP1"))
    ) == _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-OTBL"), _.zil_sdk.zstate_get("P-PREP1")) or temp == 0:
        if adj:
            # ZIL: <PUT ...>
            _.zil_sdk.table_put(
                _.zil_sdk.zstate_get("P-OTBL"), _.zil_sdk.zstate_get("P-NC1"), rest(_.zil_sdk.zstate_get("P-LEXV"), 2)
            )
            if _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1L")) == 0:
                # ZIL: <PUT ...>
                _.zil_sdk.table_put(
                    _.zil_sdk.zstate_get("P-ITBL"),
                    _.zil_sdk.zstate_get("P-NC1L"),
                    rest(_.zil_sdk.zstate_get("P-LEXV"), 6),
                )
            if _.zil_sdk.zstate_get("P-NCN") == 0:
                _.zil_sdk.zstate_set("P-NCN", 1)
        else:
            # ZIL: <PUT ...>
            _.zil_sdk.table_put(
                _.zil_sdk.zstate_get("P-OTBL"),
                _.zil_sdk.zstate_get("P-NC1"),
                _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1")),
            )
        # ZIL: <PUT ...>
        _.zil_sdk.table_put(
            _.zil_sdk.zstate_get("P-OTBL"),
            _.zil_sdk.zstate_get("P-NC1L"),
            _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1L")),
        )
    else:
        return False
elif _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-OTBL"), _.zil_sdk.zstate_get("P-NC2")) == 1:
    if (
        temp := _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-PREP1"))
    ) == _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-OTBL"), _.zil_sdk.zstate_get("P-PREP2")) or temp == 0:
        if adj:
            # ZIL: <PUT ...>
            _.zil_sdk.table_put(
                _.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1"), rest(_.zil_sdk.zstate_get("P-LEXV"), 2)
            )
            if _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1L")) == 0:
                # ZIL: <PUT ...>
                _.zil_sdk.table_put(
                    _.zil_sdk.zstate_get("P-ITBL"),
                    _.zil_sdk.zstate_get("P-NC1L"),
                    rest(_.zil_sdk.zstate_get("P-LEXV"), 6),
                )
        # ZIL: <PUT ...>
        _.zil_sdk.table_put(
            _.zil_sdk.zstate_get("P-OTBL"),
            _.zil_sdk.zstate_get("P-NC2"),
            _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1")),
        )
        # ZIL: <PUT ...>
        _.zil_sdk.table_put(
            _.zil_sdk.zstate_get("P-OTBL"),
            _.zil_sdk.zstate_get("P-NC2L"),
            _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1L")),
        )
        _.zil_sdk.zstate_set("P-NCN", 2)
    else:
        return False
elif not _.zil_sdk.zstate_get("P-ACLAUSE") == 0:
    if not _.zil_sdk.zstate_get("P-NCN") == 1 and not adj:
        _.zil_sdk.zstate_set("P-ACLAUSE", None)
        return False
    else:
        beg = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1"))
        if adj:
            beg = rest(_.zil_sdk.zstate_get("P-LEXV"), 2)
            adj = None
        end = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1L"))
        while True:
            wrd = _.zil_sdk.table_get(beg, 0)
            if beg == end:
                if adj:
                    # ZIL: <ACLAUSE-WIN ...>
                    _.zork_thing.invoke_verb("aclause-win", adj)
                    break
                else:
                    _.zil_sdk.zstate_set("P-ACLAUSE", None)
                    return False
            elif (
                not adj
                and btst(
                    _.zil_sdk.table_get(wrd, _.zil_sdk.zstate_get("P-PSOFF")), _.zil_sdk.zstate_get("PS?ADJECTIVE")
                )
                or wrd in (_.zil_sdk.zstate_get("W?ALL"), _.zil_sdk.zstate_get("W?ONE"))
            ):
                adj = wrd
            elif wrd == _.zil_sdk.zstate_get("W?ONE"):
                # ZIL: <ACLAUSE-WIN ...>
                _.zork_thing.invoke_verb("aclause-win", adj)
                break
            elif btst(_.zil_sdk.table_get(wrd, _.zil_sdk.zstate_get("P-PSOFF")), _.zil_sdk.zstate_get("PS?OBJECT")):
                if wrd == _.zil_sdk.zstate_get("P-ANAM"):
                    # ZIL: <ACLAUSE-WIN ...>
                    _.zork_thing.invoke_verb("aclause-win", adj)
                else:
                    # ZIL: <NCLAUSE-WIN ...>
                    _.zork_thing.invoke_verb("nclause-win")
                break
            beg = rest(beg, _.zil_sdk.zstate_get("P-WORDLEN"))
            if end == 0:
                end = beg
                _.zil_sdk.zstate_set("P-NCN", 1)
                # ZIL: <PUT ...>
                _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1"), back(beg, 4))
                # ZIL: <PUT ...>
                _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-NC1L"), beg)
# ZIL: <PUT ...>
_.zil_sdk.table_put(_.zil_sdk.zstate_get("P-VTBL"), 0, _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-OVTBL"), 0))
# ZIL: <PUTB ...>
putb(_.zil_sdk.zstate_get("P-VTBL"), 2, _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-OVTBL"), 2))
# ZIL: <PUTB ...>
putb(_.zil_sdk.zstate_get("P-VTBL"), 3, _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-OVTBL"), 3))
# ZIL: <PUT ...>
_.zil_sdk.table_put(_.zil_sdk.zstate_get("P-OTBL"), _.zil_sdk.zstate_get("P-VERBN"), _.zil_sdk.zstate_get("P-VTBL"))
# ZIL: <PUTB ...>
putb(_.zil_sdk.zstate_get("P-VTBL"), 2, 0)
while True:
    if (cnt := cnt + 1) > _.zil_sdk.zstate_get("P-ITBLLEN"):
        _.zil_sdk.zstate_set("P-MERGED", True)
        return True
    else:
        # ZIL: <PUT ...>
        _.zil_sdk.table_put(
            _.zil_sdk.zstate_get("P-ITBL"), cnt, _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-OTBL"), cnt)
        )
return True
