#!moo verb other-side --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: OTHER-SIDE
# params: DOBJ
# aux: P, TX

dobj = args[0] if len(args) > 0 else None
p = 0
tx = None

while True:
    if (p := nextp(context.player.location, p)) < _.zil_sdk.zstate_get("LOW-DIRECTION"):
        break
    else:
        tx = getpt(context.player.location, p)
        if (
            ptsize(tx) == _.zil_sdk.zstate_get("DEXIT")
            and _.zil_sdk.table_get(tx, _.zil_sdk.zstate_get("DEXITOBJ")) == dobj
        ):
            return p
