#!moo verb dig find follow get pick take where --on $pathobj --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: PATH-OBJECT

if player_verb in ["take", "get", "pick", "follow"]:
    return print("You must specify a direction to go.")
elif player_verb in ["find", "where"]:
    return print("I can't help you there....")
elif player_verb in ["dig"]:
    return print("Not a chance.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
