#!moo verb prep-find --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: PREP-FIND
# params: PREP
# aux: CNT, SIZE

prep = args[0] if len(args) > 0 else None
cnt = 0
size = None

size = _.zil_sdk.table_get(_.zil_sdk.zstate_get("PREPOSITIONS"), 0) * 2
while True:
    if igrtr_p(cnt, size):
        return False
    elif _.zil_sdk.table_get(_.zil_sdk.zstate_get("PREPOSITIONS"), cnt) == prep:
        return _.zil_sdk.table_get(_.zil_sdk.zstate_get("PREPOSITIONS"), cnt - 1)
