#!moo verb randomize-objects --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
from moo.sdk import context
# ZIL routine: RANDOMIZE-OBJECTS
# aux: R, F, N, L

r = None
f = None
n = None
l = None

if _.get_property("lamp").location == context.player:
    return _.zil_sdk.move(_.get_property("lamp"), _.get_property("living_room"))
if _.get_property("coffin").location == context.player:
    return _.zil_sdk.move(_.get_property("coffin"), _.get_property("egypt_room"))
_.get_property("sword").set_property("tvalue", 0)
n = context.player.contents.first()
l = _.zil_sdk.table_get(_.zil_sdk.zstate_get("ABOVE-GROUND"), 0)
while True:
    f = n
    if not f:
        break
    n = _.zil_sdk.next_sibling(f)
    if _.zil_sdk.getp(f, "tvalue") > 0:
        while True:
            if not r:
                r = _.zil_sdk.zstate_get("ROOMS").contents.first()
            if _.zil_sdk.flag(r, "outdoor") and not _.zil_sdk.flag(r, "onbit") and random.randint(1, 100) <= 50:
                _.zil_sdk.move(f, r)
                break
            else:
                r = _.zil_sdk.next_sibling(r)
    else:
        return _.zil_sdk.move(f, _.zil_sdk.table_get(_.zil_sdk.zstate_get("ABOVE-GROUND"), random.randint(1, l)))
