#!moo verb recover-stiletto --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import lookup
# ZIL routine: RECOVER-STILETTO

if _.get_property("stiletto").location == lookup("thief").location:
    _.zil_sdk.set_flag(_.get_property("stiletto"), "obvious", True)
    return _.zil_sdk.move(_.get_property("stiletto"), lookup("thief"))
