#!moo verb remove-carefully --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: REMOVE-CAREFULLY
# params: OBJ
# aux: OLIT

obj = args[0] if len(args) > 0 else None
olit = None

if obj == _.zil_sdk.zstate_get("P-IT-OBJECT"):
    _.zil_sdk.zstate_set("P-IT-OBJECT", None)
olit = _.zil_sdk.zstate_get("LIT")
_.zil_sdk.remove(obj)
_.zil_sdk.zstate_set("LIT", _.zork_thing.invoke_verb("lit?", context.player.location))
if olit and not olit == _.zil_sdk.zstate_get("LIT"):
    print("You are left in the dark...")
return True
