#!moo verb search-list --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: SEARCH-LIST
# params: OBJ, TBL, LVL
# aux: FLS, NOBJ

obj = args[0] if len(args) > 0 else None
tbl = args[1] if len(args) > 1 else None
lvl = args[2] if len(args) > 2 else None
fls = None
nobj = None

if obj := obj.contents.first():
    while True:
        if (
            not lvl == _.zil_sdk.zstate_get("P-SRCBOT")
            and getpt(obj, _.zil_sdk.zstate_get("P?SYNONYM"))
            and _.zork_thing.invoke_verb("this-it?", obj, tbl)
        ):
            # ZIL: <OBJ-FOUND ...>
            return _.zork_thing.invoke_verb("obj-found", obj, tbl)
        if (
            not lvl == _.zil_sdk.zstate_get("P-SRCTOP")
            or _.zil_sdk.flag(obj, "searchable")
            or _.zil_sdk.flag(obj, "surfacebit")
            and (nobj := obj.contents.first())
            and _.zil_sdk.flag(obj, "open")
            or _.zil_sdk.flag(obj, "transparent")
        ):
            fls = _.zork_thing.invoke_verb(
                "search-list",
                obj,
                tbl,
                cond(
                    [["FSET?", ".OBJ", "SURFACEBIT"], "P-SRCALL"],
                    [["FSET?", ".OBJ", "SEARCHBIT"], "P-SRCALL"],
                    ["T", "P-SRCTOP"],
                ),
            )
        if obj := _.zil_sdk.next_sibling(obj):
            pass
        else:
            break
