#!moo verb slider --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: SLIDER
# params: OBJ

obj = args[0] if len(args) > 0 else None

if _.zil_sdk.flag(obj, "takeable"):
    print("The " + _.zil_sdk.desc(obj) + " falls into the slide and is gone.")
    if obj == _.get_property("water"):
        return _.zil_sdk.remove(obj)
    else:
        return _.zil_sdk.move(obj, _.get_property("cellar"))
else:
    return print(_.zil_sdk.pick(_.zil_sdk.zstate_get("YUKS")))
