#!moo verb stupid-container --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: STUPID-CONTAINER
# params: OBJ, STR

obj = args[0] if len(args) > 0 else None
str_v = args[1] if len(args) > 1 else None

if player_verb in ["open", "close", "shut"]:
    return print("The " + str_v + " are safely inside; there's no need to do that.")
elif player_verb in ["look-inside", "examine", "x", "describe", "what"]:
    return print("There are lots of " + str_v + " in there.")
elif player_verb in ["put", "place", "insert"] and context.parser.get_iobj() == obj:
    return print("Don't be silly. It wouldn't be a " + _.zil_sdk.desc(obj) + " anymore.")
