#!moo verb touch-all --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: TOUCH-ALL
# params: OBJ
# aux: F

obj = args[0] if len(args) > 0 else None
f = None

f = obj.contents.first()
while True:
    if not f:
        break
    else:
        _.zil_sdk.set_flag(f, "touchbit", True)
        if f.contents.first():
            # ZIL: <TOUCH-ALL ...>
            _.zork_thing.invoke_verb("touch-all", f)
    f = _.zil_sdk.next_sibling(f)
