#!moo verb trap-door-exit --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: TRAP-DOOR-EXIT

if _.zil_sdk.zstate_get("RUG-MOVED"):
    if _.zil_sdk.flag(_.get_property("trap_door"), "open"):
        return _.get_property("cellar")
    else:
        print("The trap door is closed.")
        # ZIL: <THIS-IS-IT ...>
        _.zork_thing.invoke_verb("this-is-it", _.get_property("trap_door"))
        return False
else:
    print("You can't go that way.")
    return False
