#!moo verb untie-from --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: UNTIE-FROM

if (
    context.parser.get_dobj() == _.get_property("rope")
    and _.zil_sdk.zstate_get("DOME-FLAG")
    and context.parser.get_iobj() == _.get_property("railing")
):
    return _.zil_sdk.perform(_.zil_sdk.zstate_get("V?UNTIE"), context.parser.get_dobj(), None)
else:
    return print("It's not attached to that!")
