#!moo verb weight --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: WEIGHT
# params: OBJ
# aux: CONT, WT

obj = args[0] if len(args) > 0 else None
cont = None
wt = 0

if cont := obj.contents.first():
    while True:
        if obj == context.player and _.zil_sdk.flag(cont, "wearbit"):
            wt = wt + 1
        else:
            wt = wt + _.zork_thing.invoke_verb("weight", cont)
        if not (cont := _.zil_sdk.next_sibling(cont)):
            break
return wt + obj.get_property("size")
