#!moo verb zmemq --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: ZMEMQ
# params: ITM, TBL, SIZE
# aux: CNT

itm = args[0] if len(args) > 0 else None
tbl = args[1] if len(args) > 1 else None
size = args[2] if len(args) > 2 else -1
cnt = 1

if not tbl:
    return False
if not size < 0:
    cnt = 0
else:
    size = _.zil_sdk.table_get(tbl, 0)
while True:
    if itm == _.zil_sdk.table_get(tbl, cnt):
        return rest(tbl, cnt * 2)
    elif igrtr_p(cnt, size):
        return False
