#!moo verb pre_fill --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: PRE-FILL
# aux: TX

player = context.player
parser = context.parser
global_water = lookup("global_water")
water = lookup("water")
tx = 0

if not (parser.get_iobj() if parser.has_iobj() else None):
    tx = getpt(player.here(), player.zstate_get("P?GLOBAL"))
    if tx and _.zork_thing.zmemqb(global_water, tx, ptsize(tx) - 1):
        _.perform(player.zstate_get("V?FILL"), parser.get_dobj(), global_water)
        return True
    elif water.location == player.location:
        _.perform(player.zstate_get("V?FILL"), parser.get_dobj(), water)
        return True
    else:
        print("There is nothing to fill it with.")
        return True
if (parser.get_iobj() if parser.has_iobj() else None) == water:
    return False
elif not (parser.get_iobj() if parser.has_iobj() else None) == global_water:
    _.perform(player.zstate_get("V?PUT"), (parser.get_iobj() if parser.has_iobj() else None), parser.get_dobj())
    return True
