#!moo verb pre_turn --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: PRE-TURN

player = context.player
parser = context.parser

if player.zstate_get("ZORK-NUMBER") == 3:
    if (parser.get_iobj() if parser.has_iobj() else None) == player.zstate_get("ROOMS") and parser.get_dobj() in (
        player.zstate_get("DIAL"),
        player.zstate_get("TM-DIAL"),
        player.zstate_get("T-BAR"),
    ):
        print("You should turn the " + parser.get_dobj().desc() + " to something.")
        return True
else:
    return True
if (
    (parser.get_iobj() if parser.has_iobj() else None) == player.zstate_get("ROOMS")
    and not parser.get_dobj() == lookup("book")
    if player.zstate_get("ZORK-NUMBER") == 1
    else (parser.get_iobj() if parser.has_iobj() else None) == player.zstate_get("ROOMS")
):
    print("Your bare hands don't appear to be enough.")
    return
elif not parser.get_dobj().flag("turnable"):
    print("You can't turn that!")
    return
