#!moo verb pre_move --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: PRE-MOVE

parser = context.parser

if _.zork_thing.is_held(parser.get_dobj()):
    print("You aren't an accomplished enough juggler.")
    return
