#!moo verb pre_drop --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: PRE-DROP

player = context.player
parser = context.parser

if parser.get_dobj() == player.location:
    _.perform(player.zstate_get("V?DISEMBARK"), parser.get_dobj(), None)
    return True
