#!moo verb describe_object --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: DESCRIBE-OBJECT
# params: OBJ, V?, LEVEL
# aux: STR, AV

player = context.player
obj = args[0] if len(args) > 0 else None
v_p = args[1] if len(args) > 1 else None
level = args[2] if len(args) > 2 else None
str_v = 0
av = 0

player.zstate_set("DESC-OBJECT", obj)
if level == 0 and (
    obj.invoke_verb("descfunc") if obj is not None and obj.has_verb("descfunc", recurse=False) else None
):
    return True
elif (
    level == 0 and not obj.flag("touchbit") and (str_v := obj.getp("description")) or (str_v := obj.getp("description"))
):
    print(str_v, end="")
    return
elif level == 0:
    print("There is a " + obj.desc() + " here", end="")
    if obj.flag("onbit"):
        print(" (providing light)", end="")
    print(".", end="")
    return
else:
    print(_.table_get(player.zstate_get("INDENTS"), level) + "A " + obj.desc(), end="")
    if obj.flag("onbit"):
        print(" (providing light)", end="")
        return
    elif obj.flag("wearbit") and obj.location == player:
        print(" (being worn)", end="")
        return
if player.zstate_get("ZORK-NUMBER") == 2:
    if obj == player.zstate_get("SPELL-VICTIM") and player.zstate_get("SPELL-USED") == player.zstate_get("W?FLOAT"):
        print(" (floating in midair)", end="")
        return
else:
    # ZIL: <NULL-F ...>
    return _.zork_thing.null_f()
if level == 0 and (av := player.location) and av.flag("vehicle"):
    print(" (outside the " + av.desc() + ")", end="")
    return
print()
if _.zork_thing.is_see_inside(obj) and obj.contents.first():
    # ZIL: <PRINT-CONT ...>
    return _.zork_thing.print_cont(obj, v_p, level)
