#!moo verb describe_room --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: DESCRIBE-ROOM
# params: LOOK?
# aux: V?, STR, AV

player = context.player
look_p = args[0] if len(args) > 0 else None
v_p = 0
str_v = 0
av = 0

v_p = look_p or player.zstate_get("VERBOSE")
if not player.zstate_get("LIT"):
    print("It is pitch black.", end="")
    if not player.zstate_get("SPRAYED?"):
        print(" You are likely to be eaten by a grue.", end="")
    print()
    if player.zstate_get("ZORK-NUMBER") == 3:
        if player.here() == player.zstate_get("DARK-2"):
            print(
                "The ground continues to slope upwards away from the lake. You can barely\ndetect a dim light from the east."
            )
    else:
        # ZIL: <NULL-F ...>
        _.zork_thing.null_f()
    return False
if not player.here().flag("touchbit"):
    player.here().set_flag("touchbit", True)
    v_p = True
if player.zstate_get("ZORK-NUMBER") == 1:
    if player.here().flag("maze"):
        player.here().set_flag("touchbit", False)
else:
    # ZIL: <NULL-F ...>
    _.zork_thing.null_f()
if player.here().location == player.zstate_get("ROOMS"):
    print(player.here().desc(), end="")
    if (av := player.location).flag("vehicle"):
        print(", in the " + av.desc(), end="")
    print()
if (
    look_p or not player.zstate_get("SUPER-BRIEF") or player.here() == player.zstate_get("ZORK3")
    if player.zstate_get("ZORK-NUMBER") == 2
    else look_p or not player.zstate_get("SUPER-BRIEF")
):
    av = player.location
    if v_p and (
        player.here().invoke_verb("look")
        if player.here() is not None and player.here().has_verb("look", recurse=False)
        else None
    ):
        return True
    elif v_p and (str_v := player.here().getp("description")):
        print(str_v)
    else:
        # ZIL: <APPLY ...>
        (
            player.here().invoke_verb("flashfunc")
            if player.here() is not None and player.here().has_verb("flashfunc", recurse=False)
            else None
        )
    if not player.here() == av and av.flag("vehicle"):
        # ZIL: <APPLY ...>
        (av.invoke_verb("look") if av is not None and av.has_verb("look", recurse=False) else None)
return True
