#!moo verb score_obj --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

# ZIL routine: SCORE-OBJ
# params: OBJ
# aux: TEMP

obj = args[0] if len(args) > 0 else None
temp = 0

if (temp := obj.getp("value")) > 0:
    # ZIL: <SCORE-UPD ...>
    _.zork_thing.score_upd(temp)
    return obj.set_property("value", 0)
