# Generated by extras/zil_import — do not edit by hand
"""Zork-specific root classes — standalone, no dependency on default bootstrap."""
# pylint: disable=undefined-variable

# The system object (_) is created by initialize_dataset.
# Wizard is also created there. Everything else we create from scratch.

# ---------------------------------------------------------------------------
# ZIL SDK object
# Translated verbs call ZIL intrinsics via _.zil_sdk.FUNCTION(args).
# ---------------------------------------------------------------------------
zil_sdk, _created = bootstrap.get_or_create_object("ZIL SDK", unique_name=True)
_.set_property("zil_sdk", zil_sdk)

# ---------------------------------------------------------------------------
# Root classes
# ---------------------------------------------------------------------------
# Accept verb — needed so objects can be placed in rooms/containers.
# PROPDEF defaults from zork1.zil go on the root so every object/actor/exit
# inherits them; the WEIGHT routine reads ``size`` on context.player which
# wouldn't have it otherwise (Zork Actor descends from Zork Root, not Zork
# Thing).
zork_root, _created = bootstrap.get_or_create_object("Zork Root", unique_name=True)
zork_root.add_verb("accept", code="return True")
zork_root.set_property("size", 5)
zork_root.set_property("capacity", 0)
zork_root.set_property("value", 0)
zork_root.set_property("tvalue", 0)
_.set_property("zork_root", zork_root)

zork_thing, _created = bootstrap.get_or_create_object("Zork Thing", unique_name=True, parents=[zork_root])
zork_thing.set_property("takeable", False)
zork_thing.set_property("size", 5)
zork_thing.set_property("value", 0)
zork_thing.set_property("tvalue", 0)
zork_thing.set_property("readable", False)
zork_thing.set_property("flammable", False)
_.set_property("zork_thing", zork_thing)

zork_container, _created = bootstrap.get_or_create_object("Zork Container", unique_name=True, parents=[zork_thing])
zork_container.set_property("takeable", False)
zork_container.set_property("open", False)
zork_container.set_property("size", 10)
zork_container.set_property("capacity", 10)
zork_container.set_property("value", 0)
_.set_property("zork_container", zork_container)

zork_room, _created = bootstrap.get_or_create_object("Zork Room", unique_name=True, parents=[zork_root])
zork_room.set_property("value", 0)
zork_room.set_property("discovered", False)
zork_room.set_property("outdoor", False)
zork_room.set_property("sacred", False)
zork_room.set_property("maze", False)
zork_room.set_property("dark", False)
_.set_property("zork_room", zork_room)

zork_actor, _created = bootstrap.get_or_create_object("Zork Actor", unique_name=True, parents=[zork_root])
_.set_property("zork_actor", zork_actor)
_.set_property("player", zork_actor)  # alias so --on $player verbs attach here

# Wizard must inherit from Zork Actor so the parser can resolve verbs like
# ``take`` (registered ``--on $player``, which aliases to ``zork_actor``)
# when commands are dispatched on the Wizard avatar.
if zork_actor not in wizard.parents.all():
    wizard.parents.add(zork_actor)

zork_exit, _created = bootstrap.get_or_create_object("Zork Exit", unique_name=True, parents=[zork_root])
_.set_property("zork_exit", zork_exit)

_classes = {
    "zork_root": zork_root,
    "zork_thing": zork_thing,
    "zork_container": zork_container,
    "zork_room": zork_room,
    "zork_actor": zork_actor,
    "zork_exit": zork_exit,
}
log.info("Zork classes: %d created/updated", len(_classes))
log.info("ZIL SDK registered as _.zil_sdk")
