# Generated by extras/zil_import — do not edit by hand
"""Zork-specific root classes — standalone, no dependency on default bootstrap."""
# pylint: disable=undefined-variable

# The system object (_) is created by initialize_dataset.
# Wizard is also created there. Everything else we create from scratch.
# ZIL SDK verbs are attached directly to the System Object, $player, and
# $root_class — translated routines call them as ``_.flag(...)``,
# ``context.player.zstate_set(...)``, ``context.player.move(...)``, etc.

# ---------------------------------------------------------------------------
# Root classes
# ---------------------------------------------------------------------------
# Accept verb — needed so objects can be placed in rooms/containers.
# PROPDEF defaults from zork1.zil go on the root so every object/actor/exit
# inherits them; the WEIGHT routine reads ``size`` on context.player which
# wouldn't have it otherwise (Zork Actor descends from Zork Root, not Zork
# Thing).
zork_root, _created = bootstrap.get_or_create_object("Zork Root", unique_name=True)
zork_root.add_verb("accept", code="return True")
zork_root.set_property("size", 5)
zork_root.set_property("capacity", 0)
zork_root.set_property("value", 0)
zork_root.set_property("tvalue", 0)

# ``zork_thing`` is the only substrate handle that lives on the System
# Object — translated routines invoke cross-class verbs via
# ``_.zork_thing.foo()`` (predicates, dispatchers, M-clause splits).  The
# remaining substrate classes are reachable via ``--on "Zork <Class>"`` at
# verb-load time and need no system-property alias.
zork_thing, _created = bootstrap.get_or_create_object("Zork Thing", unique_name=True, parents=[zork_root])
zork_thing.set_property("takeable", False)
zork_thing.set_property("size", 5)
zork_thing.set_property("value", 0)
zork_thing.set_property("tvalue", 0)
zork_thing.set_property("readable", False)
zork_thing.set_property("flammable", False)
_.set_property("zork_thing", zork_thing)

zork_container, _created = bootstrap.get_or_create_object("Zork Container", unique_name=True, parents=[zork_thing])
zork_container.set_property("takeable", False)
zork_container.set_property("open", False)
zork_container.set_property("size", 10)
zork_container.set_property("capacity", 10)
zork_container.set_property("value", 0)

zork_room, _created = bootstrap.get_or_create_object("Zork Room", unique_name=True, parents=[zork_root])
zork_room.set_property("value", 0)
zork_room.set_property("discovered", False)
zork_room.set_property("outdoor", False)
zork_room.set_property("sacred", False)
zork_room.set_property("maze", False)
zork_room.set_property("dark", False)

zork_actor, _created = bootstrap.get_or_create_object("Zork Actor", unique_name=True, parents=[zork_root])

# Wizard must inherit from Zork Actor so the parser can resolve verbs
# registered ``--on "Zork Actor"`` when commands dispatch on the Wizard
# avatar.
if zork_actor not in wizard.parents.all():
    wizard.parents.add(zork_actor)

zork_exit, _created = bootstrap.get_or_create_object("Zork Exit", unique_name=True, parents=[zork_root])

_classes = {
    "zork_root": zork_root,
    "zork_thing": zork_thing,
    "zork_container": zork_container,
    "zork_room": zork_room,
    "zork_actor": zork_actor,
    "zork_exit": zork_exit,
}
log.info("Zork classes: %d created/updated", len(_classes))
