# Generated by extras/zil_import — do not edit by hand
"""Scalar ZIL globals seeded into the wizard's zstate slots."""
# pylint: disable=undefined-variable

wizard.set_property("zstate_base_score", 0)
wizard.set_property("zstate_beach_dig", -1)
wizard.set_property("zstate_buoy_flag", "T")
wizard.set_property("zstate_c_demons", 180)
wizard.set_property("zstate_c_ints", 180)
wizard.set_property("zstate_cage_top", "T")
wizard.set_property("zstate_cyclowrath", 0)
wizard.set_property("zstate_deaths", 0)
wizard.set_property("zstate_fumble_number", 7)
wizard.set_property("zstate_fumble_prob", 8)
wizard.set_property("zstate_here", 0)
wizard.set_property("zstate_hs", 0)
wizard.set_property("zstate_light_shaft", 13)
wizard.set_property("zstate_load_allowed", 100)
wizard.set_property("zstate_load_max", 100)
wizard.set_property("zstate_lucky", 1)
wizard.set_property("zstate_match_count", 6)
wizard.set_property("zstate_moves", 0)
wizard.set_property("zstate_p_dir", 0)
wizard.set_property("zstate_p_direction", 0)
wizard.set_property("zstate_p_getflags", 0)
wizard.set_property("zstate_p_gwimbit", 0)
wizard.set_property("zstate_p_len", 0)
wizard.set_property("zstate_p_matchlen", 0)
wizard.set_property("zstate_p_ncn", 0)
wizard.set_property("zstate_p_not_here", 0)
wizard.set_property("zstate_p_number", 0)
wizard.set_property("zstate_p_oneobj", 0)
wizard.set_property("zstate_p_slocbits", 0)
wizard.set_property("zstate_p_syntax", 0)
wizard.set_property("zstate_p_table", 0)
wizard.set_property(
    "zstate_robber_c_desc",
    "There is a suspicious-looking individual, holding a bag, leaning\nagainst one wall. He is armed with a vicious-looking stiletto.",
)
wizard.set_property(
    "zstate_robber_u_desc", "There is a suspicious-looking individual lying unconscious on the\nground."
)
wizard.set_property("zstate_score", 0)
wizard.set_property("zstate_score_max", 350)
wizard.set_property("zstate_water_level", 0)
wizard.set_property("zstate_winner", 0)

log.info("Zork globals: 37 seeded")
