# Generated by extras/zork_import — do not edit by hand
"""
Zork 1 bootstrap for DjangoMOO.

Load with:
    manage.py moo_init --bootstrap zork1

World statistics (as parsed from dungeon.zil):
    Rooms:   110
    Objects: 122

Based on Infocom Zork 1 source (dungeon.zil / actions.zil).
"""

import importlib.resources
import logging
import secrets
from time import time

from moo import bootstrap
from moo.core import code, lookup

log = logging.getLogger(__name__)
_repo = bootstrap.initialize_dataset("zork1")
wizard = lookup("Wizard")

_namespace = {
    "log": log,
    "secrets": secrets,
    "time": time,
    "bootstrap": bootstrap,
    "lookup": lookup,
    "wizard": wizard,
    "repo": _repo,
}

_pkg = importlib.resources.files("moo.bootstrap") / "zork1"
_scripts = sorted(
    (f for f in _pkg.iterdir() if f.name.endswith(".py") and f.name[0].isdigit()),
    key=lambda f: f.name,
)

with code.ContextManager(wizard, log.info):
    for _script in _scripts:
        exec(compile(_script.read_text(encoding="utf8"), _script.name, "exec"), _namespace)  # pylint: disable=exec-used

bootstrap.load_verbs(_repo, "moo.bootstrap.zork1_verbs", replace=False)
