#!moo verb look-inside --on "kitchen window" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: KITCHEN-WINDOW-F (look-inside branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("You can see ", end="")
if player.here() == lookup("kitchen"):
    print("a clear area leading towards a forest.")
    return
else:
    print("what appears to be a kitchen.")
    return
return passthrough()
