#!moo verb bag_of_coins_f --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

# ZIL routine: BAG-OF-COINS-F

# ZIL: <STUPID-CONTAINER ...>
return _.zork_thing.stupid_container(this, "coins")
