#!moo verb rub --on "mirror (MIRROR-1)" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: MIRROR-MIRROR (rub branch)

player = context.player
parser = context.parser
rm2 = lookup("mirror_room_2")
l1 = 0
l2 = 0
n = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if not player.zstate_get("MIRROR-MUNG"):
    if (parser.get_iobj() if parser.has_iobj() else None) and not (
        parser.get_iobj() if parser.has_iobj() else None
    ) == lookup("hands"):
        print(
            "You feel a faint tingling transmitted through the "
            + (parser.get_iobj() if parser.has_iobj() else None).desc()
            + "."
        )
        return True
    if player.here() == rm2:
        rm2 = lookup("mirror_room_1")
    l1 = player.here().contents.first()
    l2 = rm2.contents.first()
    while True:
        if not l1:
            break
        n = _.next_sibling(l1)
        l1.moveto(rm2)
        l1 = n
    while True:
        if not l2:
            break
        n = _.next_sibling(l2)
        l2.moveto(player.here())
        l2 = n
    _.goto(rm2)
    print("There is a rumble from deep within the earth and the room shakes.")
    return
return passthrough()
