#!moo verb ring --on "brass bell" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: BELL-F (ring branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.here() == lookup("lld_room") and not player.zstate_get("LLD-FLAG"):
    return passthrough()
else:
    print("Ding, dong.")
    return
return passthrough()
