#!moo verb close describe examine get insert look-inside open pick place put shut take what x --on $large_bag --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context, lookup
# ZIL routine: LARGE-BAG-F

if player_verb in ["take", "get", "pick"]:
    if lookup("thief").get_property("description") == _.zil_sdk.zstate_get("ROBBER-U-DESC"):
        return print("Sadly for you, the robber collapsed on top of the bag. Trying to take\nit would wake him.")
    else:
        return print("The bag will be taken over his dead body.")
elif player_verb in ["put", "place", "insert"] and context.parser.get_iobj() == _.get_property("large_bag"):
    return print("It would be a good trick.")
elif player_verb in ["open", "close", "shut"]:
    return print("Getting close enough would be a good trick.")
elif player_verb in ["examine", "x", "describe", "what", "look-inside"]:
    return print("The bag is underneath the thief, so one can't say what, if anything, is\ninside.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
