#!moo verb describe examine get give hear hello hi listen look-inside pick take tell throw toss what x --on $thief --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
from moo.sdk import context, lookup
# ZIL routine: ROBBER-FUNCTION
# params: MODE
# aux: FLG, X

mode = args[0] if len(args) > 0 else None
flg = None
x = None

if player_verb in ["tell"]:
    print("The thief is a strong, silent type.")
    return _.zil_sdk.zstate_set("P-CONT", None)
elif not mode:
    if player_verb in ["hello", "hi"] and _.zil_sdk.getp(lookup("thief"), "description") == _.zil_sdk.zstate_get(
        "ROBBER-U-DESC"
    ):
        return print(
            "The thief, being temporarily incapacitated, is unable to acknowledge\nyour greeting with his usual graciousness."
        )
    elif (
        context.parser.get_dobj() == _.get_property("knife")
        and player_verb in ["throw", "toss"]
        and not _.zil_sdk.flag(lookup("thief"), "hostile")
    ):
        _.zil_sdk.move(context.parser.get_dobj(), context.player.location)
        if random.randint(1, 100) <= 10:
            print("You evidently frightened the robber, though you didn't hit him. He\nflees", end="")
            _.zil_sdk.remove(_.get_property("large_bag"))
            x = None
            if _.get_property("stiletto").location == lookup("thief"):
                _.zil_sdk.remove(_.get_property("stiletto"))
                x = True
            if lookup("thief").contents.first():
                # ZIL: <MOVE-ALL ...>
                _.zork_thing.invoke_verb("move-all", lookup("thief"), context.player.location)
                print(", but the contents of his bag fall on the floor.", end="")
            else:
                print(".", end="")
            _.zil_sdk.move(_.get_property("large_bag"), lookup("thief"))
            if x:
                _.zil_sdk.move(_.get_property("stiletto"), lookup("thief"))
            print()
            return _.zil_sdk.set_flag(lookup("thief"), "invisible", True)
        else:
            print(
                "You missed. The thief makes no attempt to take the knife, though it\nwould be a fine addition to the collection in his bag. He does seem\nangered by your attempt."
            )
            return _.zil_sdk.set_flag(lookup("thief"), "hostile", True)
    elif (
        player_verb in ["throw", "toss", "give"]
        and context.parser.get_dobj()
        and not context.parser.get_dobj() == lookup("thief")
        and context.parser.get_iobj() == lookup("thief")
    ):
        if _.zil_sdk.getp(lookup("thief"), "strength") < 0:
            lookup("thief").set_property("strength", -_.zil_sdk.getp(lookup("thief"), "strength"))
            _.zil_sdk.queue("i-thief", 0)
            # ZIL: <RECOVER-STILETTO ...>
            _.zork_thing.invoke_verb("recover-stiletto")
            lookup("thief").set_property("description", _.zil_sdk.zstate_get("ROBBER-C-DESC"))
            return print("Your proposed victim suddenly recovers consciousness.")
        _.zil_sdk.move(context.parser.get_dobj(), lookup("thief"))
        if _.zil_sdk.getp(context.parser.get_dobj(), "tvalue") > 0:
            _.zil_sdk.zstate_set("THIEF-ENGROSSED", True)
            return print(
                "The thief is taken aback by your unexpected generosity, but accepts\nthe "
                + _.zil_sdk.desc(context.parser.get_dobj())
                + " and stops to admire its beauty."
            )
        else:
            return print(
                "The thief places the "
                + _.zil_sdk.desc(context.parser.get_dobj())
                + " in his bag and thanks\nyou politely."
            )
    elif player_verb in ["take", "get", "pick"]:
        return print("Once you got him, what would you do with him?")
    elif player_verb in ["examine", "x", "describe", "what", "look-inside"]:
        return print(
            "The thief is a slippery character with beady eyes that flit back\nand forth. He carries, along with an unmistakable arrogance, a large bag\nover his shoulder and a vicious stiletto, whose blade is aimed\nmenacingly in your direction. I'd watch out if I were you."
        )
    elif player_verb in ["listen", "hear"]:
        return print("The thief says nothing, as you have not been formally introduced.")
elif mode == _.zil_sdk.zstate_get("F-BUSY?"):
    if _.get_property("stiletto").location == lookup("thief"):
        pass
    elif _.get_property("stiletto").location == lookup("thief").location:
        _.zil_sdk.move(_.get_property("stiletto"), lookup("thief"))
        _.zil_sdk.set_flag(_.get_property("stiletto"), "obvious", True)
        if lookup("thief").location == context.player.location:
            print("The robber, somewhat surprised at this turn of events, nimbly\nretrieves his stiletto.")
        return True
elif mode == _.zil_sdk.zstate_get("F-DEAD"):
    _.zil_sdk.move(_.get_property("stiletto"), context.player.location)
    _.zil_sdk.set_flag(_.get_property("stiletto"), "obvious", False)
    x = _.zork_thing.invoke_verb("deposit-booty", context.player.location)
    if context.player.location == _.get_property("treasure_room"):
        x = context.player.location.contents.first()
        while True:
            if not x:
                print("The chalice is now safe to take.")
                break
            elif not x in (_.get_property("chalice"), lookup("thief"), _.get_property("adventurer")):
                _.zil_sdk.set_flag(x, "invisible", False)
                if not flg:
                    flg = True
                    print("As the thief dies, the power of his magic decreases, and his\ntreasures reappear:")
                print("  A " + _.zil_sdk.desc(x), end="")
                if x.contents.first() and _.zork_thing.invoke_verb("see-inside?", x):
                    print(", with ", end="")
                    # ZIL: <PRINT-CONTENTS ...>
                    _.zork_thing.invoke_verb("print-contents", x)
                print()
            x = _.zil_sdk.next_sibling(x)
    elif x:
        print("His booty remains.")
    return _.zil_sdk.cancel("i-thief")
elif mode == _.zil_sdk.zstate_get("F-FIRST?"):
    if (
        _.zil_sdk.zstate_get("THIEF-HERE")
        and not _.zil_sdk.flag(lookup("thief"), "invisible")
        and random.randint(1, 100) <= 20
    ):
        _.zil_sdk.set_flag(lookup("thief"), "hostile", True)
        _.zil_sdk.zstate_set("P-CONT", None)
        return True
elif mode == _.zil_sdk.zstate_get("F-UNCONSCIOUS"):
    _.zil_sdk.cancel("i-thief")
    _.zil_sdk.set_flag(lookup("thief"), "hostile", False)
    _.zil_sdk.move(_.get_property("stiletto"), context.player.location)
    _.zil_sdk.set_flag(_.get_property("stiletto"), "obvious", False)
    return lookup("thief").set_property("description", _.zil_sdk.zstate_get("ROBBER-U-DESC"))
elif mode == _.zil_sdk.zstate_get("F-CONSCIOUS"):
    if lookup("thief").location == context.player.location:
        _.zil_sdk.set_flag(lookup("thief"), "hostile", True)
        print(
            "The robber revives, briefly feigning continued unconsciousness, and,\nwhen he sees his moment, scrambles away from you."
        )
    _.zil_sdk.queue("i-thief", 0)
    lookup("thief").set_property("description", _.zil_sdk.zstate_get("ROBBER-C-DESC"))
    # ZIL: <RECOVER-STILETTO ...>
    return _.zork_thing.invoke_verb("recover-stiletto")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
