#!moo verb attack --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: V-ATTACK

player = context.player
parser = context.parser

if not parser.get_dobj().flag("actorbit"):
    print("I've known strange people, but fighting a " + parser.get_dobj().desc() + "?")
    return
elif not (parser.get_iobj() if parser.has_iobj() else None) or (
    parser.get_iobj() if parser.has_iobj() else None
) == lookup("hands"):
    print("Trying to attack a " + parser.get_dobj().desc() + " with your bare hands is suicidal.")
    return
elif not (parser.get_iobj() if parser.has_iobj() else None).location == player:
    print("You aren't even holding the " + (parser.get_iobj() if parser.has_iobj() else None).desc() + ".")
    return
elif not (parser.get_iobj() if parser.has_iobj() else None).flag("weapon"):
    print(
        "Trying to attack the "
        + parser.get_dobj().desc()
        + " with a "
        + (parser.get_iobj() if parser.has_iobj() else None).desc()
        + " is suicidal."
    )
    return
else:
    if player.zstate_get("ZORK-NUMBER") == 1:
        # ZIL: <HERO-BLOW ...>
        return _.zork_thing.hero_blow()
    else:
        print("You can't.")
        return
