#!moo verb count --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: V-COUNT

parser = context.parser

if parser.get_dobj() == lookup("blessings"):
    print("Well, for one, you are playing Zork...")
    return
else:
    print("You have lost your mind.")
    return
