#!moo verb eat --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: V-EAT
# aux: EAT?, DRINK?, NOBJ

player = context.player
parser = context.parser
eat_p = 0
drink_p = 0
nobj = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if eat_p := parser.get_dobj().flag("edible"):
    if not parser.get_dobj().location == player and not parser.get_dobj().location.location == player:
        print("You're not holding that.")
    elif the_player_verb == "drink":
        print("How can you drink that?", end="")
    else:
        print("Thank you very much. It really hit the spot.", end="")
        _.remove(parser.get_dobj())
    print()
    return
elif parser.get_dobj().flag("drinkable"):
    drink_p = True
    nobj = parser.get_dobj().location
    if (
        parser.get_dobj().location == lookup("global_objects")
        or lookup("global_water").global_in(player.here())
        or parser.get_dobj() == lookup("pseudo_object")
    ):
        # ZIL: <HIT-SPOT ...>
        return _.zork_thing.hit_spot()
    elif not nobj or not _.zork_thing.is_accessible(nobj):
        print("There isn't any water here.")
        return
    elif _.zork_thing.is_accessible(nobj) and not nobj.location == player:
        print("You have to be holding the " + nobj.desc() + " first.")
        return
    elif not nobj.flag("open"):
        print("You'll have to open the " + nobj.desc() + " first.")
        return
    else:
        # ZIL: <HIT-SPOT ...>
        return _.zork_thing.hit_spot()
elif not eat_p or drink_p:
    print("I don't think that the " + parser.get_dobj().desc() + " would agree with you.")
    return
