#!moo verb examine --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-EXAMINE

parser = context.parser

if parser.get_dobj().getp("text"):
    print(parser.get_dobj().getp("text"))
    return
elif parser.get_dobj().flag("contbit") or parser.get_dobj().flag("is_door"):
    # ZIL: <V-LOOK-INSIDE ...>
    return _.zork_thing.look_inside()
else:
    print("There's nothing special about the " + parser.get_dobj().desc() + ".")
    return
