#!moo verb find --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: V-FIND
# aux: L

player = context.player
parser = context.parser
l = parser.get_dobj().location

if parser.get_dobj() in (lookup("hands"), lookup("lungs")):
    print("Within six feet of your head, assuming you haven't left that\nsomewhere.")
    return
elif parser.get_dobj() == lookup("me"):
    print("You're around here somewhere...")
    return
elif l == lookup("global_objects"):
    print("You find it.")
    return
elif parser.get_dobj().location == player:
    print("You have it.")
    return
elif (
    parser.get_dobj().location == player.here()
    or parser.get_dobj().global_in(player.here())
    or parser.get_dobj() == lookup("pseudo_object")
):
    print("It's right here.")
    return
elif l.flag("actorbit"):
    print("The " + l.desc() + " has it.")
    return
elif l.flag("surfacebit"):
    print("It's on the " + l.desc() + ".")
    return
elif l.flag("contbit"):
    print("It's in the " + l.desc() + ".")
    return
else:
    print("Beats me.")
    return
