#!moo verb give --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-GIVE

parser = context.parser

pre_x = "pre-give"
if _.zork_thing.has_verb(pre_x) and _.zork_thing.invoke_verb(pre_x):
    return
if not (parser.get_iobj() if parser.has_iobj() else None).flag("actorbit"):
    print(
        "You can't give a "
        + parser.get_dobj().desc()
        + " to a "
        + (parser.get_iobj() if parser.has_iobj() else None).desc()
        + "!"
    )
    return
else:
    print("The " + (parser.get_iobj() if parser.has_iobj() else None).desc() + " refuses it politely.")
    return
