#!moo verb knock --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-KNOCK

parser = context.parser

if parser.get_dobj().flag("is_door"):
    print("Nobody's home.")
    return
else:
    print("Why knock on a " + parser.get_dobj().desc() + "?")
    return
