#!moo verb lamp_on --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-LAMP-ON

player = context.player
parser = context.parser

if parser.get_dobj().flag("lit"):
    if parser.get_dobj().flag("onbit"):
        print("It is already on.")
    else:
        parser.get_dobj().set_flag("onbit", True)
        print("The " + parser.get_dobj().desc() + " is now on.")
        if not player.zstate_get("LIT"):
            player.zstate_set("LIT", _.zork_thing.is_lit(player.here()))
            print()
            # ZIL: <V-LOOK ...>
            _.zork_thing.look()
elif parser.get_dobj().flag("flammable"):
    print("If you wish to burn the " + parser.get_dobj().desc() + ", you should say so.")
else:
    print("You can't turn that on.")
return True
