#!moo verb look_inside --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-LOOK-INSIDE

parser = context.parser

if parser.get_dobj().flag("is_door"):
    if parser.get_dobj().flag("open"):
        print("The " + parser.get_dobj().desc() + " is open, but I can't tell what's beyond it.", end="")
    else:
        print("The " + parser.get_dobj().desc() + " is closed.", end="")
    print()
    return
elif parser.get_dobj().flag("contbit"):
    if parser.get_dobj().flag("actorbit"):
        print("There is nothing special to be seen.")
        return
    elif _.zork_thing.is_see_inside(parser.get_dobj()):
        if parser.get_dobj().contents.first() and _.zork_thing.print_cont(parser.get_dobj()):
            return True
        elif _.zork_thing.null_f():
            return True
        else:
            print("The " + parser.get_dobj().desc() + " is empty.")
            return
    else:
        print("The " + parser.get_dobj().desc() + " is closed.")
        return
else:
    print("You can't look inside a " + parser.get_dobj().desc() + ".")
    return
