#!moo verb move --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-MOVE

parser = context.parser

pre_x = "pre-move"
if _.zork_thing.has_verb(pre_x) and _.zork_thing.invoke_verb(pre_x):
    return
if parser.get_dobj().flag("takeable"):
    print("Moving the " + parser.get_dobj().desc() + " reveals nothing.")
    return
else:
    print("You can't move the " + parser.get_dobj().desc() + ".")
    return
