#!moo verb play --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-PLAY

parser = context.parser

if parser.get_dobj().flag("actorbit"):
    print(
        "You become so engrossed in the role of the "
        + parser.get_dobj().desc()
        + " that\nyou kill yourself, just as he might have done!"
    )
    return _.jigs_up("")
else:
    print("That's silly!")
    return
