#!moo verb put --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-PUT

parser = context.parser

pre_x = "pre-put"
if _.zork_thing.has_verb(pre_x) and _.zork_thing.invoke_verb(pre_x):
    return
if (
    (parser.get_iobj() if parser.has_iobj() else None).flag("open")
    or (parser.get_iobj() if parser.has_iobj() else None).flag("openable")
    or (parser.get_iobj() if parser.has_iobj() else None).flag("vehicle")
):
    pass
else:
    print("You can't do that.")
    return True
if not (parser.get_iobj() if parser.has_iobj() else None).flag("open"):
    print("The " + (parser.get_iobj() if parser.has_iobj() else None).desc() + " isn't open.")
    # ZIL: <THIS-IS-IT ...>
    return _.zork_thing.this_is_it((parser.get_iobj() if parser.has_iobj() else None))
elif (parser.get_iobj() if parser.has_iobj() else None) == parser.get_dobj():
    print("How can you do that?")
    return
elif parser.get_dobj().location == (parser.get_iobj() if parser.has_iobj() else None):
    print(
        "The "
        + parser.get_dobj().desc()
        + " is already in the "
        + (parser.get_iobj() if parser.has_iobj() else None).desc()
        + "."
    )
    return
elif _.zork_thing.weight((parser.get_iobj() if parser.has_iobj() else None)) + _.zork_thing.weight(
    parser.get_dobj()
) - (parser.get_iobj() if parser.has_iobj() else None).getp("size") > (
    parser.get_iobj() if parser.has_iobj() else None
).getp("capacity"):
    print("There's no room.")
    return
elif not _.zork_thing.is_held(parser.get_dobj()) and parser.get_dobj().flag("trytakebit"):
    print("You don't have the " + parser.get_dobj().desc() + ".")
    return True
elif not _.zork_thing.is_held(parser.get_dobj()) and not _.zork_thing.itake():
    return True
else:
    parser.get_dobj().moveto((parser.get_iobj() if parser.has_iobj() else None))
    parser.get_dobj().set_flag("touchbit", True)
    # ZIL: <SCORE-OBJ ...>
    _.zork_thing.score_obj(parser.get_dobj())
    print("Done.")
    return
