#!moo verb put_on --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: V-PUT-ON

player = context.player
parser = context.parser

if (parser.get_iobj() if parser.has_iobj() else None) == lookup("ground"):
    _.perform(player.zstate_get("V?DROP"), parser.get_dobj(), None)
    return True
elif (parser.get_iobj() if parser.has_iobj() else None).flag("surfacebit"):
    # ZIL: <V-PUT ...>
    return _.zork_thing.put()
else:
    print("There's no good surface on the " + (parser.get_iobj() if parser.has_iobj() else None).desc() + ".")
    return
