#!moo verb reply --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-REPLY

player = context.player
parser = context.parser

print("It is hardly likely that the " + parser.get_dobj().desc() + " is interested.")
player.zstate_set("P-CONT", None)
player.zstate_set("QUOTE-FLAG", None)
return True
