#!moo verb send --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-SEND

parser = context.parser

if parser.get_dobj().flag("actorbit"):
    print("Why would you send for the " + parser.get_dobj().desc() + "?")
    return
else:
    print("That doesn't make sends.")
    return
