#!moo verb stab --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-STAB
# aux: W

player = context.player
parser = context.parser
w = 0

if w := _.zork_thing.find_weapon(player):
    _.perform(player.zstate_get("V?ATTACK"), parser.get_dobj(), w)
    return True
else:
    print("No doubt you propose to stab the " + parser.get_dobj().desc() + " with your pinky?")
    return
