#!moo verb strike --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-STRIKE

player = context.player
parser = context.parser

if parser.get_dobj().flag("actorbit"):
    print(
        "Since you aren't versed in hand-to-hand combat, you'd better attack the "
        + parser.get_dobj().desc()
        + " with a weapon."
    )
    return
else:
    _.perform(player.zstate_get("V?LAMP-ON"), parser.get_dobj(), None)
    return True
