#!moo verb take --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-TAKE

parser = context.parser

pre_x = "pre-take"
if _.zork_thing.has_verb(pre_x) and _.zork_thing.invoke_verb(pre_x):
    return
if _.zork_thing.itake() == True:
    if parser.get_dobj().flag("wearbit"):
        print("You are now wearing the " + parser.get_dobj().desc() + ".")
        return
    else:
        print("Taken.")
        return
