#!moo verb tell --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-TELL

player = context.player
parser = context.parser

if parser.get_dobj().flag("actorbit"):
    if player:
        player.zstate_set("WINNER", parser.get_dobj())
        return player.zstate_set("HERE", player.location)
    else:
        print(
            "The "
            + parser.get_dobj().desc()
            + " pauses for a moment, perhaps thinking that you should reread\nthe manual."
        )
        return
else:
    print("You can't talk to the " + parser.get_dobj().desc() + "!")
    player.zstate_set("QUOTE-FLAG", None)
    player.zstate_set("P-CONT", None)
    # ZIL: <RFATAL ...>
    return 2
