#!moo verb through --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-THROUGH
# params: OBJ
# aux: M

player = context.player
parser = context.parser
obj = args[0] if len(args) > 0 else None
m = 0

player.zstate_get("#DECL")
if parser.get_dobj().flag("is_door") and (m := _.zork_thing.other_side(parser.get_dobj())):
    _.walk(m)
    return True
elif not obj and parser.get_dobj().flag("vehicle"):
    _.perform(player.zstate_get("V?BOARD"), parser.get_dobj(), None)
    return True
elif obj or not parser.get_dobj().flag("takeable"):
    if player.zstate_get("ZORK-NUMBER") == 2:
        if player.zstate_get("SCOL-ROOM") and obj or parser.get_dobj() == player.zstate_get("CURTAIN"):
            # ZIL: <SCOL-GO ...>
            scol_go(obj)
            return True
        elif (
            player.here() == player.zstate_get("DEPOSITORY")
            and parser.get_dobj() == player.zstate_get("SNWL")
            and player.zstate_get("SCOL-ROOM")
        ):
            # ZIL: <SCOL-GO ...>
            scol_go(obj)
            return True
        elif player.here() == player.zstate_get("SCOL-ACTIVE") and parser.get_dobj() == _.table_get(
            (m := get_wall(player.here())), 1
        ):
            player.zstate_set("SCOL-ROOM", _.table_get(m, 2))
            # SETG of parser-state slot is a no-op in DjangoMOO
            if obj:
                # ZIL: <SCOL-OBJ ...>
                scol_obj(obj, 0, player.zstate_get("DEPOSITORY"))
            else:
                # ZIL: <SCOL-THROUGH ...>
                scol_through(0, player.zstate_get("DEPOSITORY"))
            return True
        elif parser.get_dobj() == player.zstate_get("CURTAIN"):
            print("You can't go more than part way through the curtain.")
            return True
    else:
        # ZIL: <NULL-F ...>
        _.zork_thing.null_f()
    print("You hit your head against the " + parser.get_dobj().desc() + " as you attempt this feat.")
    return
elif parser.get_dobj().location == player:
    print("That would involve quite a contortion!")
    return
else:
    print(_.pick(player.zstate_get("YUKS")))
    return
