#!moo verb tie --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: V-TIE

player = context.player
parser = context.parser

if (parser.get_iobj() if parser.has_iobj() else None) == player:
    print("You can't tie anything to yourself.")
    return
else:
    print("You can't tie the " + parser.get_dobj().desc() + " to that.")
    return
