#!moo verb enterfunc --on $grating_room
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL: MAZE-11-FCN / M-ENTER

_.zil_sdk.set_flag(_.get_property("grate"), "invisible", False)
