#!moo verb maze-11-fcn --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: MAZE-11-FCN
# params: RARG

rarg = args[0] if len(args) > 0 else None

if rarg == "M-ENTER":
    return _.zil_sdk.set_flag(_.get_property("grate"), "invisible", False)
elif rarg == "M-LOOK":
    print("You are in a small room near the maze. There are twisty passages\nin the immediate vicinity.")
    if _.zil_sdk.flag(_.get_property("grate"), "open"):
        print("Above you is an open grating with sunlight pouring in.", end="")
    elif _.zil_sdk.zstate_get("GRUNLOCK"):
        print("Above you is a grating.", end="")
    else:
        print("Above you is a grating locked with a skull-and-crossbones lock.", end="")
    return print()
