#!moo verb break crack destroy mung open smash --on $boarded_window --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: BOARDED-WINDOW-FCN

if player_verb in ["open"]:
    return print("The windows are boarded and can't be opened.")
elif player_verb in ["mung", "destroy", "break", "smash", "crack"]:
    return print("You can't break the windows open.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
