apiVersion: v2
name: django-moo-chart
description: A Helm chart for Kubernetes
dependencies:
  - name: valkey
    version: 0.25.11
    repository: oci://registry-1.docker.io/cloudpirates
    condition: valkey.enabled
  - name: postgres
    version: 0.20.5
    repository: oci://registry-1.docker.io/cloudpirates
    condition: postgres.enabled
type: application
version: 1.14.2
appVersion: 1.14.2
