apiVersion: v2
name: django-moo-chart
description: A Helm chart for Kubernetes
dependencies:
  - name: redis
    version: 25.3.2
    repository: oci://registry-1.docker.io/bitnamicharts
type: application
version: 0.65.7
appVersion: 0.65.7
