#!moo verb break climb-on crack destroy hatch mung open smash throw toss --on $egg --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: EGG-OBJECT

if player_verb in [
    "open",
    "mung",
    "destroy",
    "break",
    "smash",
    "crack",
] and context.parser.get_dobj() == _.get_property("egg"):
    if _.zil_sdk.flag(context.parser.get_dobj(), "open"):
        return print("The egg is already open.")
    elif not context.parser.get_iobj():
        return print("You have neither the tools nor the expertise.")
    elif context.parser.get_iobj() == _.get_property("hands"):
        return print("I doubt you could do that without damaging it.")
    elif (
        _.zil_sdk.flag(context.parser.get_iobj(), "weapon")
        or _.zil_sdk.flag(context.parser.get_iobj(), "toolbit")
        or player_verb in ["mung", "destroy", "break", "smash", "crack"]
    ):
        print(
            "The egg is now open, but the clumsiness of your attempt has seriously\ncompromised its esthetic appeal.",
            end="",
        )
        # ZIL: <BAD-EGG ...>
        _.zork_thing.invoke_verb("bad-egg")
        return print()
    elif _.zil_sdk.flag(context.parser.get_dobj(), "hostile"):
        return print(
            "Not to say that using the " + _.zil_sdk.desc(context.parser.get_iobj()) + " isn't original too..."
        )
    else:
        print("The concept of using a " + _.zil_sdk.desc(context.parser.get_iobj()) + " is certainly original.")
        return _.zil_sdk.set_flag(context.parser.get_dobj(), "hostile", True)
elif player_verb in ["climb-on", "hatch"]:
    print(
        "There is a noticeable crunch from beneath you, and inspection reveals\nthat the egg is lying open, badly damaged.",
        end="",
    )
    # ZIL: <BAD-EGG ...>
    _.zork_thing.invoke_verb("bad-egg")
    return print()
elif player_verb in ["open", "mung", "destroy", "break", "smash", "crack", "throw", "toss"]:
    if player_verb in ["throw", "toss"]:
        _.zil_sdk.move(context.parser.get_dobj(), context.player.location)
    print(
        "Your rather indelicate handling of the egg has caused it some damage,\nalthough you have succeeded in opening it.",
        end="",
    )
    # ZIL: <BAD-EGG ...>
    _.zork_thing.invoke_verb("bad-egg")
    return print()
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
