#!moo verb look --on "Up a Tree" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned
from moo.sdk import context, lookup
# ZIL: TREE-ROOM / M-LOOK

parser = context.parser
path = lookup("path")
rarg = args[0] if len(args) > 0 else "M-LOOK"
f = 0
the_player_verb = (
    args[1]
    if len(args) > 1
    else (parser.words[0].lower() if context.parser is not None and parser.words else verb_name)
)

print(
    "You are about 10 feet above the ground nestled among some large\nbranches. The nearest branch above you is above your reach."
)
if (f := path.contents.first()) and _.next_sibling(f):
    print("On the ground below you can see:  ", end="")
    # ZIL: <PRINT-CONTENTS ...>
    _.zork_thing.print_contents(path)
    print(".")
