#!moo verb climb-down climb-foo climb-up drop leap --on $up_a_tree --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: TREE-ROOM
# params: RARG
# aux: F

rarg = args[0] if len(args) > 0 else None
f = None

if rarg == "M-LOOK":
    print(
        "You are about 10 feet above the ground nestled among some large\nbranches. The nearest branch above you is above your reach."
    )
    if (f := _.get_property("path").contents.first()) and _.zil_sdk.next_sibling(f):
        print("On the ground below you can see:  ", end="")
        # ZIL: <PRINT-CONTENTS ...>
        _.zork_thing.invoke_verb("print-contents", _.get_property("path"))
        return print(".")
elif rarg == "M-BEG":
    if player_verb in ["climb-down"] and context.parser.get_dobj() in (
        _.get_property("tree"),
        _.zil_sdk.zstate_get("ROOMS"),
    ):
        return _.zil_sdk.walk(_.zil_sdk.zstate_get("P?DOWN"))
    elif player_verb in ["climb-up", "climb-foo"] and context.parser.get_dobj() == _.get_property("tree"):
        return _.zil_sdk.walk(_.zil_sdk.zstate_get("P?UP"))
    elif player_verb in ["drop"]:
        if not _.zork_thing.invoke_verb("idrop"):
            return True
        elif context.parser.get_dobj() == _.get_property("nest") and _.get_property("egg").location == _.get_property(
            "nest"
        ):
            print("The nest falls to the ground, and the egg spills out of it, seriously\ndamaged.")
            _.zil_sdk.remove(_.get_property("egg"))
            return _.zil_sdk.move(_.get_property("broken_egg"), _.get_property("path"))
        elif context.parser.get_dobj() == _.get_property("egg"):
            print("The egg falls to the ground and springs open, seriously damaged.", end="")
            _.zil_sdk.move(_.get_property("egg"), _.get_property("path"))
            # ZIL: <BAD-EGG ...>
            _.zork_thing.invoke_verb("bad-egg")
            return print()
        elif not context.parser.get_dobj() in (context.player, _.get_property("tree")):
            _.zil_sdk.move(context.parser.get_dobj(), _.get_property("path"))
            return print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " falls to the ground.")
        elif player_verb in ["leap"]:
            return _.zil_sdk.jigs_up("That was just a bit too far down.")
elif rarg == "M-ENTER":
    return _.zil_sdk.queue("i-forest-room", -1)
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
