#!moo verb look --on $up_a_tree
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL: TREE-ROOM / M-LOOK

print(
    "You are about 10 feet above the ground nestled among some large\nbranches. The nearest branch above you is above your reach."
)
if (f := _.get_property("path").contents.first()) and _.zil_sdk.next_sibling(f):
    print("On the ground below you can see:  ", end="")
    # ZIL: <PRINT-CONTENTS ...>
    _.zork_thing.invoke_verb("print-contents", _.get_property("path"))
    print(".")
