#!moo verb raise --on "carpet" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: RUG-FCN (raise branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("The rug is too heavy to lift", end="")
if player.zstate_get("RUG-MOVED"):
    print(".")
    return
else:
    print(", but in trying to take it you have\nnoticed an irregularity beneath it.")
    return
return passthrough()
