#!moo verb turnfunc --on $tiny_cave
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
from moo.sdk import context
# ZIL: CAVE2-ROOM / M-END

if (
    _.get_property("candles").location == context.player
    and random.randint(1, 100) <= 50
    and _.zil_sdk.flag(_.get_property("candles"), "onbit")
):
    _.zil_sdk.cancel("i-candles")
    _.zil_sdk.set_flag(_.get_property("candles"), "onbit", False)
    print("A gust of wind blows out your candles!")
    if not _.zil_sdk.zstate_set("LIT", _.zork_thing.invoke_verb("lit?", context.player.location)):
        print("It is now completely dark.")
