#!moo verb enter go move through walk --on $stone_barrow --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: STONE-BARROW-FCN
# params: RARG

rarg = args[0] if len(args) > 0 else None

if (
    rarg == "M-BEG"
    and player_verb in ["enter"]
    or player_verb in ["go", "walk", "move"]
    and context.parser.get_dobj() in (_.zil_sdk.zstate_get("P?WEST"), _.zil_sdk.zstate_get("P?IN"))
    or player_verb in ["through"]
    and context.parser.get_dobj() == _.get_property("barrow")
):
    print(
        "Inside the Barrow\n\nAs you enter the barrow, the door closes inexorably behind you. Around\nyou it is dark, but ahead is an enormous cavern, brightly lit. Through\nits center runs a wide stream. Spanning the stream is a small wooden\nfootbridge, and beyond a path leads into a dark tunnel. Above the\nbridge, floating in the air, is a large sign. It reads:  All ye who\nstand before this bridge have completed a great and perilous adventure\nwhich has tested your wit and courage. You have mastered",
        end="",
    )
    if band(_.zil_sdk.table_get(0, 1), 8) == 0:
        print(
            '\nthe first part of the ZORK trilogy. Those who pass over this bridge must be\nprepared to undertake an even greater adventure that will severely test your\nskill and bravery!\n\n\n\nThe ZORK trilogy continues with "ZORK II: The Wizard of Frobozz" and\nis completed in "ZORK III: The Dungeon Master."'
        )
    else:
        print("\nZORK: The Great Underground Empire.\n")
    # ZIL: <FINISH ...>
    return _.zork_thing.invoke_verb("finish")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
