#!moo verb enterfunc --on $cyclops_room
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL: CYCLOPS-ROOM-FCN / M-ENTER

if not _.zil_sdk.zstate_get("CYCLOWRATH") == 0:
    _.zil_sdk.queue("i-cyclops", 0)
