#!moo verb look --on $cyclops_room
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL: CYCLOPS-ROOM-FCN / M-LOOK

print("This room has an exit on the northwest, and a staircase leading up.")
if _.zil_sdk.zstate_get("CYCLOPS-FLAG") and not _.zil_sdk.zstate_get("MAGIC-FLAG"):
    print("The cyclops is sleeping blissfully at the foot of the stairs.")
elif _.zil_sdk.zstate_get("MAGIC-FLAG"):
    print("The east wall, previously solid, now has a cyclops-sized opening in it.")
elif _.zil_sdk.zstate_get("CYCLOWRATH") == 0:
    print(
        "A cyclops, who looks prepared to eat horses (much less mere\nadventurers), blocks the staircase. From his state of health, and\nthe bloodstains on the walls, you gather that he is not very\nfriendly, though he likes people."
    )
elif _.zil_sdk.zstate_get("CYCLOWRATH") > 0:
    print(
        "The cyclops is standing in the corner, eyeing you closely. I don't\nthink he likes you very much. He looks extremely hungry, even for a\ncyclops."
    )
elif _.zil_sdk.zstate_get("CYCLOWRATH") < 0:
    print(
        "The cyclops, having eaten the hot peppers, appears to be gasping.\nHis enflamed tongue protrudes from his man-sized mouth."
    )
