#!moo verb alarm attach attack break burn crack cut describe destroy examine fasten fight get give hear hit kick kill light listen mung odysseus pick slice smash stab take throw tie toss what x --on $cyclops --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context, lookup
# ZIL routine: CYCLOPS-FCN
# aux: COUNT

count = None

count = _.zil_sdk.zstate_get("CYCLOWRATH")
if context.player == lookup("cyclops"):
    if _.zil_sdk.zstate_get("CYCLOPS-FLAG"):
        return print("No use talking to him. He's fast asleep.")
    elif player_verb in ["odysseus"]:
        _.zil_sdk.zstate_set("WINNER", _.get_property("adventurer"))
        _.zil_sdk.perform(_.zil_sdk.zstate_get("V?ODYSSEUS"), None, None)
        return True
    else:
        return print("The cyclops prefers eating to making conversation.")
elif _.zil_sdk.zstate_get("CYCLOPS-FLAG"):
    if player_verb in ["examine", "x", "describe", "what"]:
        return print("The cyclops is sleeping like a baby, albeit a very ugly one.")
    elif player_verb in [
        "alarm",
        "kick",
        "attack",
        "kill",
        "hit",
        "fight",
        "stab",
        "cut",
        "slice",
        "burn",
        "light",
        "mung",
        "destroy",
        "break",
        "smash",
        "crack",
    ]:
        print("The cyclops yawns and stares at the thing that woke him up.")
        _.zil_sdk.zstate_set("CYCLOPS-FLAG", None)
        _.zil_sdk.set_flag(lookup("cyclops"), "hostile", True)
        if count < 0:
            return _.zil_sdk.zstate_set("CYCLOWRATH", -count)
        else:
            return _.zil_sdk.zstate_set("CYCLOWRATH", count)
elif player_verb in ["examine", "x", "describe", "what"]:
    return print("A hungry cyclops is standing at the foot of the stairs.")
elif player_verb in ["give"] and context.parser.get_iobj() == lookup("cyclops"):
    if context.parser.get_dobj() == _.get_property("lunch"):
        if not count < 0:
            _.zil_sdk.remove(_.get_property("lunch"))
            print(
                'The cyclops says "Mmm Mmm. I love hot peppers! But oh, could I use\na drink. Perhaps I could drink the blood of that thing."  From the\ngleam in his eye, it could be surmised that you are "that thing".'
            )
            _.zil_sdk.zstate_set("CYCLOWRATH", min(-1, -count))
        return _.zil_sdk.queue("i-cyclops", -1)
    elif (
        context.parser.get_dobj() == _.get_property("water")
        or context.parser.get_dobj() == _.get_property("bottle")
        and _.get_property("water").location == _.get_property("bottle")
    ):
        if count < 0:
            _.zil_sdk.remove(_.get_property("water"))
            _.zil_sdk.move(_.get_property("bottle"), context.player.location)
            _.zil_sdk.set_flag(_.get_property("bottle"), "open", True)
            _.zil_sdk.set_flag(lookup("cyclops"), "hostile", False)
            print(
                "The cyclops takes the bottle, checks that it's open, and drinks the water.\nA moment later, he lets out a yawn that nearly blows you over, and then\nfalls fast asleep (what did you put in that drink, anyway?)."
            )
            return _.zil_sdk.zstate_set("CYCLOPS-FLAG", True)
        else:
            return print("The cyclops apparently is not thirsty and refuses your generous offer.")
    elif context.parser.get_dobj() == _.get_property("garlic"):
        return print("The cyclops may be hungry, but there is a limit.")
    else:
        return print("The cyclops is not so stupid as to eat THAT!")
elif player_verb in [
    "throw",
    "toss",
    "attack",
    "kill",
    "hit",
    "fight",
    "stab",
    "cut",
    "slice",
    "mung",
    "destroy",
    "break",
    "smash",
    "crack",
]:
    _.zil_sdk.queue("i-cyclops", -1)
    if player_verb in ["mung", "destroy", "break", "smash", "crack"]:
        return print('"Do you think I\'m as stupid as my father was?", he says, dodging.')
    else:
        print("The cyclops shrugs but otherwise ignores your pitiful attempt.")
        if player_verb in ["throw", "toss"]:
            _.zil_sdk.move(context.parser.get_dobj(), context.player.location)
        return True
elif player_verb in ["take", "get", "pick"]:
    return print("The cyclops doesn't take kindly to being grabbed.")
elif player_verb in ["tie", "attach", "fasten"]:
    return print("You cannot tie the cyclops, though he is fit to be tied.")
elif player_verb in ["listen", "hear"]:
    return print("You can hear his stomach rumbling.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
