#!moo verb ring --on $bell --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: BELL-F

if player_verb in ["ring"]:
    if context.player.location == _.zork_thing.invoke_verb("lld-room") and not _.zil_sdk.zstate_get("LLD-FLAG"):
        return False
    else:
        return print("Ding, dong.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
