"""Generate DjangoMOO bootstrap files from ZIL IR.

See :doc:`/reference/zil-importer` for the file plan and
:doc:`/explanation/zil-importer` for the why."""
# pylint: disable=f-string-without-interpolation

from __future__ import annotations

import shutil
import textwrap
from pathlib import Path

from .ir import (
    DIRECTION_ALIASES,
    FLAG_PROPERTIES,
    ROOM_FLAG_PROPERTIES,
    ZilExit,
    ZilObject,
    ZilRoom,
    ZilRoutine,
)
from .translator import ZilTranslator

# Static verb-tree templates copied verbatim into ``output_dir/verbs/`` on
# every regen.  These cover the few pieces that have no ZIL counterpart:
# MooSSH delimiter verbs (PREFIX/SUFFIX), the Object-exit traversal verb
# our movement model needs, and the small ZIL→DjangoMOO impedance shims
# (flag/zstate/table primitives) the translator emits calls to.
_TEMPLATE_VERBS_DIR = Path(__file__).resolve().parent / "verbs"


def _py_str(s: str | None) -> str:
    """Render a string value as a Python string literal."""
    if s is None:
        return "None"
    return repr(s)


def _atom_to_var(atom: str) -> str:
    """Convert a ZIL atom like WEST-OF-HOUSE to a Python variable name."""
    return "_r_" + atom.replace("-", "_").replace("?", "_Q").replace("!", "_B").lower()


def _obj_atom_to_var(atom: str) -> str:
    return "_o_" + atom.replace("-", "_").replace("?", "_Q").replace("!", "_B").lower()


def _routine_to_filename(name: str) -> str:
    return name.replace("-", "_").replace("?", "_p").replace("!", "_b").lower() + ".py"


def _routine_to_verbname(name: str) -> str:
    return name.lower().replace("_", "-")


def _room_slug(atom: str) -> str:
    return atom.lower().replace("-", "_")


def _resolve_object_room(atom: str, objects: dict, rooms: dict) -> str | None:
    """Walk an object's container chain up to its enclosing room atom.

    ZIL objects can be nested (an item inside a container inside a room).
    For verb-file location grouping we only care about the outermost room.
    LOCAL-GLOBALS / GLOBAL-OBJECTS pseudo-containers are not rooms — for
    those we fall back to the first room that lists this object in its
    ``(GLOBAL …)`` declaration, since global objects are conceptually
    "scenery available wherever it shows up first."
    Returns None for orphan objects (those with no resolvable home room).
    """
    seen: set[str] = set()
    cur = atom
    while cur:
        if cur in seen:
            break
        seen.add(cur)
        if cur in rooms:
            return cur
        if cur in objects:
            cur = objects[cur].location
            continue
        break
    # Fall back: scan rooms for first GLOBAL declaration that mentions atom.
    for room_atom, room in rooms.items():
        if atom in (room.globals or []):
            return room_atom
    return None


# ---------------------------------------------------------------------------
# 010_classes.py
# ---------------------------------------------------------------------------

_CLASSES_TEMPLATE = '''\
# Generated by extras/zil_import — do not edit by hand
"""Zork-specific root classes — standalone, no dependency on default bootstrap."""
# pylint: disable=undefined-variable

# The system object (_) is created by initialize_dataset.
# Wizard is also created there. Everything else we create from scratch.

# ---------------------------------------------------------------------------
# ZIL SDK object
# Translated verbs call ZIL intrinsics via _.zil_sdk.FUNCTION(args).
# ---------------------------------------------------------------------------
zil_sdk, _created = bootstrap.get_or_create_object("ZIL SDK", unique_name=True)
_.set_property("zil_sdk", zil_sdk)

# ---------------------------------------------------------------------------
# Root classes
# ---------------------------------------------------------------------------
# Accept verb — needed so objects can be placed in rooms/containers.
# PROPDEF defaults from zork1.zil go on the root so every object/actor/exit
# inherits them; the WEIGHT routine reads ``size`` on context.player which
# wouldn't have it otherwise (Zork Actor descends from Zork Root, not Zork
# Thing).
zork_root, _created = bootstrap.get_or_create_object("Zork Root", unique_name=True)
zork_root.add_verb("accept", code="return True")
zork_root.set_property("size", 5)
zork_root.set_property("capacity", 0)
zork_root.set_property("value", 0)
zork_root.set_property("tvalue", 0)
_.set_property("zork_root", zork_root)

zork_thing, _created = bootstrap.get_or_create_object("Zork Thing", unique_name=True, parents=[zork_root])
zork_thing.set_property("takeable", False)
zork_thing.set_property("size", 5)
zork_thing.set_property("value", 0)
zork_thing.set_property("tvalue", 0)
zork_thing.set_property("readable", False)
zork_thing.set_property("flammable", False)
_.set_property("zork_thing", zork_thing)

zork_container, _created = bootstrap.get_or_create_object("Zork Container", unique_name=True, parents=[zork_thing])
zork_container.set_property("takeable", False)
zork_container.set_property("open", False)
zork_container.set_property("size", 10)
zork_container.set_property("capacity", 10)
zork_container.set_property("value", 0)
_.set_property("zork_container", zork_container)

zork_room, _created = bootstrap.get_or_create_object("Zork Room", unique_name=True, parents=[zork_root])
zork_room.set_property("value", 0)
zork_room.set_property("discovered", False)
zork_room.set_property("outdoor", False)
zork_room.set_property("sacred", False)
zork_room.set_property("maze", False)
zork_room.set_property("dark", False)
_.set_property("zork_room", zork_room)

zork_actor, _created = bootstrap.get_or_create_object("Zork Actor", unique_name=True, parents=[zork_root])
_.set_property("zork_actor", zork_actor)
_.set_property("player", zork_actor)  # alias so --on $player verbs attach here

# Wizard must inherit from Zork Actor so the parser can resolve verbs like
# ``take`` (registered ``--on $player``, which aliases to ``zork_actor``)
# when commands are dispatched on the Wizard avatar.
if zork_actor not in wizard.parents.all():
    wizard.parents.add(zork_actor)

zork_exit, _created = bootstrap.get_or_create_object("Zork Exit", unique_name=True, parents=[zork_root])
_.set_property("zork_exit", zork_exit)

_classes = {
    "zork_root": zork_root,
    "zork_thing": zork_thing,
    "zork_container": zork_container,
    "zork_room": zork_room,
    "zork_actor": zork_actor,
    "zork_exit": zork_exit,
}
log.info("Zork classes: %d created/updated", len(_classes))
log.info("ZIL SDK registered as _.zil_sdk")
'''


# ---------------------------------------------------------------------------
# 020_rooms.py
# ---------------------------------------------------------------------------


def _gen_rooms(rooms: dict[str, ZilRoom]) -> str:
    from collections import Counter

    lines = [
        "# Generated by extras/zil_import — do not edit by hand",
        '"""Zork room objects."""',
        "# pylint: disable=undefined-variable",
        "",
        "_rooms = {}  # keyed by ZIL atom — used by 040_exits.py",
        "",
    ]

    # Some ZIL games re-use the same DESC across multiple rooms (e.g. Zork 1
    # has FOREST-1/2/3 all titled "Forest").  ``unique_name=True`` collapses
    # them to a single Object, which silently breaks navigation.  Append the
    # atom in parens for any DESC that's not unique.
    desc_counts: Counter[str] = Counter(r.desc for r in rooms.values() if r.desc)

    for atom, room in rooms.items():
        var = _atom_to_var(atom)
        base = room.desc or atom.replace("-", " ").title()
        display_name = f"{base} ({atom})" if room.desc and desc_counts[room.desc] > 1 else base
        lines.append(f"# {atom}")
        lines.append(f"{var}, _created = bootstrap.get_or_create_object(")
        lines.append(f"    {repr(display_name)}, unique_name=True,")
        lines.append(f"    parents=[_classes['zork_room']],")
        lines.append(f")")

        if room.ldesc:
            lines.append(f"{var}.set_property('description', {_py_str(room.ldesc)})")
        elif room.fdesc:
            lines.append(f"{var}.set_property('description', {_py_str(room.fdesc)})")

        if room.fdesc and room.ldesc:
            lines.append(f"{var}.set_property('first_description', {_py_str(room.fdesc)})")

        # Room flags
        for flag in room.flags:
            if flag in ROOM_FLAG_PROPERTIES:
                prop, val = ROOM_FLAG_PROPERTIES[flag]
                lines.append(f"{var}.set_property({repr(prop)}, {repr(val)})")

        if room.value:
            lines.append(f"{var}.set_property('value', {room.value})")

        if room.globals:
            lines.append(f"{var}.set_property('global_scenery', {room.globals!r})")

        if room.action:
            lines.append(f"# ACTION: {room.action} — see verbs/{_routine_to_filename(room.action)}")
            action_prop = room.action.lower().replace("-", "_")
            lines.append(f"_.set_property({repr(action_prop)}, {var})")

        atom_prop = atom.lower().replace("-", "_")
        lines.append(f"_.set_property({repr(atom_prop)}, {var})")
        lines.append(f"_rooms[{repr(atom)}] = {var}")
        lines.append("")

    lines.append(f"log.info('Zork rooms: %d', len(_rooms))")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# 030_objects.py
# ---------------------------------------------------------------------------


def _gen_objects(objects: dict[str, ZilObject], rooms: dict[str, ZilRoom]) -> str:
    lines = [
        "# Generated by extras/zil_import — do not edit by hand",
        '"""Zork game objects."""',
        "# pylint: disable=undefined-variable",
        "",
        "_objects = {}  # keyed by ZIL atom",
        "",
    ]
    # ZIL ``IN`` may reference an object declared later in dungeon.zil
    # (LEAFLET → MAILBOX is the canonical case).  Collect deferred location
    # fixups and apply them in a second pass after every object exists.
    deferred_locations: list[tuple[str, str]] = []  # (object_atom, location_atom)

    for atom, obj in objects.items():
        var = _obj_atom_to_var(atom)

        # Pick parent class
        if "ACTORBIT" in obj.flags:
            parent = "_classes['zork_actor']"
        elif "CONTBIT" in obj.flags:
            parent = "_classes['zork_container']"
        else:
            parent = "_classes['zork_thing']"

        # Obvious flag
        obvious = "False" if "NDESCBIT" in obj.flags else "True"

        # Resolve location
        if obj.location and obj.location in rooms:
            loc_expr = f"_rooms[{repr(obj.location)}]"
        elif obj.location and obj.location in objects:
            # Forward reference to another object — start with None and
            # patch after every object has been created.
            loc_expr = "None"
            deferred_locations.append((atom, obj.location))
        elif obj.location:
            # Unknown atom (e.g. a global pseudo-container).  Best-effort
            # lookup through the running ``_objects`` dict.
            loc_expr = f"_objects.get({repr(obj.location)})  # {obj.location}"
        else:
            loc_expr = "None"

        display_name = obj.desc or atom.replace("-", " ").lower()
        lines.append(f"# {atom}")
        lines.append(f"{var}, _created = bootstrap.get_or_create_object(")
        lines.append(f"    {repr(display_name)}, unique_name=False,")
        lines.append(f"    parents=[{parent}],")
        lines.append(f"    location={loc_expr},")
        lines.append(f")")
        lines.append(f"{var}.obvious = {obvious}")
        lines.append(f"{var}.save()")

        desc_text = obj.ldesc or obj.fdesc or obj.desc
        if desc_text:
            lines.append(f"{var}.set_property('description', {_py_str(desc_text)})")

        if obj.fdesc and obj.ldesc:
            lines.append(f"{var}.set_property('first_description', {_py_str(obj.fdesc)})")

        if obj.text:
            lines.append(f"{var}.set_property('text', {_py_str(obj.text)})")

        # Synonyms as aliases
        for syn in obj.synonyms:
            lines.append(f"{var}.add_alias({repr(syn)})")

        # Adjectives stored as property
        if obj.adjectives:
            lines.append(f"{var}.set_property('adjectives', {obj.adjectives!r})")

        # Flag properties
        for flag in obj.flags:
            if flag in FLAG_PROPERTIES:
                prop, val = FLAG_PROPERTIES[flag]
                lines.append(f"{var}.set_property({repr(prop)}, {repr(val)})")

        if obj.capacity:
            lines.append(f"{var}.set_property('capacity', {obj.capacity})")
        if obj.size != 5:
            lines.append(f"{var}.set_property('size', {obj.size})")
        if obj.value:
            lines.append(f"{var}.set_property('value', {obj.value})")
        if obj.tvalue:
            lines.append(f"{var}.set_property('tvalue', {obj.tvalue})")

        if obj.action:
            lines.append(f"# ACTION: {obj.action} — see verbs/{_routine_to_filename(obj.action)}")
            action_prop = obj.action.lower().replace("-", "_")
            lines.append(f"_.set_property({repr(action_prop)}, {var})")

        atom_prop = atom.lower().replace("-", "_")
        lines.append(f"_.set_property({repr(atom_prop)}, {var})")
        lines.append(f"_objects[{repr(atom)}] = {var}")
        lines.append("")

    if deferred_locations:
        lines.append("# Resolve forward IN references that pointed at later-declared objects.")
        for obj_atom, loc_atom in deferred_locations:
            lines.append(f"_objects[{obj_atom!r}].location = _objects[{loc_atom!r}]; _objects[{obj_atom!r}].save()")
        lines.append("")
    lines.append("log.info('Zork objects: %d', len(_objects))")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# 040_exits.py
# ---------------------------------------------------------------------------


def _gen_exits(rooms: dict[str, ZilRoom]) -> str:
    """Emit 040_exits.py.

    Each room's ``exits`` list and each destination's ``entrances`` list
    are accumulated in Python locals first, then written once at the end
    of the room block.  This avoids the prior get/append/set-per-exit
    pattern, which left the lists growing 8x on every sync because each
    sync re-ran the script against a populated database.
    """
    lines = [
        "# Generated by extras/zil_import — do not edit by hand",
        '"""Zork exit objects connecting rooms."""',
        "# pylint: disable=undefined-variable",
        "",
        "_entrances: dict[int, list] = {}  # room pk → entry-Object list (built up below)",
        "",
    ]

    for atom, room in rooms.items():
        if not room.exits:
            continue
        room_var = _atom_to_var(atom)
        lines.append(f"# Exits from {atom}")
        lines.append(f"_room_exits = []")

        for ex in room.exits:
            direction_lower = ex.direction.lower()
            aliases = DIRECTION_ALIASES.get(ex.direction, [direction_lower])
            # Use atom (always unique) rather than DESC — when ZIL games
            # share a DESC across rooms (e.g. FOREST-1/2/3 are all "Forest"),
            # the exit names would collide under unique_name=True and the
            # exits would all attach to whichever Object was created first.
            exit_name = f"{direction_lower} from {atom}"

            lines.append(f"_e, _created = bootstrap.get_or_create_object(")
            lines.append(f"    {repr(exit_name)}, unique_name=True,")
            lines.append(f"    parents=[_classes['zork_exit']],")
            lines.append(f")")
            lines.append(f"_e.set_property('source', {room_var})")

            if ex.per_routine:
                lines.append(f"_e.set_property('dest', None)")
                lines.append(f"_e.set_property('exit_routine', {repr(ex.per_routine)})")
                lines.append(f"# PER: {ex.per_routine} — needs custom verb in verbs/")
            elif ex.dest and ex.dest in rooms:
                dest_var = _atom_to_var(ex.dest)
                lines.append(f"_e.set_property('dest', {dest_var})")
                if ex.condition:
                    lines.append(f"_e.set_property('condition_flag', {repr(ex.condition)})")
                if ex.else_message:
                    lines.append(f"_e.set_property('nogo_msg', {_py_str(ex.else_message)})")
            elif ex.message:
                lines.append(f"_e.set_property('dest', None)")
                lines.append(f"_e.set_property('nogo_msg', {_py_str(ex.message)})")
            elif ex.dest:
                # dest atom not found in rooms dict (e.g. a non-room destination)
                lines.append(f"_e.set_property('dest', None)  # unknown dest: {ex.dest}")
                lines.append(f"_e.set_property('nogo_msg', 'You cannot go that way.')")
            else:
                lines.append(f"_e.set_property('dest', None)")
                lines.append(f"_e.set_property('nogo_msg', 'You cannot go that way.')")

            for alias in aliases:
                lines.append(f"_e.add_alias({repr(alias)})")

            lines.append(f"_e.save()")
            lines.append(f"_room_exits.append(_e)")

            if ex.dest and ex.dest in rooms:
                dest_var = _atom_to_var(ex.dest)
                lines.append(f"_entrances.setdefault({dest_var}.pk, []).append(_e)")

            lines.append("")

        lines.append(f"{room_var}.set_property('exits', _room_exits)")
        lines.append("")

    # Flush all accumulated entrances at end so a single dest collects every
    # incoming exit before the property is written.
    lines.append("for _room_pk, _ents in _entrances.items():")
    lines.append("    _r = _rooms_by_pk.get(_room_pk) if '_rooms_by_pk' in dir() else None")
    lines.append("    if _r is None:")
    lines.append("        from moo.core.models.object import Object as _Object")
    lines.append("        _r = _Object.global_objects.get(pk=_room_pk)")
    lines.append("    _r.set_property('entrances', _ents)")
    lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# zork1/bootstrap.py
# ---------------------------------------------------------------------------


def _gen_bootstrap_init(rooms: dict, objects: dict) -> str:
    return textwrap.dedent(f"""\
        # Generated by extras/zil_import — do not edit by hand
        \"\"\"
        Zork 1 bootstrap for DjangoMOO.

        Load with:
            manage.py moo_init --bootstrap zork1

        World statistics (as parsed from dungeon.zil):
            Rooms:   {len(rooms)}
            Objects: {len(objects)}

        Derived from the Infocom Zork 1 source (dungeon.zil / actions.zil), released
        under the MIT License by Microsoft / Activision Publishing, Inc. in 2025.
        See LICENSE and README.md in this directory for full terms and credits.

        Zork is a registered trademark of Activision Publishing, Inc.
        \"\"\"
        import importlib.resources
        import logging
        import secrets
        from time import time

        from moo import bootstrap
        from moo.core import code, lookup

        log = logging.getLogger(__name__)
        _repo = bootstrap.initialize_dataset("zork1")
        wizard = lookup("Wizard")
        _ = lookup("System Object")

        _namespace = {{
            "log": log,
            "secrets": secrets,
            "time": time,
            "bootstrap": bootstrap,
            "lookup": lookup,
            "wizard": wizard,
            "repo": _repo,
            "_": _,
        }}

        _pkg = importlib.resources.files("moo.bootstrap") / "zork1"
        _scripts = sorted(
            (f for f in _pkg.iterdir() if f.name.endswith(".py") and f.name[0].isdigit()),
            key=lambda f: f.name,
        )

        with code.ContextManager(wizard, log.info, site=wizard.site):
            for _script in _scripts:
                exec(compile(_script.read_text(encoding="utf8"), _script.name, "exec"), _namespace)  # pylint: disable=exec-used
            bootstrap.load_verbs(_repo, "moo.bootstrap.zork1.verbs", replace=True)
    """)


# ---------------------------------------------------------------------------
# Verb translation
# ---------------------------------------------------------------------------


def _gen_verb_translated(
    routine: ZilRoutine,
    object_atoms: set[str] | None = None,
    routine_atoms: set[str] | None = None,
) -> str:
    """Translate a ZilRoutine to a DjangoMOO verb file using ZilTranslator."""
    translator = ZilTranslator(routine, object_atoms=object_atoms, routine_atoms=routine_atoms)
    return translator.translate()


def _gen_m_clause_verb(
    routine: ZilRoutine,
    m_constant: str,
    object_atoms: set[str] | None = None,
    routine_atoms: set[str] | None = None,
) -> str:
    """Generate a single M-* clause as a separate verb file."""
    translator = ZilTranslator(routine, object_atoms=object_atoms, routine_atoms=routine_atoms)
    return translator.translate_m_clause(m_constant)


def _clause_is_empty(code: str) -> bool:
    """True when a translated clause body is whitespace / comments / ``pass`` only."""
    for line in code.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped == "pass":
            continue
        return False
    return True


# ---------------------------------------------------------------------------
# 013_globals.py — scalar GLOBAL declarations from ZIL substrate / dungeon
# ---------------------------------------------------------------------------


def _gen_globals(globals_dict: dict[str, object]) -> str:
    """Generate 013_globals.py to seed zstate slots from ``<GLOBAL …>`` forms.

    Translated routines read these via ``_.zil_sdk.zstate_get('FOO')`` →
    ``context.player.get_property('zstate_foo')``.  Without the seed the
    slot returns None and any arithmetic crashes (e.g. ITAKE's load-allowed
    check).  We set the property directly on the wizard at bootstrap time
    because verb files (and therefore ``zstate_set`` itself) haven't loaded
    yet when this script runs.
    """
    import re as _re

    lines = [
        "# Generated by extras/zil_import — do not edit by hand",
        '"""Scalar ZIL globals seeded into the wizard\'s zstate slots."""',
        "# pylint: disable=undefined-variable",
        "",
    ]
    if globals_dict:
        for name, value in sorted(globals_dict.items()):
            sanitized = _re.sub(r"[^a-z0-9_]", "_", name.lower().replace("-", "_"))
            prop = "zstate_" + sanitized
            lines.append(f"wizard.set_property({prop!r}, {value!r})")
        lines.append("")
        lines.append(f"log.info('Zork globals: {len(globals_dict)} seeded')")
    else:
        lines.append("log.info('Zork globals: none extracted')")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# 015_tables.py — ZIL table data stored as properties on $zil_sdk
# ---------------------------------------------------------------------------


def _gen_tables(tables: dict[str, list]) -> str:
    """Generate 015_tables.py which stores ZIL table data on $zil_sdk."""
    lines = [
        "# Generated by extras/zil_import — do not edit by hand",
        '"""ZIL table data stored as list properties on $zil_sdk."""',
        "# pylint: disable=undefined-variable",
        "",
        "# Tables are stored with zstate_ prefix so pick() can find them.",
        "# Key conversion: UPPER-KEBAB-CASE -> lower_snake_case with zstate_ prefix.",
        "_zil_sdk = _.get_property('zil_sdk')",
        "",
    ]
    if tables:
        for atom, values in tables.items():
            prop_name = "zstate_" + atom.lower().replace("-", "_")
            lines.append(f"_zil_sdk.set_property({repr(prop_name)}, {values!r})")
        lines.append("")
        lines.append(f"log.info('Zork tables: {len(tables)} loaded onto $zil_sdk')")
    else:
        lines.append("# No tables extracted from ZIL source.")
        lines.append("# If ZIL source contains LTABLE/TABLE globals, re-run the converter.")
        lines.append("log.info('Zork tables: none (no tables extracted)')")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def generate_all(
    rooms: dict[str, ZilRoom],
    objects: dict[str, ZilObject],
    routines: dict[str, ZilRoutine],
    output_dir: Path,
    tables: dict[str, list] | None = None,
    globals_dict: dict[str, object] | None = None,
    syntax_dict: dict[str, list[tuple[int, str]]] | None = None,
    synonyms_dict: dict[str, list[str]] | None = None,
) -> None:
    tables = tables or {}
    globals_dict = globals_dict or {}
    syntax_dict = syntax_dict or {}
    synonyms_dict = synonyms_dict or {}
    output_dir.mkdir(parents=True, exist_ok=True)
    verbs_dir = output_dir / "verbs"
    # Wipe the previous regen so stale files (renamed routines, removed
    # objects, or files left behind by earlier flat-directory layouts)
    # don't pile up in the bootstrap output.  The whole tree is rebuilt
    # below from templates + fresh codegen.
    if verbs_dir.exists():
        shutil.rmtree(verbs_dir)
    verbs_dir.mkdir(parents=True, exist_ok=True)
    tests_dir = output_dir / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)

    # Copy the static verb templates (PREFIX/SUFFIX delimiters and the
    # ZIL→DjangoMOO impedance shims under zil_sdk/) into verbs/ before
    # generating ZIL routine files.  None of
    # these depend on ZIL input — they're the small runtime layer the
    # translator emits calls to.
    for src in _TEMPLATE_VERBS_DIR.iterdir():
        dst = verbs_dir / src.name
        if src.is_dir():
            shutil.copytree(src, dst, dirs_exist_ok=True)
        else:
            shutil.copy2(src, dst)

    # Empty package marker — keeps the bootstrap directory importable for
    # test discovery without running database setup at import time.
    (output_dir / "__init__.py").write_text("", encoding="utf-8")

    # Bootstrap entry point — invoked via `moo_init --bootstrap`.
    (output_dir / "bootstrap.py").write_text(_gen_bootstrap_init(rooms, objects), encoding="utf-8")

    # 010_classes.py — includes $zil_sdk creation
    (output_dir / "010_classes.py").write_text(_CLASSES_TEMPLATE, encoding="utf-8")

    # 013_globals.py — scalar GLOBAL declarations (LOAD-ALLOWED, etc.)
    (output_dir / "013_globals.py").write_text(_gen_globals(globals_dict), encoding="utf-8")

    # 015_tables.py — ZIL table data on $zil_sdk
    (output_dir / "015_tables.py").write_text(_gen_tables(tables), encoding="utf-8")

    # 020_rooms.py
    (output_dir / "020_rooms.py").write_text(_gen_rooms(rooms), encoding="utf-8")

    # 030_objects.py
    (output_dir / "030_objects.py").write_text(_gen_objects(objects, rooms), encoding="utf-8")

    # 040_exits.py
    (output_dir / "040_exits.py").write_text(_gen_exits(rooms), encoding="utf-8")

    # Translated verb files
    # Map each routine to the object/room it's an action for
    action_owners: dict[str, tuple[str | None, bool]] = {}  # name → (atom, is_room)
    for atom, room in rooms.items():
        if room.action:
            action_owners[room.action] = (atom, True)
    for atom, obj in objects.items():
        if obj.action:
            action_owners[obj.action] = (atom, False)

    # Routine-name → room-slug grouping so the file tree under verbs/ is
    # browsable.  Room ACTIONs go under their own room dir; object ACTIONs
    # go under whichever room contains the object.  Helper/system routines
    # with no action_owner entry land in verbs/_global/.
    routine_room: dict[str, str] = {}
    for atom, room in rooms.items():
        if room.action:
            routine_room[room.action] = _room_slug(atom)
    for atom, obj in objects.items():
        if obj.action:
            room_atom = _resolve_object_room(atom, objects, rooms)
            if room_atom:
                routine_room[obj.action] = _room_slug(room_atom)

    def _global_bucket(routine_name: str) -> str:
        """Subdivide global helpers so no bucket holds more than a few dozen files.

        Substrate prefixes (V-/PRE-/I-/M-) are well-known.  Everything else
        is bucketed by ZIL naming convention: ``-PSEUDO``/``-FCN``/``-F``
        suffixes mean object handlers, ``-P`` are predicates, plus a few
        keyword-driven buckets for combat, parser, output, and scoring
        helpers.  Anything that doesn't match lands in ``helpers/``.
        """
        lower = routine_name.lower()
        if lower.startswith("v-"):
            return "substrate_verbs"
        if lower.startswith("pre-"):
            return "substrate_pre"
        if lower.startswith("i-"):
            return "daemons"
        if lower.startswith("m-"):
            return "metaverbs"
        if lower.endswith(("-pseudo",)):
            return "pseudo_objects"
        if lower.endswith(("-fcn", "-function", "-f")):
            return "object_handlers"
        if lower.endswith("?"):
            return "predicates"
        if any(k in lower for k in ("print", "tell", "remark", "describe-", "with-tell")):
            return "output"
        if any(k in lower for k in ("fight", "villain", "weapon", "thief", "snarf", "rob", "steal")):
            return "combat"
        if any(k in lower for k in ("clause", "syntax", "buffer-print", "unknown-word", "this-is-it", "this-it")):
            return "parser"
        if any(k in lower for k in ("score", "winning", "finish")):
            return "score"
        return "helpers"

    def _target_dir(routine_name: str) -> Path:
        slug = routine_room.get(routine_name)
        if slug:
            sub = verbs_dir / "rooms" / slug
        else:
            sub = verbs_dir / "_global" / _global_bucket(routine_name)
        sub.mkdir(parents=True, exist_ok=True)
        init = sub / "__init__.py"
        if not init.exists():
            init.write_text("", encoding="utf-8")
        return sub

    translated_names = []
    m_clause_count = 0

    # See :doc:`/reference/zil-importer` for how these are used.
    object_atoms = set(rooms.keys()) | set(objects.keys())
    routine_atoms = set(routines.keys())

    for name, routine in routines.items():
        translator = ZilTranslator(
            routine,
            object_atoms=object_atoms,
            routine_atoms=routine_atoms,
            action_owner=action_owners.get(name),
        )

        target = _target_dir(name)

        if translator.has_m_dispatch():
            # Split M-* clauses into separate verb files
            m_constants = translator.m_constants_found()
            for m_const in m_constants:
                clause_code = translator.translate_m_clause(m_const)
                # Skip clauses whose ZIL body is ``<>`` (no-op event handlers).
                if _clause_is_empty(clause_code):
                    continue
                m_verb = m_const.lower().replace("m-", "")
                filename = f"{_routine_to_filename(name)[:-3]}_{m_verb}.py"
                (target / filename).write_text(clause_code, encoding="utf-8")
                m_clause_count += 1
            # Also write the full routine as a fallback for any unhandled RARG
            full_code = translator.translate()
            (target / _routine_to_filename(name)).write_text(full_code, encoding="utf-8")
        else:
            full_code = translator.translate()
            (target / _routine_to_filename(name)).write_text(full_code, encoding="utf-8")

        translated_names.append(name)

    # SYNTAX-driven player commands.  For every unique verb declared in
    # ``syntax.zil`` (folded with ``synonyms.zil``), emit a tiny ``$player``
    # verb file whose body delegates to the V-routine recorded for that
    # verb.  These files live in ``verbs/syntax/`` to keep them out of the
    # hand-shipped ``verbs/commands/`` directory while we transition.
    syntax_dir = verbs_dir / "syntax"
    syntax_dir.mkdir(exist_ok=True)
    (syntax_dir / "__init__.py").write_text("", encoding="utf-8")
    # Verbs whose substrate V-routine uses Z-machine table-based exits
    # (V-WALK, V-WALK-AROUND).  Our exit model is Object-based, so the
    # WALK family delegates to our zil_sdk.walk helper instead of the
    # substrate routine.
    OBJECT_WALK_OVERRIDES = {"WALK"}

    syntax_count = 0
    for verb, rules in syntax_dict.items():
        names = [verb] + synonyms_dict.get(verb, [])
        names = [n.lower() for n in names if n and not n.startswith("\\")]
        if not names or not rules:
            continue
        # WALK family: delegate to the generic exit-Object traversal helper
        # (``$zil_sdk.walk``) rather than the substrate's table-based
        # V-WALK, which assumes Z-machine memory exits we don't have.
        if verb in OBJECT_WALK_OVERRIDES:
            body = textwrap.dedent(f"""\
                #!moo verb {" ".join(names)} --on $player --dspec either
                # Generated by extras/zil_import — do not edit by hand
                # pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
                \"\"\"Player command for {verb}: traverse an exit Object.\"\"\"

                from moo.sdk import context

                if context.parser.has_dobj_str():
                    _.zil_sdk.walk(context.parser.get_dobj_str())
                else:
                    print("Where do you want to go?")
            """)
            fname = verb.lower() + ".py"
            (syntax_dir / fname).write_text(body, encoding="utf-8")
            syntax_count += 1
            continue
        # Pick the no-OBJECT and the single-OBJECT variants.  Two-OBJECT
        # variants (e.g. ``READ OBJECT OBJECT = V-READ-PAGE``) are skipped
        # because the dobj/iobj split would need extra grammar parsing the
        # SYNTAX codegen doesn't do; the player command falls back to the
        # one-OBJECT V-routine when only a single dobj is typed.
        no_obj = next((v for n, v in rules if n == 0), None)
        obj_variant = next((v for n, v in rules if n == 1), None)
        if obj_variant is None:
            # Fall back to whichever variant is closest to one-object so
            # commands like ``put`` (only ever multi-object in syntax) still
            # have something to delegate to.
            obj_variant = next((v for n, v in sorted(rules, key=lambda r: r[0]) if n >= 1), None)
        # Build the body.  When both variants exist, branch on whether the
        # player typed a dobj.  Otherwise just delegate to whichever rule
        # we have.
        if no_obj and obj_variant and no_obj != obj_variant:
            body = textwrap.dedent(f"""\
                #!moo verb {" ".join(names)} --on $player --dspec either
                # Generated by extras/zil_import — do not edit by hand
                # pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
                \"\"\"Player command for {verb}: dispatch by object slot.\"\"\"

                from moo.sdk import context

                if context.parser.has_dobj_str():
                    _.zork_thing.invoke_verb({obj_variant.lower()!r})
                else:
                    _.zork_thing.invoke_verb({no_obj.lower()!r})
            """)
        else:
            v_routine = obj_variant or no_obj
            body = textwrap.dedent(f"""\
                #!moo verb {" ".join(names)} --on $player --dspec either
                # Generated by extras/zil_import — do not edit by hand
                # pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
                \"\"\"Player command for {verb}: delegate to {v_routine}.\"\"\"

                _.zork_thing.invoke_verb({v_routine.lower()!r})
            """)
        fname = verb.lower().replace("?", "_p").replace("!", "_b") + ".py"
        (syntax_dir / fname).write_text(body, encoding="utf-8")
        syntax_count += 1
    print(f"  syntax commands: {syntax_count}")

    # verbs_dir __init__.py
    (verbs_dir / "__init__.py").write_text("# Zork 1 translated verb files\n", encoding="utf-8")

    # tests __init__.py
    (tests_dir / "__init__.py").write_text("", encoding="utf-8")

    _write_tests(rooms, objects, routines, translated_names, tests_dir)

    # Run ruff format on every generated file so the committed output
    # matches the project's formatting rules without relying on a
    # separate auto-fix pass.  Failures are non-fatal — the worst case is
    # the pre-commit hook fixing them later.
    import subprocess

    try:
        subprocess.run(
            ["ruff", "format", "--quiet", str(output_dir)],
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except FileNotFoundError:
        pass

    print(
        f"Generated {len(rooms)} rooms, {len(objects)} objects, {len(routines)} routines "
        f"({m_clause_count} M-* clause splits)"
    )
    print(f"Bootstrap: {output_dir}/")
    print(f"Verbs:     {verbs_dir}/")


# ---------------------------------------------------------------------------
# Test generation
# ---------------------------------------------------------------------------


def _write_tests(
    rooms: dict[str, ZilRoom],
    objects: dict[str, ZilObject],
    routines: dict[str, ZilRoutine],
    stub_names: list[str],
    tests_dir: Path,
) -> None:
    _write_conftest(rooms, tests_dir)
    _write_test_rooms(rooms, tests_dir)
    _write_test_objects(objects, rooms, tests_dir)
    _write_test_exits(rooms, tests_dir)
    _write_test_verbs(stub_names, tests_dir)


def _write_conftest(rooms: dict[str, ZilRoom], tests_dir: Path) -> None:
    # Find a starting room (first outdoor room, or first room)
    start_atom = next(
        (a for a, r in rooms.items() if "ONBIT" in r.flags and "RLANDBIT" in r.flags),
        next(iter(rooms), None),
    )
    start_room = rooms[start_atom] if start_atom else None
    start_name = start_room.desc if start_room else "Unknown"

    content = textwrap.dedent(f"""\
        # Generated by extras/zil_import
        import pytest
        from moo.bootstrap import initialize_dataset
        from moo.core import code
        from moo.sdk import lookup


        @pytest.fixture
        def zork_world(t_init, t_wizard):
            \"\"\"Bootstrap the zork1 dataset for the duration of one test.

            Uses the project-wide ``t_init`` fixture parametrized for ``zork1``
            so each test gets a freshly seeded world that lives only as long
            as the surrounding ``django_db`` transaction.
            \"\"\"
            return t_init


        @pytest.fixture
        def t_start_room(zork_world, t_wizard):
            room = lookup({repr(start_name)})
            t_wizard.location = room
            t_wizard.save()
            t_wizard.refresh_from_db()
            return room
    """)
    (tests_dir / "conftest.py").write_text(content, encoding="utf-8")


def _write_test_rooms(rooms: dict[str, ZilRoom], tests_dir: Path) -> None:
    # Pick a handful of representative rooms to test
    samples = list(rooms.values())[:5]

    cases = []
    for room in samples:
        name = room.desc or room.atom
        exit_dirs = [e.direction.lower() for e in room.exits if e.dest][:2]
        blocked = [e for e in room.exits if e.message and not e.dest]
        outdoor = "RLANDBIT" in room.flags
        lit = "ONBIT" in room.flags

        cases.append(f"""
class Test{room.atom.replace("-", "_").title().replace("_", "")}:
    def test_exists(self, zork_world):
        room = lookup({repr(name)})
        assert room is not None

    def test_has_description(self, zork_world):
        from moo.sdk import NoSuchPropertyError

        room = lookup({repr(name)})
        try:
            desc = room.get_property("description")
        except NoSuchPropertyError:
            desc = None
        assert desc or room.name""")

        if exit_dirs:
            cases.append(f"""
    def test_has_exits(self, zork_world):
        room = lookup({repr(name)})
        exits = room.get_property("exits")
        aliases = {{a for e in exits for a in e.aliases.values_list("alias", flat=True)}}
        assert {repr(exit_dirs[0])} in aliases""")

        if blocked:
            cases.append(f"""
    def test_blocked_exit_{blocked[0].direction.lower()}(self, zork_world):
        room = lookup({repr(name)})
        exits = room.get_property("exits")
        blocked = [e for e in exits if e.get_property("dest") is None and e.get_property("nogo_msg")]
        assert blocked""")

        if outdoor:
            cases.append(f"""
    def test_outdoor(self, zork_world):
        room = lookup({repr(name)})
        assert room.get_property("outdoor") is True""")

        if lit:
            cases.append(f"""
    def test_lit(self, zork_world):
        room = lookup({repr(name)})
        assert room.get_property("dark") is False""")

    content = (
        textwrap.dedent("""\
        # Generated by extras/zil_import
        import pytest
        from moo.sdk import lookup

        # Each test gets a fresh ``zork1`` bootstrap inside a transactional
        # DB; ``t_init`` is parametrized indirectly so the bootstrap module
        # name reaches the project-wide fixture.
        pytestmark = [
            pytest.mark.django_db(transaction=True, reset_sequences=True),
            pytest.mark.parametrize("t_init", ["zork1"], indirect=True),
        ]
    """)
        + "\n".join(cases)
        + "\n"
    )
    (tests_dir / "test_rooms.py").write_text(content, encoding="utf-8")


def _write_test_objects(
    objects: dict[str, ZilObject],
    rooms: dict[str, ZilRoom],
    tests_dir: Path,
) -> None:
    # Skip objects whose lookup key clashes with a room or another object —
    # ``lookup()`` is case-insensitive over names + aliases, so a clash makes
    # the generated test ambiguous.
    room_names = {(r.desc or r.atom).lower() for r in rooms.values()}
    key_counts: dict[str, int] = {}
    for o in objects.values():
        for key in {(o.desc or o.atom.lower()).lower(), *(s.lower() for s in o.synonyms)}:
            key_counts[key] = key_counts.get(key, 0) + 1

    def _selectable(o: ZilObject) -> bool:
        key = (o.desc or o.atom.lower()).lower()
        return key not in room_names and key_counts.get(key, 0) == 1

    takeables = [o for o in objects.values() if "TAKEBIT" in o.flags and _selectable(o)][:4]
    containers = [o for o in objects.values() if "CONTBIT" in o.flags and _selectable(o)][:3]
    readable = [o for o in objects.values() if "READBIT" in o.flags and _selectable(o)][:2]

    lines = [
        "# Generated by extras/zil_import",
        "import pytest",
        "from moo.sdk import lookup",
        "",
        "pytestmark = [",
        "    pytest.mark.django_db(transaction=True, reset_sequences=True),",
        '    pytest.mark.parametrize("t_init", ["zork1"], indirect=True),',
        "]",
        "",
        "",
    ]

    if takeables:
        lines.append("class TestTakeables:")
        for obj in takeables:
            name = obj.desc or obj.atom.lower()
            lines.append(f"    def test_{obj.atom.lower().replace('-', '_')}_takeable(self, zork_world):")
            lines.append(f"        o = lookup({repr(name)})")
            lines.append(f"        assert o is not None")
            lines.append(f"        assert o.get_property('takeable') is True")
            lines.append("")

    if containers:
        lines.append("class TestContainers:")
        for obj in containers:
            name = obj.desc or obj.atom.lower()
            lines.append(f"    def test_{obj.atom.lower().replace('-', '_')}_is_container(self, zork_world):")
            lines.append(f"        o = lookup({repr(name)})")
            lines.append(f"        assert o is not None")
            lines.append(f"        parents = [p.name for p in o.parents.all()]")
            lines.append(f"        assert any('Container' in p or 'container' in p for p in parents)")
            if obj.capacity:
                lines.append(f"        assert o.get_property('capacity') == {obj.capacity}")
            lines.append("")

    if readable:
        lines.append("class TestReadable:")
        for obj in readable:
            name = obj.desc or obj.atom.lower()
            lines.append(f"    def test_{obj.atom.lower().replace('-', '_')}_readable(self, zork_world):")
            lines.append(f"        o = lookup({repr(name)})")
            lines.append(f"        assert o is not None")
            lines.append(f"        assert o.get_property('readable') is True")
            lines.append("")

    (tests_dir / "test_objects.py").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_test_exits(rooms: dict[str, ZilRoom], tests_dir: Path) -> None:
    # Find a room with a simple unconditional exit to test traversal
    traversal_pair = None
    for room in rooms.values():
        for ex in room.exits:
            if ex.dest and ex.dest in rooms and not ex.condition and not ex.per_routine:
                dest_room = rooms[ex.dest]
                traversal_pair = (room, ex, dest_room)
                break
        if traversal_pair:
            break

    blocked_ex = None
    blocked_room = None
    for room in rooms.values():
        for ex in room.exits:
            if ex.message and not ex.dest:
                blocked_ex = ex
                blocked_room = room
                break
        if blocked_ex:
            break

    lines = [
        "# Generated by extras/zil_import",
        "import pytest",
        "from moo.sdk import lookup",
        "",
        "pytestmark = [",
        "    pytest.mark.django_db(transaction=True, reset_sequences=True),",
        '    pytest.mark.parametrize("t_init", ["zork1"], indirect=True),',
        "]",
        "",
        "",
    ]

    if traversal_pair:
        src_room, ex, dst_room = traversal_pair
        src_name = src_room.desc or src_room.atom
        dst_name = dst_room.desc or dst_room.atom
        direction = ex.direction.lower()
        # Structural assertion only — full traversal goes through the
        # default-dataset's parse/dispatch pipeline, which the zork1
        # bootstrap doesn't pull in. We verify the exit object exists
        # and points at the right destination.
        lines += [
            f"def test_exit_traversal_{direction}(zork_world):",
            f"    room = lookup({repr(src_name)})",
            f"    exits = room.get_property('exits')",
            f"    matches = [",
            f"        e for e in exits",
            f"        if e.aliases.filter(alias={repr(direction)}).exists()",
            f"    ]",
            f"    assert matches, 'no {direction} exit on {src_name}'",
            f"    dest = matches[0].get_property('dest')",
            f"    assert dest is not None",
            f"    assert dest.name == {repr(dst_name)}",
            "",
            "",
        ]

    if blocked_ex and blocked_room:
        src_name = blocked_room.desc or blocked_room.atom
        direction = blocked_ex.direction.lower()
        # Same caveat as above — structural assertion only.
        lines += [
            f"def test_blocked_exit_{direction}(zork_world):",
            f"    room = lookup({repr(src_name)})",
            f"    exits = room.get_property('exits')",
            f"    matches = [",
            f"        e for e in exits",
            f"        if e.aliases.filter(alias={repr(direction)}).exists()",
            f"    ]",
            f"    assert matches, 'no {direction} exit on {src_name}'",
            f"    blocked = matches[0]",
            f"    assert blocked.get_property('dest') is None",
            f"    assert blocked.get_property('nogo_msg')",
            "",
        ]

    (tests_dir / "test_exits.py").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_test_verbs(verb_names: list[str], tests_dir: Path) -> None:
    if not verb_names:
        return

    param_list = repr(verb_names[:20])  # limit parametrize list
    content = textwrap.dedent(f"""\
        # Generated by extras/zil_import
        import pytest
        from moo.sdk import lookup


        @pytest.mark.django_db(transaction=True, reset_sequences=True)
        @pytest.mark.parametrize("t_init", ["zork1"], indirect=True)
        @pytest.mark.parametrize("routine_name", {param_list})
        def test_translated_verb_loaded(t_init, routine_name):
            \"\"\"Each translated ACTION routine should be loadable (no syntax errors).\"\"\"
            zork_room = lookup("Zork Room")
            assert zork_room is not None
            # Verb files are loaded by bootstrap.load_verbs — if they loaded, no SyntaxError.
            # Full dispatch testing requires individual test cases per verb.
    """)
    (tests_dir / "test_translated_verbs.py").write_text(content, encoding="utf-8")
