#!moo verb i_fight --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

import random
from moo.sdk import context, lookup
# ZIL routine: I-FIGHT
# aux: FIGHT?, LEN, CNT, OO, O, P

player = context.player
thief = lookup("thief")
fight_p = 0
len_v = _.table_get(player.zstate_get("VILLAINS"), 0)
cnt = 0
oo = 0
o = 0
p = 0

if player.zstate_get("DEAD"):
    return False
cnt = 0
while True:
    cnt = cnt + 1
    if cnt == len_v:
        break
    oo = _.table_get(player.zstate_get("VILLAINS"), cnt)
    if (o := _.table_get(oo, player.zstate_get("V-VILLAIN"))).location == player.here() and not o.flag("invisible"):
        if o == thief and player.zstate_get("THIEF-ENGROSSED"):
            player.zstate_set("THIEF-ENGROSSED", None)
        elif o.getp("strength") < 0:
            p = _.table_get(oo, player.zstate_get("V-PROB"))
            if not p == 0 and random.randint(1, 100) <= p:
                # ZIL: <PUT ...>
                _.table_put(oo, player.zstate_get("V-PROB"), 0)
                # ZIL: <AWAKEN ...>
                _.zork_thing.awaken(o)
            else:
                # ZIL: <PUT ...>
                _.table_put(oo, player.zstate_get("V-PROB"), p + 25)
        elif o.flag("hostile") or apply(o.getp("action"), player.zstate_get("F-FIRST?")):
            fight_p = True
    else:
        if o.flag("hostile"):
            # ZIL: <APPLY ...>
            apply(o.getp("action"), player.zstate_get("F-BUSY?"))
        if o == thief:
            player.zstate_set("THIEF-ENGROSSED", None)
        player.set_flag("staggered", False)
        o.set_flag("staggered", False)
        o.set_flag("hostile", False)
        # ZIL: <AWAKEN ...>
        _.zork_thing.awaken(o)
if not fight_p:
    return False
# ZIL: <DO-FIGHT ...>
return _.zork_thing.do_fight(len_v)
