#!moo verb i_forest_room --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

import random
# ZIL routine: I-FOREST-ROOM

if not _.zork_thing.is_forest_room():
    _.cancel("i-forest-room")
    return False
elif random.randint(1, 100) <= 15:
    print("You hear in the distance the chirping of a song bird.")
    return
