#!moo verb i_lantern --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: I-LANTERN
# aux: TICK, TBL

player = context.player
tick = 0
tbl = value(player.zstate_get("LAMP-TABLE"))

_.queue("i-lantern", (tick := _.table_get(tbl, 0)))
# ZIL: <LIGHT-INT ...>
_.zork_thing.light_int(lookup("lamp"), tbl, tick)
if not tick == 0:
    return player.zstate_set("LAMP-TABLE", rest(tbl, 4))
