#!moo verb i_match --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: I-MATCH

player = context.player
match = lookup("match")

print("The match has gone out.")
match.set_flag("flamebit", False)
match.set_flag("onbit", False)
player.zstate_set("LIT", _.zork_thing.is_lit(player.here()))
return True
