#!moo verb i_thief --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: I-THIEF
# aux: RM, HERE?, ONCE, FLG

player = context.player
thief = lookup("thief")
treasure_room = lookup("treasure_room")
rm = thief.location
here_p = 0
once = 0
flg = 0

if here_p := not thief.flag("invisible"):
    rm = thief.location
if rm == treasure_room and not rm == player.here():
    if here_p:
        # ZIL: <HACK-TREASURES ...>
        _.zork_thing.hack_treasures()
        here_p = None
    # ZIL: <DEPOSIT-BOOTY ...>
    _.zork_thing.deposit_booty(treasure_room)
elif rm == player.here() and not rm.flag("onbit") and not lookup("troll").location == player.here():
    if _.zork_thing.thief_vs_adventurer(here_p):
        return True
    if thief.flag("invisible"):
        here_p = None
else:
    if thief.location == rm and not thief.flag("invisible"):
        thief.set_flag("invisible", True)
        here_p = None
    if rm.flag("touchbit"):
        # ZIL: <ROB ...>
        _.zork_thing.rob(rm, thief, 75)
        flg = (
            _.zork_thing.rob_maze(rm) if rm.flag("maze") and player.here().flag("maze") else _.zork_thing.steal_junk(rm)
        )
if (once := not once) and not here_p:
    # ZIL: <RECOVER-STILETTO ...>
    _.zork_thing.recover_stiletto()
    while True:
        if rm and (rm := _.next_sibling(rm)):
            pass
        else:
            rm = player.zstate_get("ROOMS").contents.first()
        if not rm.flag("sacred") and rm.flag("outdoor"):
            thief.moveto(rm)
            thief.set_flag("hostile", False)
            thief.set_flag("invisible", True)
            player.zstate_set("THIEF-HERE", None)
            break
    # ZIL: <AGAIN ...>
    lookup("again")
if not rm == treasure_room:
    # ZIL: <DROP-JUNK ...>
    _.zork_thing.drop_junk(rm)
return flg
