#!moo verb burn describe examine find light open through walk-around what where x --on $white_house --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: WHITE-HOUSE-F

if context.player.location in (_.get_property("kitchen"), _.get_property("living_room"), _.get_property("attic")):
    if player_verb in ["find", "where"]:
        return print("Why not find your brains?")
    elif player_verb in ["walk-around"]:
        # ZIL: <GO-NEXT ...>
        _.zork_thing.invoke_verb("go-next", _.zil_sdk.zstate_get("IN-HOUSE-AROUND"))
        return True
elif not context.player.location in (
    _.get_property("east_of_house"),
    _.get_property("west_of_house"),
) or context.player.location in (_.get_property("north_of_house"), _.get_property("south_of_house")):
    if player_verb in ["find", "where"]:
        if context.player.location == _.get_property("clearing"):
            return print("It seems to be to the west.")
        else:
            return print("It was here just a minute ago....")
    else:
        return print("You're not at the house.")
elif player_verb in ["find", "where"]:
    return print("It's right here! Are you blind or something?")
elif player_verb in ["walk-around"]:
    # ZIL: <GO-NEXT ...>
    _.zork_thing.invoke_verb("go-next", _.zil_sdk.zstate_get("HOUSE-AROUND"))
    return True
elif player_verb in ["examine", "x", "describe", "what"]:
    return print(
        "The house is a beautiful colonial house which is painted white.\nIt is clear that the owners must have been extremely wealthy."
    )
elif player_verb in ["through", "open"]:
    if context.player.location == _.get_property("east_of_house"):
        if _.zil_sdk.flag(_.get_property("kitchen_window"), "open"):
            return _.zil_sdk.goto(_.get_property("kitchen"))
        else:
            print("The window is closed.")
            # ZIL: <THIS-IS-IT ...>
            return _.zork_thing.invoke_verb("this-is-it", _.get_property("kitchen_window"))
    else:
        return print("I can't see how to get in from here.")
elif player_verb in ["burn", "light"]:
    return print("You must be joking.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
