#!moo verb attack break crack cut destroy fight get hit kill mung pick slice smash stab take tell --on $bat --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: BAT-F

if player_verb in ["tell"]:
    # ZIL: <FWEEP ...>
    _.zork_thing.invoke_verb("fweep", 6)
    return _.zil_sdk.zstate_set("P-CONT", None)
elif player_verb in [
    "take",
    "get",
    "pick",
    "attack",
    "kill",
    "hit",
    "fight",
    "stab",
    "cut",
    "slice",
    "mung",
    "destroy",
    "break",
    "smash",
    "crack",
]:
    if _.get_property("garlic").location in (context.player, context.player.location):
        return print("You can't reach him; he's on the ceiling.")
    else:
        # ZIL: <FLY-ME ...>
        return _.zork_thing.invoke_verb("fly-me")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
