#!moo verb look --on $bat_room
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL: BATS-ROOM / M-LOOK

print("You are in a small room which has doors only to the east and south.")
