#!moo verb bats-room --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: BATS-ROOM
# params: RARG

rarg = args[0] if len(args) > 0 else None

if rarg == "M-LOOK":
    return print("You are in a small room which has doors only to the east and south.")
elif rarg == "M-ENTER" and not _.zil_sdk.zstate_get("DEAD"):
    if not _.get_property("garlic").location in (context.player, context.player.location):
        # ZIL: <V-LOOK ...>
        _.zork_thing.invoke_verb("v-look")
        print()
        # ZIL: <FLY-ME ...>
        return _.zork_thing.invoke_verb("fly-me")
