#!moo verb examine x describe what --on "white house" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: WHITE-HOUSE-F (examine branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print(
    "The house is a beautiful colonial house which is painted white.\nIt is clear that the owners must have been extremely wealthy."
)
return
