#!moo verb climb-on get look-under move pick press push raise take --on $rug --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: RUG-FCN

if player_verb in ["raise"]:
    print("The rug is too heavy to lift", end="")
    if _.zil_sdk.zstate_get("RUG-MOVED"):
        return print(".")
    else:
        return print(", but in trying to take it you have\nnoticed an irregularity beneath it.")
elif player_verb in ["move", "push", "press", "move"]:
    if _.zil_sdk.zstate_get("RUG-MOVED"):
        return print("Having moved the carpet previously, you find it impossible to move\nit again.")
    else:
        print(
            "With a great effort, the rug is moved to one side of the room, revealing\nthe dusty cover of a closed trap door."
        )
        _.zil_sdk.set_flag(_.get_property("trap_door"), "invisible", False)
        # ZIL: <THIS-IS-IT ...>
        _.zork_thing.invoke_verb("this-is-it", _.get_property("trap_door"))
        return _.zil_sdk.zstate_set("RUG-MOVED", True)
elif player_verb in ["take", "get", "pick"]:
    return print("The rug is extremely heavy and cannot be carried.")
elif (
    player_verb in ["look-under"]
    and not _.zil_sdk.zstate_get("RUG-MOVED")
    and not _.zil_sdk.flag(_.get_property("trap_door"), "open")
):
    return print(
        "Underneath the rug is a closed trap door. As you drop the corner of the\nrug, the trap door is once again concealed from view."
    )
elif player_verb in ["climb-on"]:
    if not _.zil_sdk.zstate_get("RUG-MOVED") and not _.zil_sdk.flag(_.get_property("trap_door"), "open"):
        return print(
            "As you sit, you notice an irregularity underneath it. Rather than be\nuncomfortable, you stand up again."
        )
    else:
        return print("I suppose you think it's a magic carpet?")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
