#!moo verb describe examine get pick take what x --on $sword --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: SWORD-FCN
# aux: G

g = None

if player_verb in ["take", "get", "pick"] and context.player == _.get_property("adventurer"):
    return _.zil_sdk.queue("i-sword", -1)
elif player_verb in ["examine", "x", "describe", "what"]:
    if (g := _.get_property("sword").get_property("tvalue")) == 1:
        return print("Your sword is glowing with a faint blue glow.")
    elif g == 2:
        return print("Your sword is glowing very brightly.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
