#!moo verb close look-under open raise shut unlock --on $trap_door --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: TRAP-DOOR-FCN

if player_verb in ["raise"]:
    _.zil_sdk.perform(_.zil_sdk.zstate_get("V?OPEN"), _.get_property("trap_door"), None)
    return True
elif player_verb in ["open", "close", "shut"] and context.player.location == _.get_property("living_room"):
    # ZIL: <OPEN-CLOSE ...>
    return _.zork_thing.invoke_verb(
        "open-close",
        context.parser.get_dobj(),
        "The door reluctantly opens to reveal a rickety staircase descending into\ndarkness.",
        "The door swings shut and closes.",
    )
elif player_verb in ["look-under"] and context.player.location == _.get_property("living_room"):
    if _.zil_sdk.flag(_.get_property("trap_door"), "open"):
        return print("You see a rickety staircase descending into darkness.")
    else:
        return print("It's closed.")
elif context.player.location == _.get_property("cellar"):
    if player_verb in ["open", "unlock"] and not _.zil_sdk.flag(_.get_property("trap_door"), "open"):
        return print("The door is locked from above.")
    elif player_verb in ["close", "shut"] and not _.zil_sdk.flag(_.get_property("trap_door"), "open"):
        _.zil_sdk.set_flag(_.get_property("trap_door"), "touchbit", False)
        _.zil_sdk.set_flag(_.get_property("trap_door"), "open", False)
        return print("The door closes and locks.")
    elif player_verb in ["open", "close", "shut"]:
        return print(_.zil_sdk.pick(_.zil_sdk.zstate_get("DUMMY")))
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
