#!moo verb get pick take --on $trophy_case --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: TROPHY-CASE-FCN

if player_verb in ["take", "get", "pick"] and context.parser.get_dobj() == _.get_property("trophy_case"):
    return print("The trophy case is securely fastened to the wall.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
