#!moo verb get oil pick rotate take turn --on $bolt --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: BOLT-F

if player_verb in ["turn", "rotate"]:
    if context.parser.get_iobj() == _.get_property("wrench"):
        if _.zil_sdk.zstate_get("GATE-FLAG"):
            _.zil_sdk.set_flag(_.get_property("reservoir_south"), "touchbit", False)
            if _.zil_sdk.zstate_get("GATES-OPEN"):
                _.zil_sdk.zstate_set("GATES-OPEN", None)
                _.zil_sdk.set_flag(_.get_property("loud_room"), "touchbit", False)
                print("The sluice gates close and water starts to collect behind the dam.")
                _.zil_sdk.queue("i-rfill", 8)
                # ZIL: <QUEUE ...>
                _.zork_thing.invoke_verb("queue", _.zork_thing.invoke_verb("i-rempty"), 0)
                return True
            else:
                _.zil_sdk.zstate_set("GATES-OPEN", True)
                print("The sluice gates open and water pours through the dam.")
                _.zil_sdk.queue("i-rempty", 8)
                # ZIL: <QUEUE ...>
                _.zork_thing.invoke_verb("queue", _.zork_thing.invoke_verb("i-rfill"), 0)
                return True
        else:
            return print("The bolt won't turn with your best effort.")
    elif not context.parser.get_iobj() in (_.get_property("hands"), _.zil_sdk.zstate_get("ROOMS")):
        return print("The bolt won't turn using the " + _.zil_sdk.desc(context.parser.get_iobj()) + ".")
elif player_verb in ["take", "get", "pick"]:
    # ZIL: <INTEGRAL-PART ...>
    return _.zork_thing.invoke_verb("integral-part")
elif player_verb in ["oil"]:
    return print("Hmm. It appears the tube contained glue, not oil. Turning the bolt\nwon't get any easier....")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
