#!moo verb dam-room-fcn --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: DAM-ROOM-FCN
# params: RARG

rarg = args[0] if len(args) > 0 else None

if rarg == "M-LOOK":
    print(
        "You are standing on the top of the Flood Control Dam #3, which was\nquite a tourist attraction in times far distant. There are paths to\nthe north, south, and west, and a scramble down."
    )
    if _.zil_sdk.zstate_get("LOW-TIDE") and _.zil_sdk.zstate_get("GATES-OPEN"):
        print(
            "The water level behind the dam is low: The sluice gates have been\nopened. Water rushes through the dam and downstream."
        )
    elif _.zil_sdk.zstate_get("GATES-OPEN"):
        print(
            "The sluice gates are open, and water rushes through the dam. The\nwater level behind the dam is still high."
        )
    elif _.zil_sdk.zstate_get("LOW-TIDE"):
        print(
            "The sluice gates are closed. The water level in the reservoir is\nquite low, but the level is rising quickly."
        )
    else:
        print(
            "The sluice gates on the dam are closed. Behind the dam, there can be\nseen a wide reservoir. Water is pouring over the top of the now\nabandoned dam."
        )
    print(
        "There is a control panel here, on which a large metal bolt is mounted.\nDirectly above the bolt is a small green plastic bubble",
        end="",
    )
    if _.zil_sdk.zstate_get("GATE-FLAG"):
        print(" which is\nglowing serenely", end="")
    return print(".")
