#!moo verb climb-down climb-foo climb-up through --on "chute" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: SLIDE-FUNCTION

player = context.player
parser = context.parser
cellar = lookup("cellar")
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (
    the_player_verb in ["through", "climb-up", "climb-down", "climb-foo"]
    or the_player_verb in ["put", "place", "insert"]
    and parser.get_dobj() == lookup("me")
):
    if player.here() == cellar:
        _.walk(player.zstate_get("P?WEST"))
        return True
    else:
        print("You tumble down the slide....")
        return _.goto(cellar)
return passthrough()
