#!moo verb look --on $reservoir
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL: RESERVOIR-FCN / M-LOOK

if _.zil_sdk.zstate_get("LOW-TIDE"):
    print(
        'You are on what used to be a large lake, but which is now a large\nmud pile. There are "shores" to the north and south.',
        end="",
    )
else:
    print(
        "You are on the lake. Beaches can be seen north and south.\nUpstream a small stream enters the lake through a narrow cleft\nin the rocks. The dam can be seen downstream.",
        end="",
    )
print()
