#!moo verb count open --on "matchbook" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: MATCH-FUNCTION (count/open branch)

player = context.player
cnt = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("You have ", end="")
cnt = player.zstate_get("MATCH-COUNT") - 1
if not cnt > 0:
    print("no", end="")
else:
    print(str(cnt), end="")
print(" match", end="")
if not cnt == 1:
    print("es.", end="")
else:
    print(".", end="")
print()
return
