#!moo verb is_forest_room --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: FOREST-ROOM?

player = context.player

if not player.here() in (lookup("forest_1"), lookup("forest_2"), lookup("forest_3")):
    return player.here() in (lookup("path"), lookup("up_a_tree"))
