#!moo verb is_infested --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

# ZIL routine: INFESTED?
# params: R
# aux: F

r = args[0] if len(args) > 0 else None
f = r.contents.first()

while True:
    if not f:
        return False
    elif f.flag("actorbit") and not f.flag("invisible"):
        return True
    elif not (f := _.next_sibling(f)):
        return False
