#!moo verb is_lit --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: LIT?
# params: RM, RMBIT
# aux: OHERE, LIT

player = context.player
rm = args[0] if len(args) > 0 else None
rmbit = args[1] if len(args) > 1 else True
ohere = 0
lit = 0

if player.zstate_get("ALWAYS-LIT") and player == player:
    return True
player.zstate_set("P-GWIMBIT", player.zstate_get("ONBIT"))
ohere = player.here()
player.zstate_set("HERE", rm)
if rmbit and rm.flag("onbit"):
    lit = True
else:
    # ZIL: <PUT ...>
    _.table_put(player.zstate_get("P-MERGE"), player.zstate_get("P-MATCHLEN"), 0)
    player.zstate_set("P-TABLE", player.zstate_get("P-MERGE"))
    player.zstate_set("P-SLOCBITS", -1)
    if ohere == rm:
        # ZIL: <DO-SL ...>
        _.zork_thing.do_sl(player, 1, 1)
        if not player == player and player.location == rm:
            # ZIL: <DO-SL ...>
            _.zork_thing.do_sl(player, 1, 1)
    # ZIL: <DO-SL ...>
    _.zork_thing.do_sl(rm, 1, 1)
    if _.table_get(player.zstate_get("P-TABLE"), player.zstate_get("P-MATCHLEN")) > 0:
        lit = True
player.zstate_set("HERE", ohere)
player.zstate_set("P-GWIMBIT", 0)
return lit
