#!moo verb clause-copy --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: CLAUSE-COPY
# params: SRC, DEST, INSRT
# aux: BEG, END

src = args[0] if len(args) > 0 else None
dest = args[1] if len(args) > 1 else None
insrt = args[2] if len(args) > 2 else None
beg = None
end = None

beg = _.zil_sdk.table_get(src, _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-CCTBL"), _.zil_sdk.zstate_get("CC-SBPTR")))
end = _.zil_sdk.table_get(src, _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-CCTBL"), _.zil_sdk.zstate_get("CC-SEPTR")))
# ZIL: <PUT ...>
_.zil_sdk.table_put(
    dest,
    _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-CCTBL"), _.zil_sdk.zstate_get("CC-DBPTR")),
    rest(
        _.zil_sdk.zstate_get("P-OCLAUSE"),
        _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-OCLAUSE"), _.zil_sdk.zstate_get("P-MATCHLEN"))
        * _.zil_sdk.zstate_get("P-LEXELEN")
        + 2,
    ),
)
while True:
    if beg == end:
        # ZIL: <PUT ...>
        _.zil_sdk.table_put(
            dest,
            _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-CCTBL"), _.zil_sdk.zstate_get("CC-DEPTR")),
            rest(
                _.zil_sdk.zstate_get("P-OCLAUSE"),
                _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-OCLAUSE"), _.zil_sdk.zstate_get("P-MATCHLEN"))
                * _.zil_sdk.zstate_get("P-LEXELEN")
                + 2,
            ),
        )
        break
    else:
        if insrt and _.zil_sdk.zstate_get("P-ANAM") == _.zil_sdk.table_get(beg, 0):
            # ZIL: <CLAUSE-ADD ...>
            _.zork_thing.invoke_verb("clause-add", insrt)
        # ZIL: <CLAUSE-ADD ...>
        _.zork_thing.invoke_verb("clause-add", _.zil_sdk.table_get(beg, 0))
    beg = rest(beg, _.zil_sdk.zstate_get("P-WORDLEN"))
