#!moo verb clause --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: CLAUSE
# params: PTR, VAL, WRD
# aux: OFF, NUM, ANDFLG, FIRST??, NW, LW

ptr = args[0] if len(args) > 0 else None
val = args[1] if len(args) > 1 else None
wrd = args[2] if len(args) > 2 else None
off = None
num = None
andflg = None
first_p_p = True
nw = None
lw = 0

off = _.zil_sdk.zstate_get("P-NCN") - 1 * 2
if not val == 0:
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-ITBL"), (num := _.zil_sdk.zstate_get("P-PREP1") + off), val)
    # ZIL: <PUT ...>
    _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-ITBL"), num + 1, wrd)
    ptr = ptr + _.zil_sdk.zstate_get("P-LEXELEN")
else:
    return _.zil_sdk.zstate_set("P-LEN", _.zil_sdk.zstate_get("P-LEN") + 1)
if _.zil_sdk.zstate_get("P-LEN") == 0:
    _.zil_sdk.zstate_set("P-NCN", _.zil_sdk.zstate_get("P-NCN") - 1)
    return -1
# ZIL: <PUT ...>
_.zil_sdk.table_put(
    _.zil_sdk.zstate_get("P-ITBL"),
    (num := _.zil_sdk.zstate_get("P-NC1") + off),
    rest(_.zil_sdk.zstate_get("P-LEXV"), ptr * 2),
)
if _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-LEXV"), ptr) in (
    _.zil_sdk.zstate_get("W?THE"),
    _.zil_sdk.zstate_get("W?A"),
    _.zil_sdk.zstate_get("W?AN"),
):
    # ZIL: <PUT ...>
    return _.zil_sdk.table_put(
        _.zil_sdk.zstate_get("P-ITBL"), num, rest(_.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), num), 4)
    )
while True:
    if _.zil_sdk.zstate_set("P-LEN", _.zil_sdk.zstate_get("P-LEN") - 1) < 0:
        # ZIL: <PUT ...>
        _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-ITBL"), num + 1, rest(_.zil_sdk.zstate_get("P-LEXV"), ptr * 2))
        return -1
    if (wrd := _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-LEXV"), ptr)) or (
        wrd := _.zork_thing.invoke_verb("number?", ptr)
    ):
        if _.zil_sdk.zstate_get("P-LEN") == 0:
            nw = 0
        else:
            nw = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-LEXV"), ptr + _.zil_sdk.zstate_get("P-LEXELEN"))
        if wrd in (_.zil_sdk.zstate_get("W?AND"), _.zil_sdk.zstate_get("W?COMMA")):
            andflg = True
        elif wrd in (_.zil_sdk.zstate_get("W?ALL"), _.zil_sdk.zstate_get("W?ONE")):
            if nw == _.zil_sdk.zstate_get("W?OF"):
                _.zil_sdk.zstate_set("P-LEN", _.zil_sdk.zstate_get("P-LEN") - 1)
                ptr = ptr + _.zil_sdk.zstate_get("P-LEXELEN")
        elif (
            wrd in (_.zil_sdk.zstate_get("W?THEN"), _.zil_sdk.zstate_get("W?PERIOD"))
            or _.zork_thing.invoke_verb("wt?", wrd, _.zil_sdk.zstate_get("PS?PREPOSITION"))
            and _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-VERB"))
            and not first_p_p
        ):
            _.zil_sdk.zstate_set("P-LEN", _.zil_sdk.zstate_get("P-LEN") + 1)
            # ZIL: <PUT ...>
            _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-ITBL"), num + 1, rest(_.zil_sdk.zstate_get("P-LEXV"), ptr * 2))
            return ptr - _.zil_sdk.zstate_get("P-LEXELEN")
        elif _.zork_thing.invoke_verb("wt?", wrd, _.zil_sdk.zstate_get("PS?OBJECT")):
            if (
                _.zil_sdk.zstate_get("P-LEN") > 0
                and nw == _.zil_sdk.zstate_get("W?OF")
                and not wrd in (_.zil_sdk.zstate_get("W?ALL"), _.zil_sdk.zstate_get("W?ONE"))
            ):
                True
            elif (
                _.zork_thing.invoke_verb(
                    "wt?", wrd, _.zil_sdk.zstate_get("PS?ADJECTIVE"), _.zil_sdk.zstate_get("P1?ADJECTIVE")
                )
                and not nw == 0
                and _.zork_thing.invoke_verb("wt?", nw, _.zil_sdk.zstate_get("PS?OBJECT"))
            ):
                pass
            elif (
                not andflg
                and not nw in (_.zil_sdk.zstate_get("W?BUT"), _.zil_sdk.zstate_get("W?EXCEPT"))
                and not nw in (_.zil_sdk.zstate_get("W?AND"), _.zil_sdk.zstate_get("W?COMMA"))
            ):
                # ZIL: <PUT ...>
                _.zil_sdk.table_put(
                    _.zil_sdk.zstate_get("P-ITBL"), num + 1, rest(_.zil_sdk.zstate_get("P-LEXV"), ptr + 2 * 2)
                )
                return ptr
            else:
                andflg = None
        elif (
            _.zil_sdk.zstate_get("P-MERGED")
            or _.zil_sdk.zstate_get("P-OFLAG")
            or not _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-ITBL"), _.zil_sdk.zstate_get("P-VERB")) == 0
            and _.zork_thing.invoke_verb("wt?", wrd, _.zil_sdk.zstate_get("PS?ADJECTIVE"))
            or _.zork_thing.invoke_verb("wt?", wrd, _.zil_sdk.zstate_get("PS?BUZZ-WORD"))
        ):
            pass
        elif (
            andflg
            and _.zork_thing.invoke_verb("wt?", wrd, _.zil_sdk.zstate_get("PS?DIRECTION"))
            or _.zork_thing.invoke_verb("wt?", wrd, _.zil_sdk.zstate_get("PS?VERB"))
        ):
            ptr = ptr - 4
            # ZIL: <PUT ...>
            _.zil_sdk.table_put(_.zil_sdk.zstate_get("P-LEXV"), ptr + 2, _.zil_sdk.zstate_get("W?THEN"))
            _.zil_sdk.zstate_set("P-LEN", _.zil_sdk.zstate_get("P-LEN") + 2)
        elif _.zork_thing.invoke_verb("wt?", wrd, _.zil_sdk.zstate_get("PS?PREPOSITION")):
            True
        else:
            # ZIL: <CANT-USE ...>
            _.zork_thing.invoke_verb("cant-use", ptr)
            return False
    else:
        # ZIL: <UNKNOWN-WORD ...>
        _.zork_thing.invoke_verb("unknown-word", ptr)
        return False
    lw = wrd
    first_p_p = None
    ptr = ptr + _.zil_sdk.zstate_get("P-LEXELEN")
