#!moo verb unknown-word --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: UNKNOWN-WORD
# params: PTR
# aux: BUF

ptr = args[0] if len(args) > 0 else None
buf = None

# ZIL: <PUT ...>
_.zil_sdk.table_put(_.zil_sdk.zstate_get("OOPS-TABLE"), _.zil_sdk.zstate_get("O-PTR"), ptr)
if player_verb in ["say"]:
    print("Nothing happens.")
    return False
print("I don't know the word \"", end="")
# ZIL: <WORD-PRINT ...>
_.zork_thing.invoke_verb(
    "word-print",
    _.zil_sdk.table_get(rest(_.zil_sdk.zstate_get("P-LEXV"), (buf := ptr * 2)), 2),
    _.zil_sdk.table_get(rest(_.zil_sdk.zstate_get("P-LEXV"), buf), 3),
)
print('".')
_.zil_sdk.zstate_set("QUOTE-FLAG", None)
return _.zil_sdk.zstate_set("P-OFLAG", None)
