#!moo verb hello hi --on "sailor" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: SAILOR-FCN (hello branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

player.zstate_set("HS", player.zstate_get("HS") + 1)
if player.zstate_get("ZORK-NUMBER") == 3:
    if not player.zstate_get("VIKING-SHIP").flag("invisible"):
        print(
            'The seaman looks up and maneuvers the boat toward shore. He cries out "I\nhave waited three ages for someone to say those words and save me from\nsailing this endless ocean. Please accept this gift. You may find it\nuseful!" He throws something which falls near you in the sand, then sails\noff toward the west, singing a lively, but somewhat uncouth, sailor song.'
        )
        player.zstate_get("VIKING-SHIP").set_flag("invisible", True)
        return player.zstate_get("VIAL").moveto(player.here())
    elif player.here() == player.zstate_get("FLATHEAD-OCEAN"):
        if player.zstate_get("SHIP-GONE"):
            print("Nothing happens anymore.")
            return
        else:
            print("Nothing happens yet.")
            return
    else:
        print("Nothing happens here.")
        return
else:
    if player.zstate_get("HS") % 20 == 0:
        print("You seem to be repeating yourself.")
        return
    elif player.zstate_get("HS") % 10 == 0:
        print("I think that phrase is getting a bit worn out.")
        return
    else:
        print("Nothing happens here.")
        return
return passthrough()
