#!moo verb cellar-fcn --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: CELLAR-FCN
# params: RARG

rarg = args[0] if len(args) > 0 else None

if rarg == "M-LOOK":
    return print(
        "You are in a dark and damp cellar with a narrow passageway leading\nnorth, and a crawlway to the south. On the west is the bottom of a\nsteep metal ramp which is unclimbable."
    )
elif rarg == "M-ENTER":
    if _.zil_sdk.flag(_.get_property("trap_door"), "open") and not _.zil_sdk.flag(
        _.get_property("trap_door"), "touchbit"
    ):
        _.zil_sdk.set_flag(_.get_property("trap_door"), "open", False)
        _.zil_sdk.set_flag(_.get_property("trap_door"), "touchbit", True)
        return print("The trap door crashes shut, and you hear someone barring it.")
