#!moo verb burn count describe examine lamp-off lamp-on light open what x --on $match --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: MATCH-FUNCTION
# aux: CNT

cnt = None

if player_verb in ["lamp-on", "burn", "light"] and context.parser.get_dobj() == _.get_property("match"):
    if _.zil_sdk.zstate_get("MATCH-COUNT") > 0:
        return _.zil_sdk.zstate_set("MATCH-COUNT", _.zil_sdk.zstate_get("MATCH-COUNT") - 1)
    if not _.zil_sdk.zstate_get("MATCH-COUNT") > 0:
        return print("I'm afraid that you have run out of matches.")
    elif context.player.location in (_.get_property("lower_shaft"), _.get_property("timber_room")):
        return print("This room is drafty, and the match goes out instantly.")
    else:
        _.zil_sdk.set_flag(_.get_property("match"), "flamebit", True)
        _.zil_sdk.set_flag(_.get_property("match"), "onbit", True)
        _.zil_sdk.queue("i-match", 2)
        print("One of the matches starts to burn.")
        if not _.zil_sdk.zstate_get("LIT"):
            _.zil_sdk.zstate_set("LIT", True)
            # ZIL: <V-LOOK ...>
            _.zork_thing.invoke_verb("v-look")
        return True
elif player_verb in ["lamp-off"] and _.zil_sdk.flag(_.get_property("match"), "flamebit"):
    print("The match is out.")
    _.zil_sdk.set_flag(_.get_property("match"), "flamebit", False)
    _.zil_sdk.set_flag(_.get_property("match"), "onbit", False)
    _.zil_sdk.zstate_set("LIT", _.zork_thing.invoke_verb("lit?", context.player.location))
    if not _.zil_sdk.zstate_get("LIT"):
        print("It's pitch black in here!")
    # ZIL: <QUEUE ...>
    _.zork_thing.invoke_verb("queue", _.zork_thing.invoke_verb("i-match"), 0)
    return True
elif player_verb in ["count", "open"]:
    print("You have ", end="")
    cnt = _.zil_sdk.zstate_get("MATCH-COUNT") - 1
    if not cnt > 0:
        print("no", end="")
    else:
        print(str(cnt), end="")
    print(" match", end="")
    if not cnt == 1:
        print("es.", end="")
    else:
        print(".", end="")
    return print()
elif player_verb in ["examine", "x", "describe", "what"]:
    if _.zil_sdk.flag(_.get_property("match"), "onbit"):
        print("The match is burning.", end="")
    else:
        print("The matchbook isn't very interesting, except for what's written on it.", end="")
    return print()
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
