#!moo verb look --on "Machine Room" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned
from moo.sdk import context, lookup
# ZIL: MACHINE-ROOM-FCN / M-LOOK

parser = context.parser
rarg = args[0] if len(args) > 0 else "M-LOOK"
the_player_verb = (
    args[1]
    if len(args) > 1
    else (parser.words[0].lower() if context.parser is not None and parser.words else verb_name)
)

print(
    'This is a large, cold room whose sole exit is to the north. In one\ncorner there is a machine which is reminiscent of a clothes\ndryer. On its face is a switch which is labelled "START".\nThe switch does not appear to be manipulable by any human hand (unless the\nfingers are about 1/16 by 1/4 inch). On the front of the machine is a large\nlid, which is ',
    end="",
)
if lookup("machine").flag("open"):
    print("open.", end="")
else:
    print("closed.", end="")
print()
