#!moo verb rotate turn --on $machine_switch --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: MSWITCH-FUNCTION
# aux: O

o = None

if player_verb in ["turn", "rotate"]:
    if context.parser.get_iobj() == _.get_property("screwdriver"):
        if _.zil_sdk.flag(_.get_property("machine"), "open"):
            return print("The machine doesn't seem to want to do anything.")
        else:
            print(
                "The machine comes to life (figuratively) with a dazzling display of\ncolored lights and bizarre noises. After a few moments, the\nexcitement abates."
            )
            if _.get_property("coal").location == _.get_property("machine"):
                _.zil_sdk.remove(_.get_property("coal"))
                return _.zil_sdk.move(_.get_property("diamond"), _.get_property("machine"))
            else:
                while True:
                    if o := _.get_property("machine").contents.first():
                        _.zil_sdk.remove(o)
                    else:
                        break
                return _.zil_sdk.move(_.get_property("gunk"), _.get_property("machine"))
    elif not context.parser.get_iobj() in (_.get_property("hands"), _.zil_sdk.zstate_get("ROOMS")):
        return print("It seems that a " + _.zil_sdk.desc(context.parser.get_iobj()) + " won't do.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
