#!moo verb put stuff insert place hide --on "Zork Actor" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

# Player command for PUT: put in container (with prep) or drop (bare).
from moo.sdk import context

if context.parser.prepositions:
    if _.zork_thing.has_verb("pre-put") and _.zork_thing.invoke_verb("pre-put"):
        return
    _.zork_thing.put()
else:
    if _.zork_thing.has_verb("pre-drop") and _.zork_thing.invoke_verb("pre-drop"):
        return
    _.zork_thing.drop()
