#!moo verb throw hurl chuck toss --on $player --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
"""Player command for THROW: delegate to V-THROW."""

_.zork_thing.invoke_verb("v-throw")
