#!moo verb tie fasten secure attach --on $player --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
"""Player command for TIE: delegate to V-TIE."""

_.zork_thing.invoke_verb("v-tie")
