#!moo verb walk go run proceed step --on $player --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
"""Player command for WALK: traverse an exit Object."""

from moo.sdk import context

if context.parser.has_dobj_str():
    _.zil_sdk.walk(context.parser.get_dobj_str())
else:
    print("Where do you want to go?")
