#!moo verb attack break crack cut describe destroy examine fight get hit kill look-inside mung pick rub slice smash stab take throw toss what x --on $mirror_1 --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: MIRROR-MIRROR
# aux: RM2, L1, L2, N

rm2 = _.get_property("mirror_room_2")
l1 = None
l2 = None
n = None

if not _.zil_sdk.zstate_get("MIRROR-MUNG") and player_verb in ["rub"]:
    if context.parser.get_iobj() and not context.parser.get_iobj() == _.get_property("hands"):
        print("You feel a faint tingling transmitted through the " + _.zil_sdk.desc(context.parser.get_iobj()) + ".")
        return True
    if context.player.location == rm2:
        rm2 = _.get_property("mirror_room_1")
    l1 = context.player.location.contents.first()
    l2 = rm2.contents.first()
    while True:
        if not l1:
            break
        n = _.zil_sdk.next_sibling(l1)
        _.zil_sdk.move(l1, rm2)
        l1 = n
    while True:
        if not l2:
            break
        n = _.zil_sdk.next_sibling(l2)
        _.zil_sdk.move(l2, context.player.location)
        l2 = n
    _.zil_sdk.goto(rm2)
    return print("There is a rumble from deep within the earth and the room shakes.")
elif player_verb in ["look-inside", "examine", "x", "describe", "what"]:
    if _.zil_sdk.zstate_get("MIRROR-MUNG"):
        print("The mirror is broken into many pieces.", end="")
    else:
        print("There is an ugly person staring back at you.", end="")
    return print()
elif player_verb in ["take", "get", "pick"]:
    return print("The mirror is many times your size. Give up.")
elif player_verb in [
    "mung",
    "destroy",
    "break",
    "smash",
    "crack",
    "throw",
    "toss",
    "attack",
    "kill",
    "hit",
    "fight",
    "stab",
    "cut",
    "slice",
]:
    if _.zil_sdk.zstate_get("MIRROR-MUNG"):
        return print("Haven't you done enough damage already?")
    else:
        _.zil_sdk.zstate_set("MIRROR-MUNG", True)
        _.zil_sdk.zstate_set("LUCKY", None)
        return print("You have broken the mirror. I hope you have a seven years' supply of\ngood luck handy.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
