#!moo verb enterfunc --on $loud_room
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context, lookup
# ZIL: LOUD-ROOM-FCN / M-ENTER

if _.zil_sdk.zstate_get("LOUD-FLAG") or not _.zil_sdk.zstate_get("GATES-OPEN") and _.zil_sdk.zstate_get("LOW-TIDE"):
    return False
elif _.zil_sdk.zstate_get("GATES-OPEN") and not _.zil_sdk.zstate_get("LOW-TIDE"):
    return False
else:
    # ZIL: <V-FIRST-LOOK ...>
    _.zork_thing.invoke_verb("v-first-look")
    if context.player:
        print("The rest of your commands have been lost in the noise.")
        _.zil_sdk.zstate_set("P-CONT", None)
    while True:
        if not _.zil_sdk.zstate_get("SUPER-BRIEF"):
            print()
        print(">", end="")
        # ZIL: <READ ...>
        read(_.zil_sdk.zstate_get("P-INBUF"), _.zil_sdk.zstate_get("P-LEXV"))
        if _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-LEXV"), _.zil_sdk.zstate_get("P-LEXWORDS")) == 0:
            print("I beg your pardon?")
            # ZIL: <AGAIN ...>
            lookup("again")
        wrd = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-LEXV"), 1)
        if wrd in (_.zil_sdk.zstate_get("W?GO"), _.zil_sdk.zstate_get("W?WALK"), _.zil_sdk.zstate_get("W?RUN")):
            wrd = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-LEXV"), 3)
        elif wrd == _.zil_sdk.zstate_get("W?SAY"):
            wrd = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-LEXV"), 5)
        if wrd == _.zil_sdk.zstate_get("W?SAVE"):
            # ZIL: <V-SAVE ...>
            _.zork_thing.invoke_verb("v-save")
        elif wrd == _.zil_sdk.zstate_get("W?RESTORE"):
            # ZIL: <V-RESTORE ...>
            _.zork_thing.invoke_verb("v-restore")
        elif wrd in (_.zil_sdk.zstate_get("W?Q"), _.zil_sdk.zstate_get("W?QUIT")):
            # ZIL: <V-QUIT ...>
            _.zork_thing.invoke_verb("v-quit")
        elif wrd in (_.zil_sdk.zstate_get("W?W"), _.zil_sdk.zstate_get("W?WEST")):
            return _.zork_thing.invoke_verb("goto", _.get_property("round_room"))
        elif wrd in (_.zil_sdk.zstate_get("W?E"), _.zil_sdk.zstate_get("W?EAST")):
            return _.zork_thing.invoke_verb("goto", _.get_property("damp_cave"))
        elif wrd in (_.zil_sdk.zstate_get("W?U"), _.zil_sdk.zstate_get("W?UP")):
            return _.zork_thing.invoke_verb("goto", _.get_property("deep_canyon"))
        elif wrd == _.zil_sdk.zstate_get("W?BUG"):
            print("That's only your opinion.")
        elif wrd == _.zil_sdk.zstate_get("W?ECHO"):
            _.zil_sdk.zstate_set("LOUD-FLAG", True)
            _.zil_sdk.set_flag(_.get_property("bar"), "sacred", False)
            print("The acoustics of the room change subtly.")
            if not _.zil_sdk.zstate_get("SUPER-BRIEF"):
                print()
            break
        else:
            # ZIL: <V-ECHO ...>
            _.zork_thing.invoke_verb("v-echo")
