#!moo verb look --on $loud_room
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL: LOUD-ROOM-FCN / M-LOOK

print(
    "This is a large room with a ceiling which cannot be detected from\nthe ground. There is a narrow passage from east to west and a stone\nstairway leading upward.",
    end="",
)
if _.zil_sdk.zstate_get("LOUD-FLAG") or not _.zil_sdk.zstate_get("GATES-OPEN") and _.zil_sdk.zstate_get("LOW-TIDE"):
    print(" The room is eerie in its quietness.", end="")
else:
    print(
        " The room is deafeningly loud with an\nundetermined rushing sound. The sound seems to reverberate from all\nof the walls, making it difficult even to think.",
        end="",
    )
print()
