#!moo verb deep-canyon-f --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: DEEP-CANYON-F
# params: RARG

rarg = args[0] if len(args) > 0 else None

if rarg == "M-LOOK":
    print(
        "You are on the south edge of a deep canyon. Passages lead off to the\neast, northwest and southwest. A stairway leads down.",
        end="",
    )
    if _.zil_sdk.zstate_get("GATES-OPEN") and not _.zil_sdk.zstate_get("LOW-TIDE"):
        print(" You can hear a loud roaring sound, like that of rushing water, from\nbelow.", end="")
    elif not _.zil_sdk.zstate_get("GATES-OPEN") and _.zil_sdk.zstate_get("LOW-TIDE"):
        print()
        return True
    else:
        print(" You can hear the sound of flowing water from below.", end="")
    return print()
