#!moo verb put place insert --on "grating" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: GRATE-FUNCTION (put branch)

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (parser.get_iobj() if parser.has_iobj() else None) == this:
    if parser.get_dobj().getp("size") > 20:
        print("It won't fit through the grating.")
        return
    else:
        parser.get_dobj().moveto(lookup("grating_room"))
        print("The " + parser.get_dobj().desc() + " goes through the grating into the darkness below.")
        return
return passthrough()
