#!moo verb get pick take --on $knife --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: KNIFE-F

if player_verb in ["take", "get", "pick"]:
    _.zil_sdk.set_flag(_.get_property("attic_table"), "obvious", False)
    return False
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
