#!moo verb attach climb-down drop fasten get pick take tie tie-up untie --on $rope --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: ROPE-FUNCTION
# aux: RLOC

rloc = None

if not context.player.location == _.get_property("dome_room"):
    _.zil_sdk.zstate_set("DOME-FLAG", None)
    if player_verb in ["tie", "attach", "fasten"]:
        return print("You can't tie the rope to that.")
elif player_verb in ["tie", "attach", "fasten"]:
    if context.parser.get_iobj() == _.get_property("railing"):
        if _.zil_sdk.zstate_get("DOME-FLAG"):
            return print("The rope is already tied to it.")
        else:
            print("The rope drops over the side and comes within ten feet of the floor.")
            _.zil_sdk.zstate_set("DOME-FLAG", True)
            _.zil_sdk.set_flag(_.get_property("rope"), "obvious", True)
            rloc = _.get_property("rope").location
            if not rloc or not rloc.location == _.zil_sdk.zstate_get("ROOMS"):
                _.zil_sdk.move(_.get_property("rope"), context.player.location)
            return True
elif (
    player_verb in ["climb-down"]
    and context.parser.get_dobj() in (_.get_property("rope"), _.zil_sdk.zstate_get("ROOMS"))
    and _.zil_sdk.zstate_get("DOME-FLAG")
):
    return _.zil_sdk.walk(_.zil_sdk.zstate_get("P?DOWN"))
elif player_verb in ["tie-up"] and _.get_property("rope") == context.parser.get_iobj():
    if _.zil_sdk.flag(context.parser.get_dobj(), "actorbit"):
        if context.parser.get_dobj().get_property("strength") < 0:
            print("Your attempt to tie up the " + _.zil_sdk.desc(context.parser.get_dobj()) + " awakens him.", end="")
            # ZIL: <AWAKEN ...>
            return _.zork_thing.invoke_verb("awaken", context.parser.get_dobj())
        else:
            return print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " struggles and you cannot tie him up.")
    else:
        return print("Why would you tie up a " + _.zil_sdk.desc(context.parser.get_dobj()) + "?")
elif player_verb in ["untie"]:
    if _.zil_sdk.zstate_get("DOME-FLAG"):
        _.zil_sdk.zstate_set("DOME-FLAG", None)
        _.zil_sdk.set_flag(_.get_property("rope"), "obvious", False)
        return print("The rope is now untied.")
    else:
        return print("It is not tied to anything.")
elif (
    player_verb in ["drop"]
    and context.player.location == _.get_property("dome_room")
    and not _.zil_sdk.zstate_get("DOME-FLAG")
):
    _.zil_sdk.move(_.get_property("rope"), _.get_property("torch_room"))
    return print("The rope drops gently to the floor below.")
elif player_verb in ["take", "get", "pick"]:
    if _.zil_sdk.zstate_get("DOME-FLAG"):
        return print("The rope is tied to the railing.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
