baseURL = 'https://bubblehouse.gitlab.io/django-moo/'
languageCode = 'en-us'
title = 'django-moo'
theme = 'ananke'
contentDir = "content"

[params]
  body_classes = "avenir"
  custom_css = ["custom.css"]
