#!moo verb pour-on --on "red hot brass bell" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: HOT-BELL-F (pour-on branch)

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

_.remove(parser.get_dobj())
print("The water cools the bell and is evaporated.")
# ZIL: <QUEUE ...>
_.zork_thing.queue(_.zork_thing.i_xbh(), 0)
# ZIL: <I-XBH ...>
return _.zork_thing.i_xbh()
