#!moo verb rub --on "red hot brass bell" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: HOT-BELL-F

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if the_player_verb == "rub" or the_player_verb == "ring" and (parser.get_iobj() if parser.has_iobj() else None):
    if (parser.get_iobj() if parser.has_iobj() else None).flag("flammable"):
        print("The " + (parser.get_iobj() if parser.has_iobj() else None).desc() + " burns and is consumed.")
        return _.remove((parser.get_iobj() if parser.has_iobj() else None))
    elif (parser.get_iobj() if parser.has_iobj() else None) == lookup("hands"):
        print("The bell is too hot to touch.")
        return
    else:
        print("The heat from the bell is too intense.")
        return
return passthrough()
