#!moo verb eat --on $garlic --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: GARLIC-F

if player_verb in ["eat"]:
    _.zil_sdk.remove(context.parser.get_dobj())
    return print(
        "What the heck! You won't make friends this way, but nobody around\nhere is too friendly anyhow. Gulp!"
    )
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
