#!moo verb smell sniff --on $sandwich_bag --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: SANDWICH-BAG-FCN

if player_verb in ["smell", "sniff"] and _.get_property("lunch").location == context.parser.get_dobj():
    return print("It smells of hot peppers.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
