#!moo verb v-attack --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-ATTACK

if not _.zil_sdk.flag(context.parser.get_dobj(), "actorbit"):
    return print("I've known strange people, but fighting a " + _.zil_sdk.desc(context.parser.get_dobj()) + "?")
elif not context.parser.get_iobj() or context.parser.get_iobj() == _.get_property("hands"):
    return print(
        "Trying to attack a " + _.zil_sdk.desc(context.parser.get_dobj()) + " with your bare hands is suicidal."
    )
elif not context.parser.get_iobj().location == context.player:
    return print("You aren't even holding the " + _.zil_sdk.desc(context.parser.get_iobj()) + ".")
elif not _.zil_sdk.flag(context.parser.get_iobj(), "weapon"):
    return print(
        "Trying to attack the "
        + _.zil_sdk.desc(context.parser.get_dobj())
        + " with a "
        + _.zil_sdk.desc(context.parser.get_iobj())
        + " is suicidal."
    )
else:
    if _.zil_sdk.zstate_get("ZORK-NUMBER") == 1:
        # ZIL: <HERO-BLOW ...>
        return _.zork_thing.invoke_verb("hero-blow")
    else:
        return print("You can't.")
