#!moo verb v-board --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-BOARD
# aux: AV

av = None

print("You are now in the " + _.zil_sdk.desc(context.parser.get_dobj()) + ".")
_.zil_sdk.move(context.player, context.parser.get_dobj())
# ZIL: <APPLY ...>
apply(_.zil_sdk.getp(context.parser.get_dobj(), "action"), "M-ENTER")
return True
