#!moo verb v-climb-on --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-CLIMB-ON

if _.zil_sdk.flag(context.parser.get_dobj(), "vehicle"):
    if _.zil_sdk.zstate_get("ZORK-NUMBER") == 3:
        # ZIL: <V-CLIMB-UP ...>
        _.zork_thing.invoke_verb("v-climb-up", _.zil_sdk.zstate_get("P?UP"), True)
    else:
        _.zil_sdk.perform(_.zil_sdk.zstate_get("V?BOARD"), context.parser.get_dobj(), None)
    return True
else:
    return print("You can't climb onto the " + _.zil_sdk.desc(context.parser.get_dobj()) + ".")
