#!moo verb v-close --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-CLOSE

if not _.zil_sdk.flag(context.parser.get_dobj(), "contbit") and not _.zil_sdk.flag(
    context.parser.get_dobj(), "is_door"
):
    return print("You must tell me how to do that to a " + _.zil_sdk.desc(context.parser.get_dobj()) + ".")
elif (
    not _.zil_sdk.flag(context.parser.get_dobj(), "surfacebit")
    and not _.zil_sdk.getp(context.parser.get_dobj(), "capacity") == 0
):
    if _.zil_sdk.flag(context.parser.get_dobj(), "open"):
        _.zil_sdk.set_flag(context.parser.get_dobj(), "open", False)
        print("Closed.")
        if _.zil_sdk.zstate_get("LIT") and not _.zil_sdk.zstate_set(
            "LIT", _.zork_thing.invoke_verb("lit?", context.player.location)
        ):
            print("It is now pitch black.")
        return True
    else:
        return print("It is already closed.")
elif _.zil_sdk.flag(context.parser.get_dobj(), "is_door"):
    if _.zil_sdk.flag(context.parser.get_dobj(), "open"):
        _.zil_sdk.set_flag(context.parser.get_dobj(), "open", False)
        return print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " is now closed.")
    else:
        return print("It is already closed.")
else:
    return print("You cannot close that.")
