#!moo verb v-command --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-COMMAND

if _.zil_sdk.flag(context.parser.get_dobj(), "actorbit"):
    return print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " pays no attention.")
else:
    return print("You cannot talk to that!")
