#!moo verb v-curses --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-CURSES

if context.parser.get_dobj():
    if _.zil_sdk.flag(context.parser.get_dobj(), "actorbit"):
        return print("Insults of this nature won't help you.")
    else:
        return print("What a loony!")
else:
    return print("Such language in a high-class establishment like this!")
