#!moo verb v-disembark --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-DISEMBARK

if context.parser.get_dobj() == _.zil_sdk.zstate_get("ROOMS") and _.zil_sdk.flag(context.player.location, "vehicle"):
    _.zil_sdk.perform(_.zil_sdk.zstate_get("V?DISEMBARK"), context.player.location, None)
    return True
elif not context.player.location == context.parser.get_dobj():
    print("You're not in that!")
    # ZIL: <RFATAL ...>
    return 2
elif _.zil_sdk.flag(context.player.location, "outdoor"):
    print("You are on your own feet again.")
    return _.zil_sdk.move(context.player, context.player.location)
else:
    print("You realize that getting out here would be fatal.")
    # ZIL: <RFATAL ...>
    return 2
