#!moo verb v-enchant --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-ENCHANT

if _.zil_sdk.zstate_get("ZORK-NUMBER") == 2:
    if _.zil_sdk.zstate_get("WAND-ON"):
        return _.zil_sdk.zstate_set("SPELL-VICTIM", _.zil_sdk.zstate_get("WAND-ON"))
else:
    # ZIL: <NULL-F ...>
    return _.zork_thing.invoke_verb("null-f")
if _.zil_sdk.zstate_get("ZORK-NUMBER") == 2:
    if _.zil_sdk.zstate_get("SPELL-VICTIM"):
        if not _.zil_sdk.zstate_get("SPELL-USED"):
            print("You must be more specific.")
            return True
        if (
            _.zil_sdk.zstate_get("SPELL-USED")
            in (_.zil_sdk.zstate_get("W?FEEBLE"), _.zil_sdk.zstate_get("W?FUMBLE"), _.zil_sdk.zstate_get("W?FEAR"))
            or _.zil_sdk.zstate_get("SPELL-USED")
            in (_.zil_sdk.zstate_get("W?FREEZE"), _.zil_sdk.zstate_get("W?FALL"), _.zil_sdk.zstate_get("W?FERMENT"))
            or _.zil_sdk.zstate_get("SPELL-USED")
            in (_.zil_sdk.zstate_get("W?FIERCE"), _.zil_sdk.zstate_get("W?FENCE"), _.zil_sdk.zstate_get("W?FANTASIZE"))
        ):
            if _.zil_sdk.flag(context.parser.get_dobj(), "actorbit"):
                return print("The wand stops glowing, but there is no other obvious effect.")
            else:
                return print(
                    "That might have done something, but it's hard to tell with a "
                    + _.zil_sdk.desc(context.parser.get_dobj())
                    + "."
                )
        elif _.zil_sdk.zstate_get("SPELL-USED") == _.zil_sdk.zstate_get("W?FUDGE"):
            return print("A strong odor of chocolate permeates the room.")
        elif _.zil_sdk.zstate_get("SPELL-USED") == _.zil_sdk.zstate_get("W?FLUORESCE"):
            _.zil_sdk.set_flag(context.parser.get_dobj(), "lit", True)
            _.zil_sdk.set_flag(context.parser.get_dobj(), "onbit", True)
            _.zil_sdk.zstate_set("LIT", True)
            return print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " begins to glow.")
        elif _.zil_sdk.zstate_get("SPELL-USED") == _.zil_sdk.zstate_get("W?FILCH"):
            _.zil_sdk.zstate_set("SPELL-HANDLED?", True)
            if _.zil_sdk.flag(context.parser.get_dobj(), "takeable"):
                _.zil_sdk.move(context.parser.get_dobj(), context.player)
                # ZIL: <SCORE-OBJ ...>
                _.zork_thing.invoke_verb("score-obj", context.parser.get_dobj())
                return print("Filched!")
            else:
                return print("You can't filch the " + _.zil_sdk.desc(context.parser.get_dobj()) + "!")
        elif _.zil_sdk.zstate_get("SPELL-USED") == _.zil_sdk.zstate_get("W?FLOAT") and _.zil_sdk.flag(
            context.parser.get_dobj(), "takeable"
        ):
            if _.zil_sdk.zstate_get("SPELL-VICTIM") == _.zil_sdk.zstate_get("COLLAR") and _.zil_sdk.zstate_get(
                "COLLAR"
            ).location == _.zil_sdk.zstate_get("CERBERUS"):
                _.zil_sdk.zstate_set("SPELL-VICTIM", _.zil_sdk.zstate_get("CERBERUS"))
            return print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " floats serenely in midair.")
        elif _.zil_sdk.zstate_get("SPELL-USED") == _.zil_sdk.zstate_get("W?FRY") and _.zil_sdk.flag(
            context.parser.get_dobj(), "takeable"
        ):
            _.zil_sdk.zstate_set("SPELL-HANDLED?", True)
            _.zil_sdk.remove(context.parser.get_dobj())
            return print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " goes up in a puff of smoke.")
        else:
            _.zil_sdk.zstate_set("SPELL-VICTIM", None)
            return print("The wand stops glowing, but there is no other apparent effect.")
    else:
        _.zil_sdk.zstate_set("SPELL-VICTIM", None)
        return print("Nothing happens.")
else:
    # ZIL: <V-DISENCHANT ...>
    return _.zork_thing.invoke_verb("v-disenchant")
