#!moo verb v-examine --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-EXAMINE

if context.parser.get_dobj().get_property("text"):
    return print(context.parser.get_dobj().get_property("text"))
elif _.zil_sdk.flag(context.parser.get_dobj(), "contbit") or _.zil_sdk.flag(context.parser.get_dobj(), "is_door"):
    # ZIL: <V-LOOK-INSIDE ...>
    return _.zork_thing.invoke_verb("v-look-inside")
else:
    return print("There's nothing special about the " + _.zil_sdk.desc(context.parser.get_dobj()) + ".")
