#!moo verb v-first-look --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: V-FIRST-LOOK

if _.zork_thing.invoke_verb("describe-room"):
    if not _.zil_sdk.zstate_get("SUPER-BRIEF"):
        # ZIL: <DESCRIBE-OBJECTS ...>
        return _.zork_thing.invoke_verb("describe-objects")
