#!moo verb v-hello --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-HELLO

if context.parser.get_dobj():
    if _.zil_sdk.flag(context.parser.get_dobj(), "actorbit"):
        return print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " bows his head to you in greeting.")
    else:
        return print(
            'It\'s a well known fact that only schizophrenics say "Hello" to a '
            + _.zil_sdk.desc(context.parser.get_dobj())
            + "."
        )
else:
    return print(_.zil_sdk.pick(_.zil_sdk.zstate_get("HELLOS")))
