#!moo verb v-incant --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
from moo.sdk import context
# ZIL routine: V-INCANT

if _.zil_sdk.zstate_get("ZORK-NUMBER") == 2:
    if _.zil_sdk.zstate_get("SPELL-USED"):
        print("Nothing happens.")
    elif _.zil_sdk.zstate_get("WAND-ON"):
        _.zil_sdk.zstate_set("SPELL-VICTIM", _.zil_sdk.zstate_get("WAND-ON"))
        _.zil_sdk.zstate_set("SPELL-USED", _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-LEXV"), context.player))
        print("The wand glows very brightly for a moment.")
        _.zil_sdk.queue("i-spell", 10 + random.randint(1, 10))
        _.zil_sdk.zstate_set("WAND-ON", None)
        _.zil_sdk.perform(_.zil_sdk.zstate_get("V?ENCHANT"), _.zil_sdk.zstate_get("SPELL-VICTIM"), None)
    else:
        print("The incantation echoes back faintly, but nothing else happens.")
else:
    print("The incantation echoes back faintly, but nothing else happens.")
_.zil_sdk.zstate_set("QUOTE-FLAG", None)
_.zil_sdk.zstate_set("P-CONT", None)
return True
