#!moo verb v-inventory --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-INVENTORY

if context.player.contents.first():
    # ZIL: <PRINT-CONT ...>
    return _.zork_thing.invoke_verb("print-cont", context.player)
else:
    return print("You are empty-handed.")
