#!moo verb v-knock --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-KNOCK

if _.zil_sdk.flag(context.parser.get_dobj(), "is_door"):
    return print("Nobody's home.")
else:
    return print("Why knock on a " + _.zil_sdk.desc(context.parser.get_dobj()) + "?")
