#!moo verb v-leap --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-LEAP
# aux: TX, S

tx = None
s = None

if context.parser.get_dobj():
    if context.parser.get_dobj().location == context.player.location:
        if _.zil_sdk.flag(context.parser.get_dobj(), "actorbit"):
            return print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " is too big to jump over.")
        else:
            # ZIL: <V-SKIP ...>
            return _.zork_thing.invoke_verb("v-skip")
    else:
        return print("That would be a good trick.")
elif tx := getpt(context.player.location, _.zil_sdk.zstate_get("P?DOWN")):
    s = ptsize(tx)
    if s == 2 or s == 4 and not value(_.zil_sdk.table_get(tx, 1)):
        print("This was not a very safe place to try jumping.")
        return _.zil_sdk.jigs_up(_.zil_sdk.pick(_.zil_sdk.zstate_get("JUMPLOSS")))
    elif context.player.location == _.get_property("up_a_tree"):
        print("In a feat of unaccustomed daring, you manage to land on your feet without\nkilling yourself.")
        _.zil_sdk.walk(_.zil_sdk.zstate_get("P?DOWN"))
        return True
    else:
        # ZIL: <V-SKIP ...>
        return _.zork_thing.invoke_verb("v-skip")
else:
    # ZIL: <V-SKIP ...>
    return _.zork_thing.invoke_verb("v-skip")
