#!moo verb v-look-inside --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-LOOK-INSIDE

if _.zil_sdk.flag(context.parser.get_dobj(), "is_door"):
    if _.zil_sdk.flag(context.parser.get_dobj(), "open"):
        print(
            "The " + _.zil_sdk.desc(context.parser.get_dobj()) + " is open, but I can't tell what's beyond it.", end=""
        )
    else:
        print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " is closed.", end="")
    return print()
elif _.zil_sdk.flag(context.parser.get_dobj(), "contbit"):
    if _.zil_sdk.flag(context.parser.get_dobj(), "actorbit"):
        return print("There is nothing special to be seen.")
    elif _.zork_thing.invoke_verb("see-inside?", context.parser.get_dobj()):
        if context.parser.get_dobj().contents.first() and _.zork_thing.invoke_verb(
            "print-cont", context.parser.get_dobj()
        ):
            return True
        elif _.zork_thing.invoke_verb("null-f"):
            return True
        else:
            return print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " is empty.")
    else:
        return print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " is closed.")
else:
    return print("You can't look inside a " + _.zil_sdk.desc(context.parser.get_dobj()) + ".")
