#!moo verb v-melt --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-MELT

return print("It's not clear that a " + _.zil_sdk.desc(context.parser.get_dobj()) + " can be melted.")
