#!moo verb v-odysseus --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context, lookup
# ZIL routine: V-ODYSSEUS

if (
    context.player.location == _.get_property("cyclops_room")
    and lookup("cyclops").location == context.player.location
    and not _.zil_sdk.zstate_get("CYCLOPS-FLAG")
):
    _.zil_sdk.cancel("i-cyclops")
    _.zil_sdk.zstate_set("CYCLOPS-FLAG", True)
    print(
        "The cyclops, hearing the name of his father's deadly nemesis, flees the room\nby knocking down the wall on the east of the room."
    )
    _.zil_sdk.zstate_set("MAGIC-FLAG", True)
    _.zil_sdk.set_flag(lookup("cyclops"), "hostile", False)
    return _.zil_sdk.remove(lookup("cyclops"))
else:
    return print("Wasn't he a sailor?")
