#!moo verb v-oil --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: V-OIL

return print("You probably put spinach in your gas tank, too.")
