#!moo verb v-open --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-OPEN
# aux: F, STR

f = None
str_v = None

if (
    _.zil_sdk.flag(context.parser.get_dobj(), "contbit")
    and not _.zil_sdk.getp(context.parser.get_dobj(), "capacity") == 0
):
    if _.zil_sdk.flag(context.parser.get_dobj(), "open"):
        return print("It is already open.")
    else:
        _.zil_sdk.set_flag(context.parser.get_dobj(), "open", True)
        _.zil_sdk.set_flag(context.parser.get_dobj(), "touchbit", True)
        if not context.parser.get_dobj().contents.first() or _.zil_sdk.flag(context.parser.get_dobj(), "transparent"):
            return print("Opened.")
        elif (
            (f := context.parser.get_dobj().contents.first())
            and not _.zil_sdk.next_sibling(f)
            and not _.zil_sdk.flag(f, "touchbit")
            and (str_v := _.zil_sdk.getp(f, "first_description"))
        ):
            print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " opens.")
            return print(str_v)
        else:
            print("Opening the " + _.zil_sdk.desc(context.parser.get_dobj()) + " reveals ", end="")
            # ZIL: <PRINT-CONTENTS ...>
            _.zork_thing.invoke_verb("print-contents", context.parser.get_dobj())
            return print(".")
elif _.zil_sdk.flag(context.parser.get_dobj(), "is_door"):
    if _.zil_sdk.flag(context.parser.get_dobj(), "open"):
        return print("It is already open.")
    else:
        print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " opens.")
        return _.zil_sdk.set_flag(context.parser.get_dobj(), "open", True)
else:
    return print("You must tell me how to do that to a " + _.zil_sdk.desc(context.parser.get_dobj()) + ".")
