#!moo verb v-overboard --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-OVERBOARD
# aux: LOCN

locn = None

if context.parser.get_iobj() == _.get_property("teeth"):
    if _.zil_sdk.flag((locn := context.player.location), "vehicle"):
        _.zil_sdk.move(context.parser.get_dobj(), locn.location)
        return print("Ahoy -- " + _.zil_sdk.desc(context.parser.get_dobj()) + " overboard!")
    else:
        return print("You're not in anything!")
elif _.zil_sdk.flag(context.player.location, "vehicle"):
    _.zil_sdk.perform(_.zil_sdk.zstate_get("V?THROW"), context.parser.get_dobj(), None)
    return True
else:
    return print("Huh?")
