#!moo verb v-put-on --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-PUT-ON

if context.parser.get_iobj() == _.get_property("ground"):
    _.zil_sdk.perform(_.zil_sdk.zstate_get("V?DROP"), context.parser.get_dobj(), None)
    return True
elif _.zil_sdk.flag(context.parser.get_iobj(), "surfacebit"):
    # ZIL: <V-PUT ...>
    return _.zork_thing.invoke_verb("v-put")
else:
    return print("There's no good surface on the " + _.zil_sdk.desc(context.parser.get_iobj()) + ".")
