#!moo verb v-put --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-PUT

if (
    _.zil_sdk.flag(context.parser.get_iobj(), "open")
    or openable_p(context.parser.get_iobj())
    or _.zil_sdk.flag(context.parser.get_iobj(), "vehicle")
):
    pass
else:
    print("You can't do that.")
    return True
if not _.zil_sdk.flag(context.parser.get_iobj(), "open"):
    print("The " + _.zil_sdk.desc(context.parser.get_iobj()) + " isn't open.")
    # ZIL: <THIS-IS-IT ...>
    return _.zork_thing.invoke_verb("this-is-it", context.parser.get_iobj())
elif context.parser.get_iobj() == context.parser.get_dobj():
    return print("How can you do that?")
elif context.parser.get_dobj().location == context.parser.get_iobj():
    return print(
        "The "
        + _.zil_sdk.desc(context.parser.get_dobj())
        + " is already in the "
        + _.zil_sdk.desc(context.parser.get_iobj())
        + "."
    )
elif _.zork_thing.invoke_verb("weight", context.parser.get_iobj()) + _.zork_thing.invoke_verb(
    "weight", context.parser.get_dobj()
) - _.zil_sdk.getp(context.parser.get_iobj(), "size") > _.zil_sdk.getp(context.parser.get_iobj(), "capacity"):
    return print("There's no room.")
elif not _.zork_thing.invoke_verb("held?", context.parser.get_dobj()) and _.zil_sdk.flag(
    context.parser.get_dobj(), "trytakebit"
):
    print("You don't have the " + _.zil_sdk.desc(context.parser.get_dobj()) + ".")
    return True
elif not _.zork_thing.invoke_verb("held?", context.parser.get_dobj()) and not _.zork_thing.invoke_verb("itake"):
    return True
else:
    _.zil_sdk.move(context.parser.get_dobj(), context.parser.get_iobj())
    _.zil_sdk.set_flag(context.parser.get_dobj(), "touchbit", True)
    # ZIL: <SCORE-OBJ ...>
    _.zork_thing.invoke_verb("score-obj", context.parser.get_dobj())
    return print("Done.")
