#!moo verb v-quit --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import lookup
# ZIL routine: V-QUIT
# aux: SCOR

scor = None

# ZIL: <V-SCORE ...>
_.zork_thing.invoke_verb("v-score")
print("Do you wish to leave the game? (Y is affirmative): ", end="")
if yes_p():
    # ZIL: <QUIT ...>
    return lookup("quit")
else:
    return print("Ok.")
