#!moo verb v-random --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
from moo.sdk import context
# ZIL routine: V-RANDOM

if not context.parser.get_dobj() == _.get_property("intnum"):
    return print("Illegal call to #RND.")
else:
    random.randint(1, 0 - _.zil_sdk.zstate_get("P-NUMBER"))
    return True
