#!moo verb v-say --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-SAY
# aux: V

v = None

if _.zil_sdk.zstate_get("ZORK-NUMBER") == 2:
    if _.zil_sdk.zstate_get("SPELL-USED") or _.zil_sdk.zstate_get("WAND-ON"):
        _.zil_sdk.perform(_.zil_sdk.zstate_get("V?INCANT"), None, None)
        return True
elif _.zil_sdk.zstate_get("ZORK-NUMBER") == 3:
    if (
        _.zil_sdk.flag(_.get_property("front_door"), "touchbit")
        and _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-LEXV"), context.player) == _.zil_sdk.zstate_get("W?FROTZ")
        and _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-LEXV"), context.player + 2) == _.zil_sdk.zstate_get("W?OZMOO")
    ):
        _.zil_sdk.zstate_set("P-CONT", None)
        if context.player.location == _.zil_sdk.zstate_get("MSTAIRS"):
            print()
            _.zil_sdk.goto(_.get_property("front_door"))
        else:
            print("Nothing happens.")
        return True
else:
    if not context.player:
        print("Say what?")
        return True
_.zil_sdk.zstate_set("QUOTE-FLAG", None)
if v := _.zork_thing.invoke_verb("find-in", context.player.location, _.zil_sdk.zstate_get("ACTORBIT")):
    print("You must address the " + _.zil_sdk.desc(v) + " directly.")
    _.zil_sdk.zstate_set("P-CONT", None)
elif not _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-LEXV"), context.player) == _.zil_sdk.zstate_get("W?HELLO"):
    _.zil_sdk.zstate_set("P-CONT", None)
    print("Talking to yourself is a sign of impending mental collapse.")
return True
