#!moo verb v-save --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import lookup
# ZIL routine: V-SAVE

if lookup("save"):
    return print("Ok.")
else:
    return print("Failed.")
