#!moo verb v-send --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-SEND

if _.zil_sdk.flag(context.parser.get_dobj(), "actorbit"):
    return print("Why would you send for the " + _.zil_sdk.desc(context.parser.get_dobj()) + "?")
else:
    return print("That doesn't make sends.")
