#!moo verb v-sspray --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-SSPRAY

return _.zil_sdk.perform(_.zil_sdk.zstate_get("V?SPRAY"), context.parser.get_iobj(), context.parser.get_dobj())
