#!moo verb v-stand --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-STAND

if _.zil_sdk.flag(context.player.location, "vehicle"):
    _.zil_sdk.perform(_.zil_sdk.zstate_get("V?DISEMBARK"), context.player.location, None)
    return True
else:
    return print("You are already standing, I think.")
