#!moo verb v-stab --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-STAB
# aux: W

w = None

if w := _.zork_thing.invoke_verb("find-weapon", context.player):
    _.zil_sdk.perform(_.zil_sdk.zstate_get("V?ATTACK"), context.parser.get_dobj(), w)
    return True
else:
    return print("No doubt you propose to stab the " + _.zil_sdk.desc(context.parser.get_dobj()) + " with your pinky?")
