#!moo verb v-swim --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-SWIM

if context.player.location in (_.zil_sdk.zstate_get("ON-LAKE"), _.zil_sdk.zstate_get("IN-LAKE")):
    return print("What do you think you're doing?")
elif _.zork_thing.invoke_verb("null-f"):
    return False
else:
    return print("Go jump in a lake!")
