#!moo verb v-take --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-TAKE

if _.zork_thing.invoke_verb("itake") == True:
    if _.zil_sdk.flag(context.parser.get_dobj(), "wearbit"):
        return print("You are now wearing the " + _.zil_sdk.desc(context.parser.get_dobj()) + ".")
    else:
        return print("Taken.")
