#!moo verb v-tell --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-TELL

if _.zil_sdk.flag(context.parser.get_dobj(), "actorbit"):
    if context.player:
        _.zil_sdk.zstate_set("WINNER", context.parser.get_dobj())
        return _.zil_sdk.zstate_set("HERE", context.player.location)
    else:
        return print(
            "The "
            + _.zil_sdk.desc(context.parser.get_dobj())
            + " pauses for a moment, perhaps thinking that you should reread\nthe manual."
        )
else:
    print("You can't talk to the " + _.zil_sdk.desc(context.parser.get_dobj()) + "!")
    _.zil_sdk.zstate_set("QUOTE-FLAG", None)
    _.zil_sdk.zstate_set("P-CONT", None)
    # ZIL: <RFATAL ...>
    return 2
