#!moo verb v-through --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-THROUGH
# params: OBJ
# aux: M

obj = args[0] if len(args) > 0 else None
m = None

_.zil_sdk.zstate_get("#DECL")
if _.zil_sdk.flag(context.parser.get_dobj(), "is_door") and (
    m := _.zork_thing.invoke_verb("other-side", context.parser.get_dobj())
):
    _.zil_sdk.walk(m)
    return True
elif not obj and _.zil_sdk.flag(context.parser.get_dobj(), "vehicle"):
    _.zil_sdk.perform(_.zil_sdk.zstate_get("V?BOARD"), context.parser.get_dobj(), None)
    return True
elif obj or not _.zil_sdk.flag(context.parser.get_dobj(), "takeable"):
    if _.zil_sdk.zstate_get("ZORK-NUMBER") == 2:
        if _.zil_sdk.zstate_get("SCOL-ROOM") and obj or context.parser.get_dobj() == _.zil_sdk.zstate_get("CURTAIN"):
            # ZIL: <SCOL-GO ...>
            scol_go(obj)
            return True
        elif (
            context.player.location == _.zil_sdk.zstate_get("DEPOSITORY")
            and context.parser.get_dobj() == _.zil_sdk.zstate_get("SNWL")
            and _.zil_sdk.zstate_get("SCOL-ROOM")
        ):
            # ZIL: <SCOL-GO ...>
            scol_go(obj)
            return True
        elif context.player.location == _.zil_sdk.zstate_get(
            "SCOL-ACTIVE"
        ) and context.parser.get_dobj() == _.zil_sdk.table_get((m := get_wall(context.player.location)), 1):
            _.zil_sdk.zstate_set("SCOL-ROOM", _.zil_sdk.table_get(m, 2))
            _.zil_sdk.zstate_set("PRSO", context.parser.get_dobj().get_property("size"))
            if obj:
                # ZIL: <SCOL-OBJ ...>
                scol_obj(obj, 0, _.zil_sdk.zstate_get("DEPOSITORY"))
            else:
                # ZIL: <SCOL-THROUGH ...>
                scol_through(0, _.zil_sdk.zstate_get("DEPOSITORY"))
            return True
        elif context.parser.get_dobj() == _.zil_sdk.zstate_get("CURTAIN"):
            print("You can't go more than part way through the curtain.")
            return True
    else:
        # ZIL: <NULL-F ...>
        _.zork_thing.invoke_verb("null-f")
    return print(
        "You hit your head against the " + _.zil_sdk.desc(context.parser.get_dobj()) + " as you attempt this feat."
    )
elif context.parser.get_dobj().location == context.player:
    return print("That would involve quite a contortion!")
else:
    return print(_.zil_sdk.pick(_.zil_sdk.zstate_get("YUKS")))
