#!moo verb v-unscript --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: V-UNSCRIPT

print("Here ends a transcript of interaction with")
# ZIL: <V-VERSION ...>
_.zork_thing.invoke_verb("v-version")
# ZIL: <PUT ...>
_.zil_sdk.table_put(0, 8, band(_.zil_sdk.table_get(0, 8), -2))
return True
