#!moo verb v-version --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: V-VERSION
# aux: CNT

cnt = 17

if _.zil_sdk.zstate_get("ZORK-NUMBER") == 1:
    print(
        "ZORK I: The Great Underground Empire\n\nInfocom interactive fiction - a fantasy story\n\nCopyright (c) 1981, 1982, 1983, 1984, 1985, 1986",
        end="",
    )
elif _.zil_sdk.zstate_get("ZORK-NUMBER") == 2:
    print(
        "ZORK II: The Wizard of Frobozz\n\nInfocom interactive fiction - a fantasy story\n\nCopyright (c) 1981, 1982, 1983, 1986",
        end="",
    )
elif _.zil_sdk.zstate_get("ZORK-NUMBER") == 3:
    print(
        "ZORK III: The Dungeon Master\n\nInfocom interactive fiction - a fantasy story\n\nCopyright 1982, 1983, 1984, 1986",
        end="",
    )
print(" Infocom, Inc. All rights reserved.")
print("ZORK is a registered trademark of Infocom, Inc.\n\nRelease ", end="")
print(str(band(_.zil_sdk.table_get(0, 1), _.zil_sdk.zstate_get("*3777*"))), end="")
print(" / Serial number ", end="")
while True:
    if (cnt := cnt + 1) > 23:
        break
    else:
        print(chr(_.zil_sdk.table_get(0, cnt)), end="")
return print()
