#!moo verb v-wait --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: V-WAIT
# params: NUM

num = args[0] if len(args) > 0 else 3

print("Time passes...")
while True:
    if (num := num - 1) < 0:
        break
    elif _.zork_thing.invoke_verb("clocker"):
        break
return _.zil_sdk.zstate_set("CLOCK-WAIT", True)
