#!moo verb v-wear --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: V-WEAR

if not _.zil_sdk.flag(context.parser.get_dobj(), "wearbit"):
    return print("You can't wear the " + _.zil_sdk.desc(context.parser.get_dobj()) + ".")
else:
    _.zil_sdk.perform(_.zil_sdk.zstate_get("V?TAKE"), context.parser.get_dobj(), None)
    return True
