#!moo verb enterfunc --on $clearing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL: FOREST-ROOM / M-ENTER

_.zil_sdk.queue("i-forest-room", -1)
