#!moo verb climb-foo climb-up --on $clearing --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: FOREST-ROOM
# params: RARG

rarg = args[0] if len(args) > 0 else None

if rarg == "M-ENTER":
    return _.zil_sdk.queue("i-forest-room", -1)
elif rarg == "M-BEG":
    if player_verb in ["climb-foo", "climb-up"] and context.parser.get_dobj() == _.get_property("tree"):
        return _.zil_sdk.walk(_.zil_sdk.zstate_get("P?UP"))
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
