#!moo verb do_fight --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

import random
from moo.sdk import context
# ZIL routine: DO-FIGHT
# params: LEN
# aux: CNT, RES, O, OO, OUT

player = context.player
len_v = args[0] if len(args) > 0 else None
cnt = 0
res = 0
o = 0
oo = 0
out = 0

while True:
    cnt = 0
    while True:
        cnt = cnt + 1
        if cnt == len_v:
            res = True
            return True
        oo = _.table_get(player.zstate_get("VILLAINS"), cnt)
        o = _.table_get(oo, player.zstate_get("V-VILLAIN"))
        if not o.flag("hostile"):
            pass
        elif apply(o.getp("action"), player.zstate_get("F-BUSY?")):
            pass
        elif not (res := _.zork_thing.villain_blow(oo, out)):
            res = None
            break
        elif res == player.zstate_get("UNCONSCIOUS"):
            out = 1 + random.randint(1, 3)
    if res:
        if not out:
            break
        else:
            out = out - 1
            if out == 0:
                break
    else:
        break
