#!moo verb fight_strength --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: FIGHT-STRENGTH
# params: ADJUST?
# aux: S

player = context.player
adjust_p = args[0] if len(args) > 0 else True
s = 0

s = player.zstate_get("STRENGTH-MIN") + _.score_update(
    score_max(player.zstate_get("STRENGTH-MAX") - player.zstate_get("STRENGTH-MIN"))
)
if adjust_p:
    return s + player.getp("strength")
else:
    return s
