#!moo verb rob_maze --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

import random
from moo.sdk import lookup
# ZIL routine: ROB-MAZE
# params: RM
# aux: X, N

rm = args[0] if len(args) > 0 else None
x = 0
n = 0

x = rm.contents.first()
while True:
    if not x:
        return False
    n = _.next_sibling(x)
    if x.flag("takeable") and not x.flag("invisible") and random.randint(1, 100) <= 40:
        print(
            'You hear, off in the distance, someone saying "My, I wonder what\nthis fine '
            + x.desc()
            + ' is doing here."'
        )
        if random.randint(1, 100) <= 60:
            x.moveto(lookup("thief"))
            x.set_flag("touchbit", True)
            x.set_flag("invisible", True)
        break
    x = n
