# Generated by Django 5.0.14 on 2026-04-10 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_object_obvious_default_false"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to="core.object",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("read", models.BooleanField(db_index=True, default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(db_index=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="recipients", to="core.message"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="received_messages", to="core.object"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["sender", "sent_at"], name="core_messag_sender__5afc37_idx"),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(fields=["recipient", "deleted", "sent_at"], name="core_messag_recipie_f1202e_idx"),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(fields=["recipient", "read", "deleted"], name="core_messag_recipie_176c5e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="messagerecipient",
            unique_together={("message", "recipient")},
        ),
    ]
