# Generated by Django 5.0.14 on 2026-04-14 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='placement_prep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='placement_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_objects', to='core.object'),
        ),
    ]
