# Generated by Django 5.0.14 on 2026-05-02 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_object_placement_prep_object_placement_target"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="site",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="sites.site"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="site",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="sites.site"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("user", "site")},
        ),
        migrations.AddConstraint(
            model_name="object",
            constraint=models.UniqueConstraint(
                condition=models.Q(("unique_name", True)), fields=("name", "site"), name="unique_name_per_site"
            ),
        ),
    ]
