# Generated by Django 5.0.14 on 2026-06-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_object_initialized"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="registered_identity",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="status",
            field=models.CharField(
                choices=[("active", "active"), ("guest", "guest"), ("suspended", "suspended"), ("banned", "banned")],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="suspended_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["status"], name="player_status_idx"),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["registered_identity"], name="player_identity_idx"),
        ),
    ]
