# Generated by Django 5.0.14 on 2026-06-14 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_player_registered_identity_player_status_and_more"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "create"),
                            ("recycle", "recycle"),
                            ("destroy", "destroy"),
                            ("restore", "restore"),
                            ("owner_change", "owner_change"),
                            ("permission_change", "permission_change"),
                            ("suspend", "suspend"),
                            ("unsuspend", "unsuspend"),
                            ("ban", "ban"),
                        ],
                        max_length=24,
                    ),
                ),
                ("target_id", models.IntegerField(blank=True, null=True)),
                ("target_repr", models.CharField(blank=True, default="", max_length=255)),
                ("detail", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.player"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="sites.site"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["-timestamp"], name="audit_timestamp_idx"),
                    models.Index(fields=["actor", "-timestamp"], name="audit_actor_idx"),
                    models.Index(fields=["action", "-timestamp"], name="audit_action_idx"),
                ],
            },
        ),
    ]
