# Generated by Django 5.0.14 on 2026-06-14 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_blacklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("namespace", models.CharField(max_length=128)),
                ("key", models.CharField(max_length=255)),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="external_keys", to="core.object"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="externalkey",
            constraint=models.UniqueConstraint(fields=("namespace", "key"), name="externalkey_namespace_key_unique"),
        ),
    ]
