# Generated by Django 5.0.14 on 2026-06-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_externalkey_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="recycled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="object",
            name="recycled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
