# Generated by Django 5.0.14 on 2026-06-14 21:00

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_object_recycled_object_recycled_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                fields=["registered_identity", "site"],
                condition=Q(registered_identity__isnull=False),
                name="player_unique_identity_per_site",
            ),
        ),
    ]
