#!moo verb fill inflate insert place plug put put-on --on $punctured_boat --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: DBOAT-FUNCTION

if player_verb in ["put", "place", "insert", "put-on"] and context.parser.get_dobj() == _.get_property("putty"):
    # ZIL: <FIX-BOAT ...>
    return _.zork_thing.invoke_verb("fix-boat")
elif player_verb in ["inflate", "fill"]:
    return print("No chance. Some moron punctured it.")
elif player_verb in ["plug"]:
    if context.parser.get_iobj() == _.get_property("putty"):
        # ZIL: <FIX-BOAT ...>
        return _.zork_thing.invoke_verb("fix-boat")
    else:
        # ZIL: <WITH-TELL ...>
        return _.zork_thing.invoke_verb("with-tell", context.parser.get_iobj())
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
