#!moo verb dead-function --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context, lookup
# ZIL routine: DEAD-FUNCTION
# params: FOO

foo = args[0] if len(args) > 0 else None

if player_verb in ["go", "walk", "move"]:
    if context.player.location == _.get_property("timber_room") and context.parser.get_dobj() == _.zil_sdk.zstate_get(
        "P?WEST"
    ):
        return print("You cannot enter in your condition.")
elif player_verb in ["brief", "verbose", "superbrief", "version", "save", "restore", "quit", "q", "restart"]:
    pass
elif player_verb in [
    "attack",
    "kill",
    "hit",
    "fight",
    "stab",
    "cut",
    "slice",
    "mung",
    "destroy",
    "break",
    "smash",
    "crack",
    "alarm",
    "swing",
]:
    return print("All such attacks are vain in your condition.")
elif player_verb in [
    "open",
    "close",
    "shut",
    "eat",
    "drink",
    "inflate",
    "deflate",
    "turn",
    "rotate",
    "burn",
    "light",
    "tie",
    "attach",
    "fasten",
    "untie",
    "rub",
]:
    return print("Even such an action is beyond your capabilities.")
elif player_verb in ["wait", "z"]:
    return print("Might as well. You've got an eternity.")
elif player_verb in ["lamp-on"]:
    return print("You need no light to guide you.")
elif player_verb in ["score"]:
    return print("You're dead! How can you think of your score?")
elif player_verb in ["take", "get", "pick", "rub"]:
    return print("Your hand passes through its object.")
elif player_verb in ["drop", "throw", "toss", "inventory", "i"]:
    return print("You have no possessions.")
elif player_verb in ["diagnose"]:
    return print("You are dead.")
elif player_verb in ["look", "l"]:
    print("The room looks strange and unearthly", end="")
    if not context.player.location.contents.first():
        print(".", end="")
    else:
        print(" and objects appear indistinct.", end="")
    print()
    if not _.zil_sdk.flag(context.player.location, "onbit"):
        print("Although there is no light, the room seems dimly illuminated.")
    return print()
elif player_verb in ["pray"]:
    if context.player.location == _.get_property("south_temple"):
        _.zil_sdk.set_flag(_.get_property("lamp"), "invisible", False)
        context.player.set_property("action", 0)
        _.zil_sdk.zstate_set("ALWAYS-LIT", None)
        _.zil_sdk.zstate_set("DEAD", None)
        if lookup("troll").location == _.get_property("troll_room"):
            _.zil_sdk.zstate_set("TROLL-FLAG", None)
        print(
            "From the distance the sound of a lone trumpet is heard. The room\nbecomes very bright and you feel disembodied. In a moment, the\nbrightness fades and you find yourself rising as if from a long\nsleep, deep in the woods. In the distance you can faintly hear a\nsongbird and the sounds of the forest."
        )
        return _.zil_sdk.goto(_.get_property("forest_1"))
    else:
        return print("Your prayers are not heard.")
else:
    print("You can't even do that.")
    _.zil_sdk.zstate_set("P-CONT", None)
    # ZIL: <RFATAL ...>
    return 2
