#!moo verb find get lower pick raise read take where --on $granite_wall --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: GRANITE-WALL-F

if context.player.location == _.get_property("north_temple"):
    if player_verb in ["find", "where"]:
        return print("The west wall is solid granite here.")
    elif player_verb in ["take", "get", "pick", "raise", "lower"]:
        return print("It's solid granite.")
elif context.player.location == _.get_property("treasure_room"):
    if player_verb in ["find", "where"]:
        return print("The east wall is solid granite here.")
    elif player_verb in ["take", "get", "pick", "raise", "lower"]:
        return print("It's solid granite.")
elif context.player.location == _.get_property("slide_room"):
    if player_verb in ["find", "where", "read"]:
        return print('It only SAYS "Granite Wall".')
    else:
        return print("The wall isn't granite.")
else:
    return print("There is no granite wall here.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
