#!moo verb dig insert place put put-on --on $ground --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: GROUND-FUNCTION

if player_verb in ["put", "place", "insert", "put-on"] and context.parser.get_iobj() == _.get_property("ground"):
    _.zil_sdk.perform(_.zil_sdk.zstate_get("V?DROP"), context.parser.get_dobj(), None)
    return True
elif context.player.location == _.get_property("sandy_cave"):
    # ZIL: <SAND-FUNCTION ...>
    return _.zork_thing.invoke_verb("sand-function")
elif player_verb in ["dig"]:
    return print("The ground is too hard for digging here.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
