#!moo verb gunk-function --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: GUNK-FUNCTION

_.zil_sdk.remove(_.get_property("gunk"))
return print("The slag was rather insubstantial, and crumbles into dust at your touch.")
