#!moo verb get pick pour-on ring rub take --on $hot_bell --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: HOT-BELL-F

if player_verb in ["take", "get", "pick"]:
    return print("The bell is very hot and cannot be taken.")
elif player_verb in ["rub"] or player_verb in ["ring"] and context.parser.get_iobj():
    if _.zil_sdk.flag(context.parser.get_iobj(), "flammable"):
        print("The " + _.zil_sdk.desc(context.parser.get_iobj()) + " burns and is consumed.")
        return _.zil_sdk.remove(context.parser.get_iobj())
    elif context.parser.get_iobj() == _.get_property("hands"):
        return print("The bell is too hot to touch.")
    else:
        return print("The heat from the bell is too intense.")
elif player_verb in ["pour-on"]:
    _.zil_sdk.remove(context.parser.get_dobj())
    print("The water cools the bell and is evaporated.")
    # ZIL: <QUEUE ...>
    _.zork_thing.invoke_verb("queue", _.zork_thing.invoke_verb("i-xbh"), 0)
    # ZIL: <I-XBH ...>
    return _.zork_thing.invoke_verb("i-xbh")
elif player_verb in ["ring"]:
    return print("The bell is too hot to reach.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
