#!moo verb not-here-object-f --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: NOT-HERE-OBJECT-F
# aux: TBL, PRSO?, OBJ

tbl = None
prso_p = True
obj = None

if context.parser.get_dobj() == _.get_property("not_here_object") and context.parser.get_iobj() == _.get_property(
    "not_here_object"
):
    print("Those things aren't here!")
    return True
elif context.parser.get_dobj() == _.get_property("not_here_object"):
    tbl = _.zil_sdk.zstate_get("P-PRSO")
else:
    tbl = _.zil_sdk.zstate_get("P-PRSI")
    prso_p = None
_.zil_sdk.zstate_set("P-CONT", None)
_.zil_sdk.zstate_set("QUOTE-FLAG", None)
if context.player == context.player:
    print("You can't see any ", end="")
    # ZIL: <NOT-HERE-PRINT ...>
    _.zork_thing.invoke_verb("not-here-print", prso_p)
    print(" here!")
else:
    print("The " + _.zil_sdk.desc(context.player) + " seems confused. \"I don't see any ", end="")
    # ZIL: <NOT-HERE-PRINT ...>
    _.zork_thing.invoke_verb("not-here-print", prso_p)
    print(' here!"')
return True
