#!moo verb null-f --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: NULL-F
# params: A1, A2

a1 = args[0] if len(args) > 0 else None
a2 = args[1] if len(args) > 1 else None

return False
