#!moo verb attack board break crack cut deflate destroy drop fight fill go hit inflate insert kill launch move mung place put slice smash stab walk --on $inflated_boat --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: RBOAT-FUNCTION
# params: RARG
# aux: TMP

rarg = args[0] if len(args) > 0 else None
tmp = None

if rarg in ("M-ENTER", "M-END", "M-LOOK"):
    pass
elif rarg == "M-BEG":
    if player_verb in ["go", "walk", "move"]:
        if context.parser.get_dobj() in (
            _.zil_sdk.zstate_get("P?LAND"),
            _.zil_sdk.zstate_get("P?EAST"),
            _.zil_sdk.zstate_get("P?WEST"),
        ):
            return False
        elif context.player.location == _.get_property("reservoir") and context.parser.get_dobj() in (
            _.zil_sdk.zstate_get("P?NORTH"),
            _.zil_sdk.zstate_get("P?SOUTH"),
        ):
            return False
        elif context.player.location == _.get_property(
            "in_stream"
        ) and context.parser.get_dobj() == _.zil_sdk.zstate_get("P?SOUTH"):
            return False
        else:
            print("Read the label for the boat's instructions.")
            return True
    elif player_verb in ["launch"]:
        if context.player.location in (
            _.get_property("river_1"),
            _.get_property("river_2"),
            _.get_property("river_3"),
        ) or context.player.location in (
            _.get_property("river_4"),
            _.get_property("reservoir"),
            _.get_property("in_stream"),
        ):
            print("You are on the ", end="")
            if context.player.location == _.get_property("reservoir"):
                print("reservoir", end="")
            elif context.player.location == _.get_property("in_stream"):
                print("stream", end="")
            else:
                print("river", end="")
            return print(", or have you forgotten?")
        elif (tmp := _.zork_thing.invoke_verb("go-next", _.zil_sdk.zstate_get("RIVER-LAUNCH"))) == 1:
            _.zil_sdk.queue(
                "i-river",
                _.zork_thing.invoke_verb("lkp", context.player.location, _.zil_sdk.zstate_get("RIVER-SPEEDS")),
            )
            return True
        elif not tmp == 2:
            print("You can't launch it here.")
            return True
        else:
            return True
    elif (
        player_verb in ["drop"]
        and _.zil_sdk.flag(context.parser.get_dobj(), "weapon")
        or player_verb in ["put", "place", "insert"]
        and _.zil_sdk.flag(context.parser.get_dobj(), "weapon")
        and context.parser.get_iobj() == _.get_property("inflated_boat")
        or player_verb
        in ["attack", "kill", "hit", "fight", "stab", "cut", "slice", "mung", "destroy", "break", "smash", "crack"]
        and _.zil_sdk.flag(context.parser.get_iobj(), "weapon")
    ):
        _.zil_sdk.remove(_.get_property("inflated_boat"))
        _.zil_sdk.move(_.get_property("punctured_boat"), context.player.location)
        # ZIL: <ROB ...>
        _.zork_thing.invoke_verb("rob", _.get_property("inflated_boat"), context.player.location)
        _.zil_sdk.move(context.player, context.player.location)
        print("It seems that the ", end="")
        if player_verb in ["drop", "put", "place", "insert"]:
            print(_.zil_sdk.desc(context.parser.get_dobj()), end="")
        else:
            print(_.zil_sdk.desc(context.parser.get_iobj()), end="")
        print(
            " didn't agree with the boat, as evidenced\nby the loud hissing noise issuing therefrom. With a pathetic sputter, the\nboat deflates, leaving you without."
        )
        if _.zil_sdk.flag(context.player.location, "nonlandbit"):
            print()
            if context.player.location in (_.get_property("reservoir"), _.get_property("in_stream")):
                _.zil_sdk.jigs_up("Another pathetic sputter, this time from you, heralds your drowning.")
            else:
                _.zil_sdk.jigs_up(
                    "In other words, fighting the fierce currents of the Frigid River. You\nmanage to hold your own for a bit, but then you are carried over a\nwaterfall and into some nasty rocks. Ouch!"
                )
        return True
    elif player_verb in ["launch"]:
        return print("You're not in the boat!")
elif player_verb in ["board"]:
    if (
        _.get_property("sceptre").location == context.player
        or _.get_property("knife").location == context.player
        or _.get_property("sword").location == context.player
        or _.get_property("rusty_knife").location == context.player
        or _.get_property("axe").location == context.player
        or _.get_property("stiletto").location == context.player
    ):
        print(
            "Oops! Something sharp seems to have slipped and punctured the boat.\nThe boat deflates to the sounds of hissing, sputtering, and cursing."
        )
        _.zil_sdk.remove(_.get_property("inflated_boat"))
        _.zil_sdk.move(_.get_property("punctured_boat"), context.player.location)
        # ZIL: <THIS-IS-IT ...>
        _.zork_thing.invoke_verb("this-is-it", _.get_property("punctured_boat"))
        return True
elif player_verb in ["inflate", "fill"]:
    return print("Inflating it further would probably burst it.")
elif player_verb in ["deflate"]:
    if context.player.location == _.get_property("inflated_boat"):
        return print("You can't deflate the boat while you're in it.")
    elif not _.get_property("inflated_boat").location == context.player.location:
        return print("The boat must be on the ground to be deflated.")
    else:
        print("The boat deflates.")
        _.zil_sdk.zstate_set("DEFLATE", True)
        _.zil_sdk.remove(_.get_property("inflated_boat"))
        _.zil_sdk.move(_.get_property("inflatable_boat"), context.player.location)
        # ZIL: <THIS-IS-IT ...>
        return _.zork_thing.invoke_verb("this-is-it", _.get_property("inflatable_boat"))
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
