#!moo verb describe examine hello hi tell what x --on $sailor --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: SAILOR-FCN

if player_verb in ["tell"]:
    _.zil_sdk.zstate_set("P-CONT", None)
    _.zil_sdk.zstate_set("QUOTE-FLAG", None)
    return print("You can't talk to the sailor that way.")
elif player_verb in ["examine", "x", "describe", "what"]:
    if _.zil_sdk.zstate_get("ZORK-NUMBER") == 3:
        if not _.zil_sdk.flag(_.zil_sdk.zstate_get("VIKING-SHIP"), "invisible"):
            print("He looks like a sailor.")
            return True
    else:
        True
    return print("There is no sailor to be seen.")
elif player_verb in ["hello", "hi"]:
    _.zil_sdk.zstate_set("HS", _.zil_sdk.zstate_get("HS") + 1)
    if _.zil_sdk.zstate_get("ZORK-NUMBER") == 3:
        if not _.zil_sdk.flag(_.zil_sdk.zstate_get("VIKING-SHIP"), "invisible"):
            print(
                'The seaman looks up and maneuvers the boat toward shore. He cries out "I\nhave waited three ages for someone to say those words and save me from\nsailing this endless ocean. Please accept this gift. You may find it\nuseful!" He throws something which falls near you in the sand, then sails\noff toward the west, singing a lively, but somewhat uncouth, sailor song.'
            )
            _.zil_sdk.set_flag(_.zil_sdk.zstate_get("VIKING-SHIP"), "invisible", True)
            return _.zil_sdk.move(_.zil_sdk.zstate_get("VIAL"), context.player.location)
        elif context.player.location == _.zil_sdk.zstate_get("FLATHEAD-OCEAN"):
            if _.zil_sdk.zstate_get("SHIP-GONE"):
                return print("Nothing happens anymore.")
            else:
                return print("Nothing happens yet.")
        else:
            return print("Nothing happens here.")
    else:
        if _.zil_sdk.zstate_get("HS") % 20 == 0:
            return print("You seem to be repeating yourself.")
        elif _.zil_sdk.zstate_get("HS") % 10 == 0:
            return print("I think that phrase is getting a bit worn out.")
        else:
            return print("Nothing happens here.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
