#!moo verb brush clean --on $teeth --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: TEETH-F

if player_verb in ["brush", "clean"] and context.parser.get_dobj() == _.get_property("teeth"):
    if context.parser.get_iobj() == _.get_property("putty") and context.parser.get_iobj().location == context.player:
        return _.zil_sdk.jigs_up(
            "Well, you seem to have been brushing your teeth with some sort of\nglue. As a result, your mouth gets glued together (with your nose)\nand you die of respiratory failure."
        )
    elif not context.parser.get_iobj():
        return print("Dental hygiene is highly recommended, but I'm not sure what you want\nto brush them with.")
    else:
        return print("A nice idea, but with a " + _.zil_sdk.desc(context.parser.get_iobj()) + "?")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
