#!moo verb up-chimney-function --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: UP-CHIMNEY-FUNCTION
# aux: F

f = None

if not (f := context.player.contents.first()):
    print("Going up empty-handed is a bad idea.")
    return False
elif (
    not (f := _.zil_sdk.next_sibling(f))
    or not _.zil_sdk.next_sibling(f)
    and _.get_property("lamp").location == context.player
):
    if not _.zil_sdk.flag(_.get_property("trap_door"), "open"):
        _.zil_sdk.set_flag(_.get_property("trap_door"), "touchbit", False)
    return _.get_property("kitchen")
else:
    print("You can't get up there with what you're carrying.")
    return False
