#!moo verb weapon-function --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: WEAPON-FUNCTION
# params: W, V

w = args[0] if len(args) > 0 else None
v = args[1] if len(args) > 1 else None

if not v.location == context.player.location:
    return False
elif player_verb in ["take", "get", "pick"]:
    if w.location == v:
        print("The " + _.zil_sdk.desc(v) + " swings it out of your reach.")
    else:
        print("The " + _.zil_sdk.desc(w) + " seems white-hot. You can't hold on to it.")
    return True
