#!moo verb describe examine find what where x --on $zorkmid --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: ZORKMID-FUNCTION

if player_verb in ["examine", "x", "describe", "what"]:
    return print("The zorkmid is the unit of currency of the Great Underground Empire.")
elif player_verb in ["find", "where"]:
    return print("The best way to find zorkmids is to go out and look for them.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
