#!moo verb do-fight --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
# ZIL routine: DO-FIGHT
# params: LEN
# aux: CNT, RES, O, OO, OUT

len_v = args[0] if len(args) > 0 else None
cnt = None
res = None
o = None
oo = None
out = None

while True:
    cnt = 0
    while True:
        cnt = cnt + 1
        if cnt == len_v:
            res = True
            return True
        oo = _.zil_sdk.table_get(_.zil_sdk.zstate_get("VILLAINS"), cnt)
        o = _.zil_sdk.table_get(oo, _.zil_sdk.zstate_get("V-VILLAIN"))
        if not _.zil_sdk.flag(o, "hostile"):
            pass
        elif apply(_.zil_sdk.getp(o, "action"), _.zil_sdk.zstate_get("F-BUSY?")):
            pass
        elif not (res := _.zork_thing.invoke_verb("villain-blow", oo, out)):
            res = None
            break
        elif res == _.zil_sdk.zstate_get("UNCONSCIOUS"):
            out = 1 + random.randint(1, 3)
    if res:
        if not out:
            break
        else:
            out = out - 1
            if out == 0:
                break
    else:
        break
