#!moo verb otval-frob --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: OTVAL-FROB
# params: O
# aux: F, SCORE

o = args[0] if len(args) > 0 else _.get_property("trophy_case")
f = None
score = 0

f = o.contents.first()
while True:
    if not f:
        return score
    score = score + f.get_property("tvalue")
    if f.contents.first():
        # ZIL: <OTVAL-FROB ...>
        _.zork_thing.invoke_verb("otval-frob", f)
    f = _.zil_sdk.next_sibling(f)
