#!moo verb rob-maze --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
from moo.sdk import lookup
# ZIL routine: ROB-MAZE
# params: RM
# aux: X, N

rm = args[0] if len(args) > 0 else None
x = None
n = None

x = rm.contents.first()
while True:
    if not x:
        return False
    n = _.zil_sdk.next_sibling(x)
    if _.zil_sdk.flag(x, "takeable") and not _.zil_sdk.flag(x, "invisible") and random.randint(1, 100) <= 40:
        print(
            'You hear, off in the distance, someone saying "My, I wonder what\nthis fine '
            + _.zil_sdk.desc(x)
            + ' is doing here."'
        )
        if random.randint(1, 100) <= 60:
            _.zil_sdk.move(x, lookup("thief"))
            _.zil_sdk.set_flag(x, "touchbit", True)
            _.zil_sdk.set_flag(x, "invisible", True)
        break
    x = n
