#!moo verb steal-junk --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
from moo.sdk import context, lookup
# ZIL routine: STEAL-JUNK
# params: RM
# aux: X, N

rm = args[0] if len(args) > 0 else None
x = None
n = None

x = rm.contents.first()
while True:
    if not x:
        return False
    n = _.zil_sdk.next_sibling(x)
    if (
        x.get_property("tvalue") == 0
        and _.zil_sdk.flag(x, "takeable")
        and not _.zil_sdk.flag(x, "sacred")
        and not _.zil_sdk.flag(x, "invisible")
        and x == _.get_property("stiletto")
        or random.randint(1, 100) <= 10
    ):
        _.zil_sdk.move(x, lookup("thief"))
        _.zil_sdk.set_flag(x, "touchbit", True)
        _.zil_sdk.set_flag(x, "invisible", True)
        if x == _.get_property("rope"):
            _.zil_sdk.zstate_set("DOME-FLAG", None)
        if rm == context.player.location:
            print("You suddenly notice that the " + _.zil_sdk.desc(x) + " vanished.")
            return True
        else:
            return False
    x = n
