#!moo verb thief-vs-adventurer --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
from moo.sdk import context, lookup
# ZIL routine: THIEF-VS-ADVENTURER
# params: HERE?
# aux: ROBBED?, WINNER-ROBBED?

here_p = args[0] if len(args) > 0 else None
robbed_p = None
winner_robbed_p = None

if not _.zil_sdk.zstate_get("DEAD") and context.player.location == _.get_property("treasure_room"):
    pass
elif not _.zil_sdk.zstate_get("THIEF-HERE"):
    if not _.zil_sdk.zstate_get("DEAD") and not here_p and random.randint(1, 100) <= 30:
        if _.get_property("stiletto").location == lookup("thief"):
            _.zil_sdk.set_flag(lookup("thief"), "invisible", False)
            print(
                "Someone carrying a large bag is casually leaning against one of the\nwalls here. He does not speak, but it is clear from his aspect that\nthe bag will be taken only over his dead body."
            )
            _.zil_sdk.zstate_set("THIEF-HERE", True)
            return True
    elif (
        here_p
        and _.zil_sdk.flag(lookup("thief"), "hostile")
        and not _.zork_thing.invoke_verb("winning?", lookup("thief"))
    ):
        print(
            "Your opponent, determining discretion to be the better part of\nvalor, decides to terminate this little contretemps. With a rueful\nnod of his head, he steps backward into the gloom and disappears."
        )
        _.zil_sdk.set_flag(lookup("thief"), "invisible", True)
        _.zil_sdk.set_flag(lookup("thief"), "hostile", False)
        # ZIL: <RECOVER-STILETTO ...>
        _.zork_thing.invoke_verb("recover-stiletto")
        return True
    elif here_p and _.zil_sdk.flag(lookup("thief"), "hostile") and random.randint(1, 100) <= 90:
        return False
    elif here_p and random.randint(1, 100) <= 30:
        print("The holder of the large bag just left, looking disgusted.\nFortunately, he took nothing.")
        _.zil_sdk.set_flag(lookup("thief"), "invisible", True)
        # ZIL: <RECOVER-STILETTO ...>
        _.zork_thing.invoke_verb("recover-stiletto")
        return True
    elif random.randint(1, 100) <= 70:
        return False
    elif not _.zil_sdk.zstate_get("DEAD"):
        if _.zork_thing.invoke_verb("rob", context.player.location, lookup("thief"), 100):
            robbed_p = context.player.location
        elif _.zork_thing.invoke_verb("rob", context.player, lookup("thief")):
            robbed_p = context.player
        _.zil_sdk.zstate_set("THIEF-HERE", True)
        if robbed_p and not here_p:
            print(
                "A seedy-looking individual with a large bag just wandered through\nthe room. On the way through, he quietly abstracted some valuables from ",
                end="",
            )
            if robbed_p == context.player.location:
                print("the room", end="")
            else:
                print("your possession", end="")
            print(', mumbling something about\n"Doing unto others before..."')
            # ZIL: <STOLE-LIGHT? ...>
            stole_light_p()
        elif here_p:
            # ZIL: <RECOVER-STILETTO ...>
            _.zork_thing.invoke_verb("recover-stiletto")
            if robbed_p:
                print("The thief just left, still carrying his large bag. You may\nnot have noticed that he ", end="")
                if robbed_p == context.player:
                    print("robbed you blind first.", end="")
                else:
                    print("appropriated the valuables in the room.", end="")
                print()
                # ZIL: <STOLE-LIGHT? ...>
                stole_light_p()
            else:
                print("The thief, finding nothing of value, left disgusted.")
            _.zil_sdk.set_flag(lookup("thief"), "invisible", True)
            here_p = None
            return True
        else:
            print(
                'A "lean and hungry" gentleman just wandered through, carrying a\nlarge bag. Finding nothing of value, he left disgruntled.'
            )
            return True
else:
    if here_p:
        if random.randint(1, 100) <= 30:
            if _.zork_thing.invoke_verb("rob", context.player.location, lookup("thief"), 100):
                robbed_p = context.player.location
            elif _.zork_thing.invoke_verb("rob", context.player, lookup("thief")):
                robbed_p = context.player
            if robbed_p:
                print("The thief just left, still carrying his large bag. You may\nnot have noticed that he ", end="")
                if robbed_p == context.player:
                    print("robbed you blind first.", end="")
                else:
                    print("appropriated the valuables in the room.", end="")
                print()
                # ZIL: <STOLE-LIGHT? ...>
                stole_light_p()
            else:
                print("The thief, finding nothing of value, left disgusted.")
            _.zil_sdk.set_flag(lookup("thief"), "invisible", True)
            here_p = None
            # ZIL: <RECOVER-STILETTO ...>
            _.zork_thing.invoke_verb("recover-stiletto")
return False
