#!moo verb villain-strength --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context, lookup
# ZIL routine: VILLAIN-STRENGTH
# params: OO
# aux: VILLAIN, OD, TMP

oo = args[0] if len(args) > 0 else None
villain = _.zil_sdk.table_get(oo, _.zil_sdk.zstate_get("V-VILLAIN"))
od = None
tmp = None

od = _.zil_sdk.getp(villain, "strength")
if not od < 0:
    if villain == lookup("thief") and _.zil_sdk.zstate_get("THIEF-ENGROSSED"):
        if od > 2:
            od = 2
        _.zil_sdk.zstate_set("THIEF-ENGROSSED", None)
    if (
        context.parser.get_iobj()
        and _.zil_sdk.flag(context.parser.get_iobj(), "weapon")
        and _.zil_sdk.table_get(oo, _.zil_sdk.zstate_get("V-BEST")) == context.parser.get_iobj()
    ):
        tmp = od - _.zil_sdk.table_get(oo, _.zil_sdk.zstate_get("V-BEST-ADV"))
        if tmp < 1:
            tmp = 1
        od = tmp
return od
