#!moo verb villain-blow --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
from moo.sdk import context
# ZIL routine: VILLAIN-BLOW
# params: OO, OUT?
# aux: VILLAIN, REMARKS, DWEAPON, ATT, DEF, OA, OD, TBL, RES, NWEAPON

oo = args[0] if len(args) > 0 else None
out_p = args[1] if len(args) > 1 else None
villain = _.zil_sdk.table_get(oo, _.zil_sdk.zstate_get("V-VILLAIN"))
remarks = _.zil_sdk.table_get(oo, _.zil_sdk.zstate_get("V-MSGS"))
dweapon = None
att = None
def_v = None
oa = None
od = None
tbl = None
res = None
nweapon = None

_.zil_sdk.set_flag(context.player, "staggered", False)
if _.zil_sdk.flag(villain, "staggered"):
    print("The " + _.zil_sdk.desc(villain) + " slowly regains his feet.")
    _.zil_sdk.set_flag(villain, "staggered", False)
    return True
oa = (att := _.zork_thing.invoke_verb("villain-strength", oo))
if not (def_v := _.zork_thing.invoke_verb("fight-strength")) > 0:
    return True
od = _.zork_thing.invoke_verb("fight-strength")
dweapon = _.zork_thing.invoke_verb("find-weapon", context.player)
if def_v < 0:
    res = _.zil_sdk.zstate_get("KILLED")
else:
    if def_v == 1:
        if att > 2:
            att = 3
        tbl = _.zil_sdk.table_get(_.zil_sdk.zstate_get("DEF1-RES"), att - 1)
    elif def_v == 2:
        if att > 3:
            att = 4
        tbl = _.zil_sdk.table_get(_.zil_sdk.zstate_get("DEF2-RES"), att - 1)
    elif def_v > 2:
        att = att - def_v
        if att < -1:
            att = -2
        elif att > 1:
            att = 2
        tbl = _.zil_sdk.table_get(_.zil_sdk.zstate_get("DEF3-RES"), att + 2)
    res = _.zil_sdk.table_get(tbl, random.randint(1, 9) - 1)
    if out_p:
        if res == _.zil_sdk.zstate_get("STAGGER"):
            res = _.zil_sdk.zstate_get("HESITATE")
        else:
            res = _.zil_sdk.zstate_get("SITTING-DUCK")
    if res == _.zil_sdk.zstate_get("STAGGER") and dweapon and random.randint(1, 100) <= 25:
        res = _.zil_sdk.zstate_get("LOSE-WEAPON")
    # ZIL: <REMARK ...>
    _.zork_thing.invoke_verb(
        "remark",
        _.zork_thing.invoke_verb("random-element", _.zil_sdk.table_get(remarks, res - 1)),
        context.player,
        dweapon,
    )
if res == _.zil_sdk.zstate_get("MISSED") or res == _.zil_sdk.zstate_get("HESITATE"):
    pass
elif res == _.zil_sdk.zstate_get("UNCONSCIOUS"):
    pass
elif res == _.zil_sdk.zstate_get("KILLED") or res == _.zil_sdk.zstate_get("SITTING-DUCK"):
    def_v = 0
elif res == _.zil_sdk.zstate_get("LIGHT-WOUND"):
    def_v = def_v - 1
    if def_v < 0:
        def_v = 0
    if _.zil_sdk.zstate_get("LOAD-ALLOWED") > 50:
        _.zil_sdk.zstate_set("LOAD-ALLOWED", _.zil_sdk.zstate_get("LOAD-ALLOWED") - 10)
elif res == _.zil_sdk.zstate_get("SERIOUS-WOUND"):
    def_v = def_v - 2
    if def_v < 0:
        def_v = 0
    if _.zil_sdk.zstate_get("LOAD-ALLOWED") > 50:
        _.zil_sdk.zstate_set("LOAD-ALLOWED", _.zil_sdk.zstate_get("LOAD-ALLOWED") - 20)
elif res == _.zil_sdk.zstate_get("STAGGER"):
    _.zil_sdk.set_flag(context.player, "staggered", True)
else:
    _.zil_sdk.move(dweapon, context.player.location)
    if nweapon := _.zork_thing.invoke_verb("find-weapon", context.player):
        print("Fortunately, you still have a " + _.zil_sdk.desc(nweapon) + ".")
# ZIL: <WINNER-RESULT ...>
return _.zork_thing.invoke_verb("winner-result", def_v, res, od)
