#!moo verb reservoir-north-fcn --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: RESERVOIR-NORTH-FCN
# params: RARG

rarg = args[0] if len(args) > 0 else None

if rarg == "M-LOOK":
    if _.zil_sdk.zstate_get("LOW-TIDE") and _.zil_sdk.zstate_get("GATES-OPEN"):
        print(
            "You are in a large cavernous room, the south of which was formerly\na lake. However, with the water level lowered, there is merely\na wide stream running through there.",
            end="",
        )
    elif _.zil_sdk.zstate_get("GATES-OPEN"):
        print(
            "You are in a large cavernous area. To the south is a wide lake,\nwhose water level appears to be falling rapidly.",
            end="",
        )
    elif _.zil_sdk.zstate_get("LOW-TIDE"):
        print(
            "You are in a cavernous area, to the south of which is a very wide\nstream. The level of the stream is rising rapidly, and it appears\nthat before long it will be impossible to cross to the other side.",
            end="",
        )
    else:
        print("You are in a large cavernous room, north of a large lake.", end="")
    print()
    return print("There is a slimy stairway leaving the room to the north.")
