#!moo verb look --on $grating_clearing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL: CLEARING-FCN / M-LOOK

print("You are in a clearing, with a forest surrounding you on all sides. A\npath leads south.", end="")
if _.zil_sdk.flag(_.get_property("grate"), "open"):
    print()
    print("There is an open grating, descending into darkness.", end="")
elif _.zil_sdk.zstate_get("GRATE-REVEALED"):
    print()
    print("There is a grating securely fastened into the ground.", end="")
print()
