#!moo verb close insert lock open pick place put shut unlock --on $grate --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: GRATE-FUNCTION

if player_verb in ["open"] and context.parser.get_iobj() == _.get_property("keys"):
    _.zil_sdk.perform(_.zil_sdk.zstate_get("V?UNLOCK"), _.get_property("grate"), _.get_property("keys"))
    return True
elif player_verb in ["lock"]:
    if context.player.location == _.get_property("grating_room"):
        _.zil_sdk.zstate_set("GRUNLOCK", None)
        return print("The grate is locked.")
    elif context.player.location == _.get_property("grating_clearing"):
        return print("You can't lock it from this side.")
elif player_verb in ["unlock"] and context.parser.get_dobj() == _.get_property("grate"):
    if context.player.location == _.get_property("grating_room") and context.parser.get_iobj() == _.get_property(
        "keys"
    ):
        _.zil_sdk.zstate_set("GRUNLOCK", True)
        return print("The grate is unlocked.")
    elif context.player.location == _.get_property("grating_clearing") and context.parser.get_iobj() == _.get_property(
        "keys"
    ):
        return print("You can't reach the lock from here.")
    else:
        return print("Can you unlock a grating with a " + _.zil_sdk.desc(context.parser.get_iobj()) + "?")
elif player_verb in ["pick"]:
    return print("You can't pick the lock.")
elif player_verb in ["open", "close", "shut"]:
    if _.zil_sdk.zstate_get("GRUNLOCK"):
        # ZIL: <OPEN-CLOSE ...>
        _.zork_thing.invoke_verb(
            "open-close",
            _.get_property("grate"),
            cond(
                [["EQUAL?", "HERE", "CLEARING"], "The grating opens."],
                ["T", "The grating opens to reveal trees above you."],
            ),
            "The grating is closed.",
        )
        if _.zil_sdk.flag(_.get_property("grate"), "open"):
            if not context.player.location == _.get_property("clearing") and not _.zil_sdk.zstate_get("GRATE-REVEALED"):
                print("A pile of leaves falls onto your head and to the ground.")
                _.zil_sdk.zstate_set("GRATE-REVEALED", True)
                _.zil_sdk.move(_.get_property("leaves"), context.player.location)
            return _.zil_sdk.set_flag(_.get_property("grating_room"), "onbit", True)
        else:
            return _.zil_sdk.set_flag(_.get_property("grating_room"), "onbit", False)
    else:
        return print("The grating is locked.")
elif player_verb in ["put", "place", "insert"] and context.parser.get_iobj() == _.get_property("grate"):
    if context.parser.get_dobj().get_property("size") > 20:
        return print("It won't fit through the grating.")
    else:
        _.zil_sdk.move(context.parser.get_dobj(), _.get_property("grating_room"))
        return print(
            "The " + _.zil_sdk.desc(context.parser.get_dobj()) + " goes through the grating into the darkness below."
        )
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
