#!moo verb mung destroy break smash crack burn light --on "pile of bodies" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: BODY-FUNCTION (mung/burn branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

return _.jigs_up(
    'The voice of the guardian of the dungeon booms out from the darkness,\n"Your disrespect costs you your life!" and places your head on a sharp\npole.'
)
