#!moo verb mung destroy break smash crack --on "painting" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: PAINTING-FCN (mung branch)

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

parser.get_dobj().set_property("tvalue", 0)
parser.get_dobj().set_property("description", "There is a worthless piece of canvas here.")
print("Congratulations! Unlike the other vandals, who merely stole the\nartist's masterpieces, you have destroyed one.")
return
