#!moo verb i-candles --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: I-CANDLES
# aux: TICK, TBL

tick = None
tbl = value(_.zil_sdk.zstate_get("CANDLE-TABLE"))

_.zil_sdk.set_flag(_.get_property("candles"), "touchbit", True)
_.zil_sdk.queue("i-candles", (tick := _.zil_sdk.table_get(tbl, 0)))
# ZIL: <LIGHT-INT ...>
_.zork_thing.invoke_verb("light-int", _.get_property("candles"), tbl, tick)
if not tick == 0:
    return _.zil_sdk.zstate_set("CANDLE-TABLE", rest(tbl, 4))
