#!moo verb i-cure --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: I-CURE
# aux: S

s = context.player.get_property("strength")

if s > 0:
    s = 0
    return context.player.set_property("strength", s)
elif s < 0:
    s = s + 1
    return context.player.set_property("strength", s)
if s < 0:
    if _.zil_sdk.zstate_get("LOAD-ALLOWED") < _.zil_sdk.zstate_get("LOAD-MAX"):
        _.zil_sdk.zstate_set("LOAD-ALLOWED", _.zil_sdk.zstate_get("LOAD-ALLOWED") + 10)
    return _.zil_sdk.queue("i-cure", _.zil_sdk.zstate_get("CURE-WAIT"))
else:
    _.zil_sdk.zstate_set("LOAD-ALLOWED", _.zil_sdk.zstate_get("LOAD-MAX"))
    return _.zil_sdk.cancel("i-cure")
