#!moo verb i-cyclops --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: I-CYCLOPS

if _.zil_sdk.zstate_get("CYCLOPS-FLAG") or _.zil_sdk.zstate_get("DEAD"):
    return True
elif not context.player.location == _.get_property("cyclops_room"):
    return _.zil_sdk.cancel("i-cyclops")
else:
    if abs(_.zil_sdk.zstate_get("CYCLOWRATH")) > 5:
        _.zil_sdk.cancel("i-cyclops")
        return _.zil_sdk.jigs_up(
            "The cyclops, tired of all of your games and trickery, grabs you firmly.\nAs he licks his chops, he says \"Mmm. Just like Mom used to make 'em.\"\nIt's nice to be appreciated."
        )
    else:
        if _.zil_sdk.zstate_get("CYCLOWRATH") < 0:
            return _.zil_sdk.zstate_set("CYCLOWRATH", _.zil_sdk.zstate_get("CYCLOWRATH") - 1)
        else:
            return _.zil_sdk.zstate_set("CYCLOWRATH", _.zil_sdk.zstate_get("CYCLOWRATH") + 1)
        if not _.zil_sdk.zstate_get("CYCLOPS-FLAG"):
            return print(nth(_.zil_sdk.zstate_get("CYCLOMAD"), abs(_.zil_sdk.zstate_get("CYCLOWRATH")) - 1))
