#!moo verb i-fight --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
from moo.sdk import context, lookup
# ZIL routine: I-FIGHT
# aux: FIGHT?, LEN, CNT, OO, O, P

fight_p = None
len_v = _.zil_sdk.table_get(_.zil_sdk.zstate_get("VILLAINS"), 0)
cnt = None
oo = None
o = None
p = None

if _.zil_sdk.zstate_get("DEAD"):
    return False
cnt = 0
while True:
    cnt = cnt + 1
    if cnt == len_v:
        break
    oo = _.zil_sdk.table_get(_.zil_sdk.zstate_get("VILLAINS"), cnt)
    if (
        o := _.zil_sdk.table_get(oo, _.zil_sdk.zstate_get("V-VILLAIN"))
    ).location == context.player.location and not _.zil_sdk.flag(o, "invisible"):
        if o == lookup("thief") and _.zil_sdk.zstate_get("THIEF-ENGROSSED"):
            _.zil_sdk.zstate_set("THIEF-ENGROSSED", None)
        elif o.get_property("strength") < 0:
            p = _.zil_sdk.table_get(oo, _.zil_sdk.zstate_get("V-PROB"))
            if not p == 0 and random.randint(1, 100) <= p:
                # ZIL: <PUT ...>
                _.zil_sdk.table_put(oo, _.zil_sdk.zstate_get("V-PROB"), 0)
                # ZIL: <AWAKEN ...>
                _.zork_thing.invoke_verb("awaken", o)
            else:
                # ZIL: <PUT ...>
                _.zil_sdk.table_put(oo, _.zil_sdk.zstate_get("V-PROB"), p + 25)
        elif _.zil_sdk.flag(o, "hostile") or apply(o.get_property("action"), _.zil_sdk.zstate_get("F-FIRST?")):
            fight_p = True
    else:
        if _.zil_sdk.flag(o, "hostile"):
            # ZIL: <APPLY ...>
            apply(o.get_property("action"), _.zil_sdk.zstate_get("F-BUSY?"))
        if o == lookup("thief"):
            _.zil_sdk.zstate_set("THIEF-ENGROSSED", None)
        _.zil_sdk.set_flag(context.player, "staggered", False)
        _.zil_sdk.set_flag(o, "staggered", False)
        _.zil_sdk.set_flag(o, "hostile", False)
        # ZIL: <AWAKEN ...>
        _.zork_thing.invoke_verb("awaken", o)
if not fight_p:
    return False
# ZIL: <DO-FIGHT ...>
return _.zork_thing.invoke_verb("do-fight", len_v)
