#!moo verb i-match --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: I-MATCH

print("The match has gone out.")
_.zil_sdk.set_flag(_.get_property("match"), "flamebit", False)
_.zil_sdk.set_flag(_.get_property("match"), "onbit", False)
_.zil_sdk.zstate_set("LIT", _.zork_thing.invoke_verb("lit?", context.player.location))
return True
