#!moo verb i-rempty --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: I-REMPTY

_.zil_sdk.set_flag(_.get_property("reservoir"), "outdoor", True)
_.zil_sdk.set_flag(_.get_property("reservoir"), "nonlandbit", False)
_.zil_sdk.set_flag(_.get_property("deep_canyon"), "touchbit", False)
_.zil_sdk.set_flag(_.get_property("loud_room"), "touchbit", False)
_.zil_sdk.set_flag(_.get_property("trunk"), "invisible", False)
_.zil_sdk.zstate_set("LOW-TIDE", True)
if context.player.location == _.get_property("reservoir") and _.zil_sdk.flag(context.player.location, "vehicle"):
    print(
        "The water level has dropped to the point at which the boat can no\nlonger stay afloat. It sinks into the mud."
    )
elif context.player.location == _.get_property("deep_canyon"):
    print("The roar of rushing water is quieter now.")
elif context.player.location in (_.get_property("reservoir_north"), _.get_property("reservoir_south")):
    print("The water level is now quite low here and you could easily cross over\nto the other side.")
return True
