#!moo verb i-rfill --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: I-RFILL

_.zil_sdk.set_flag(_.get_property("reservoir"), "nonlandbit", True)
_.zil_sdk.set_flag(_.get_property("reservoir"), "outdoor", False)
_.zil_sdk.set_flag(_.get_property("deep_canyon"), "touchbit", False)
_.zil_sdk.set_flag(_.get_property("loud_room"), "touchbit", False)
if _.get_property("trunk").location == _.get_property("reservoir"):
    _.zil_sdk.set_flag(_.get_property("trunk"), "invisible", True)
_.zil_sdk.zstate_set("LOW-TIDE", None)
if context.player.location == _.get_property("reservoir"):
    if _.zil_sdk.flag(context.player.location, "vehicle"):
        print("The boat lifts gently out of the mud and is now floating on\nthe reservoir.")
    else:
        _.zil_sdk.jigs_up(
            "You are lifted up by the rising river! You try to swim, but the\ncurrents are too strong. You come closer, closer to the awesome\nstructure of Flood Control Dam #3. The dam beckons to you.\nThe roar of the water nearly deafens you, but you remain conscious\nas you tumble over the dam toward your certain doom among the rocks\nat its base."
        )
elif context.player.location == _.get_property("deep_canyon"):
    print("A sound, like that of flowing water, starts to come from below.")
elif context.player.location == _.get_property("loud_room"):
    print("All of a sudden, an alarmingly loud roaring sound fills the room.\nFilled with fear, you scramble away.")
    _.zil_sdk.goto(_.zil_sdk.pick(_.zil_sdk.zstate_get("LOUD-RUNS")))
elif context.player.location in (_.get_property("reservoir_north"), _.get_property("reservoir_south")):
    print("You notice that the water level has risen to the point that it\nis impossible to cross.")
return True
