#!moo verb i-river --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: I-RIVER
# aux: RM

rm = None

if not context.player.location in (
    _.get_property("river_1"),
    _.get_property("river_2"),
    _.get_property("river_3"),
) and not context.player.location in (_.get_property("river_4"), _.get_property("river_5")):
    return _.zil_sdk.cancel("i-river")
elif rm := _.zork_thing.invoke_verb("lkp", context.player.location, _.zil_sdk.zstate_get("RIVER-NEXT")):
    print("The flow of the river carries you downstream.")
    _.zil_sdk.goto(rm)
    return _.zil_sdk.queue(
        "i-river", _.zork_thing.invoke_verb("lkp", context.player.location, _.zil_sdk.zstate_get("RIVER-SPEEDS"))
    )
else:
    return _.zil_sdk.jigs_up(
        "Unfortunately, the magic boat doesn't provide protection from\nthe rocks and boulders one meets at the bottom of waterfalls.\nIncluding this one."
    )
