#!moo verb i-xbh --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: I-XBH

_.zil_sdk.remove(_.get_property("hot_bell"))
_.zil_sdk.move(_.get_property("bell"), _.get_property("entrance_to_hades"))
if context.player.location == _.get_property("entrance_to_hades"):
    return print("The bell appears to have cooled down.")
