#!moo verb i-xb --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: I-XB

if not _.zil_sdk.zstate_get("XC"):
    if context.player.location == _.get_property("entrance_to_hades"):
        print(
            "The tension of this ceremony is broken, and the wraiths, amused but\nshaken at your clumsy attempt, resume their hideous jeering."
        )
return _.zil_sdk.zstate_set("XB", None)
