#!moo verb i-xc --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: I-XC

_.zil_sdk.zstate_set("XC", None)
# ZIL: <I-XB ...>
return _.zork_thing.invoke_verb("i-xb")
