#!moo verb finish --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import lookup
# ZIL routine: FINISH
# aux: WRD

wrd = None

# ZIL: <V-SCORE ...>
_.zork_thing.invoke_verb("v-score")
while True:
    print()
    print(
        "Would you like to restart the game from the beginning, restore a saved\ngame position, or end this session of the game?\n\n(Type RESTART, RESTORE, or QUIT):\n\n>",
        end="",
    )
    # ZIL: <READ ...>
    read(_.zil_sdk.zstate_get("P-INBUF"), _.zil_sdk.zstate_get("P-LEXV"))
    wrd = _.zil_sdk.table_get(_.zil_sdk.zstate_get("P-LEXV"), 1)
    if wrd == _.zil_sdk.zstate_get("W?RESTART"):
        # ZIL: <RESTART ...>
        lookup("restart")
        return print("Failed.")
    elif wrd == _.zil_sdk.zstate_get("W?RESTORE"):
        if lookup("restore"):
            return print("Ok.")
        else:
            return print("Failed.")
    elif wrd in (_.zil_sdk.zstate_get("W?QUIT"), _.zil_sdk.zstate_get("W?Q")):
        # ZIL: <QUIT ...>
        return lookup("quit")
