#!moo verb score-upd --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: SCORE-UPD
# params: NUM

num = args[0] if len(args) > 0 else None

_.zil_sdk.zstate_set("BASE-SCORE", _.zil_sdk.zstate_get("BASE-SCORE") + num)
_.zil_sdk.zstate_set("SCORE", _.zil_sdk.zstate_get("SCORE") + num)
if _.zil_sdk.zstate_get("ZORK-NUMBER") == 1:
    if _.zil_sdk.zstate_get("SCORE") == 350 and not _.zil_sdk.zstate_get("WON-FLAG"):
        _.zil_sdk.zstate_set("WON-FLAG", True)
        _.zil_sdk.set_flag(_.get_property("map"), "invisible", False)
        _.zil_sdk.set_flag(_.get_property("west_of_house"), "touchbit", False)
        print('An almost inaudible voice whispers in your ear, "Look to your treasures\nfor the final secret."')
else:
    # ZIL: <NULL-F ...>
    _.zork_thing.invoke_verb("null-f")
return True
