#!moo verb leap --on $dome_room --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: DOME-ROOM-FCN
# params: RARG

rarg = args[0] if len(args) > 0 else None

if rarg == "M-LOOK":
    print(
        "You are at the periphery of a large dome, which forms the ceiling\nof another room below. Protecting you from a precipitous drop is a\nwooden railing which circles the dome."
    )
    if _.zil_sdk.zstate_get("DOME-FLAG"):
        return print("Hanging down from the railing is a rope which ends about ten feet\nfrom the floor below.")
elif rarg == "M-ENTER":
    if _.zil_sdk.zstate_get("DEAD"):
        print("As you enter the dome you feel a strong pull as if from a wind\ndrawing you over the railing and down.")
        _.zil_sdk.move(context.player, _.get_property("torch_room"))
        _.zil_sdk.zstate_set("HERE", _.get_property("torch_room"))
        return True
    elif player_verb in ["leap"]:
        return _.zil_sdk.jigs_up("I'm afraid that the leap you attempted has done you in.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
