#!moo verb give --on "pseudo" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: CRETIN-FCN (give branch)

player = context.player
parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (parser.get_iobj() if parser.has_iobj() else None) == lookup("me"):
    _.perform(player.zstate_get("V?TAKE"), parser.get_dobj(), None)
    return True
return passthrough()
