#!moo verb bag-of-coins-f --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: BAG-OF-COINS-F

# ZIL: <STUPID-CONTAINER ...>
return _.zork_thing.invoke_verb("stupid-container", _.get_property("bag_of_coins"), "coins")
