#!moo verb examine x describe what --on "brass lantern" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: LANTERN (examine branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("The lamp ", end="")
if this.flag("rmungbit"):
    print("has burned out.", end="")
elif this.flag("onbit"):
    print("is on.", end="")
else:
    print("is turned off.", end="")
print()
return
