#!moo verb throw toss --on "brass lantern" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: LANTERN (throw branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("The lamp has smashed into the floor, and the light has gone out.")
_.cancel("i-lantern")
_.remove(this)
return lookup("broken_lamp").moveto(player.here())
