#!moo verb east-house --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: EAST-HOUSE
# params: RARG

rarg = args[0] if len(args) > 0 else None

if rarg == "M-LOOK":
    print(
        "You are behind the white house. A path leads into the forest\nto the east. In one corner of the house there is a small window\nwhich is ",
        end="",
    )
    if _.zil_sdk.flag(_.get_property("kitchen_window"), "open"):
        print("open.", end="")
    else:
        print("slightly ajar.", end="")
    return print()
