#!moo verb board close describe examine go look-inside move open shut through walk what x --on $kitchen_window --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: KITCHEN-WINDOW-F

if player_verb in ["open", "close", "shut"]:
    _.zil_sdk.zstate_set("KITCHEN-WINDOW-FLAG", True)
    # ZIL: <OPEN-CLOSE ...>
    return _.zork_thing.invoke_verb(
        "open-close",
        _.get_property("kitchen_window"),
        "With great effort, you open the window far enough to allow entry.",
        "The window closes (more easily than it opened).",
    )
elif player_verb in ["examine", "x", "describe", "what"] and not _.zil_sdk.zstate_get("KITCHEN-WINDOW-FLAG"):
    return print("The window is slightly ajar, but not enough to allow entry.")
elif player_verb in ["go", "walk", "move", "board", "through"]:
    if context.player.location == _.get_property("kitchen"):
        _.zil_sdk.walk(_.zil_sdk.zstate_get("P?EAST"))
    else:
        _.zil_sdk.walk(_.zil_sdk.zstate_get("P?WEST"))
    return True
elif player_verb in ["look-inside"]:
    print("You can see ", end="")
    if context.player.location == _.get_property("kitchen"):
        return print("a clear area leading towards a forest.")
    else:
        return print("what appears to be a kitchen.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
