#!moo verb cross look-under through --on $rainbow --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: RAINBOW-FCN

if player_verb in ["cross", "through"]:
    if context.player.location == _.get_property("canyon_view"):
        print("From here?!?")
        return True
    if _.zil_sdk.zstate_get("RAINBOW-FLAG"):
        if context.player.location == _.get_property("aragain_falls"):
            return _.zil_sdk.goto(_.get_property("end_of_rainbow"))
        elif context.player.location == _.get_property("end_of_rainbow"):
            return _.zil_sdk.goto(_.get_property("aragain_falls"))
        else:
            return print("You'll have to say which way...")
    else:
        return print("Can you walk on water vapor?")
elif player_verb in ["look-under"]:
    return print("The Frigid River flows under the rainbow.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
