#!moo verb take get pick --on "cyclops" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: CYCLOPS-FCN (take branch)

count = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("The cyclops doesn't take kindly to being grabbed.")
return
