#!moo verb awaken --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: AWAKEN
# params: O
# aux: S

player = context.player
o = args[0] if len(args) > 0 else None
s = o.getp("strength")

if s < 0:
    o.set_property("strength", 0 - s)
    # ZIL: <APPLY ...>
    apply(o.getp("action"), player.zstate_get("F-CONSCIOUS"))
return True
