#!moo verb bad_egg --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import lookup
# ZIL routine: BAD-EGG

broken_canary = lookup("broken_canary")
egg = lookup("egg")

if lookup("canary").location == egg:
    print(" " + broken_canary.getp("description"), end="")
else:
    _.remove(broken_canary)
lookup("broken_egg").moveto(egg.location)
_.remove(egg)
return True
