#!moo verb bat_d --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: BAT-D

player = context.player

if lookup("garlic").location in (player, player.here()):
    print(
        "In the corner of the room on the ceiling is a large vampire bat who\nis obviously deranged and holding his nose."
    )
    return
else:
    print("A large vampire bat, hanging from the ceiling, swoops down at you!")
    return
