#!moo verb drop_junk --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

import random
from moo.sdk import context, lookup
# ZIL routine: DROP-JUNK
# params: RM
# aux: X, N, FLG

player = context.player
rm = args[0] if len(args) > 0 else None
x = 0
n = 0
flg = 0

x = lookup("thief").contents.first()
while True:
    if not x:
        return flg
    n = _.next_sibling(x)
    if x in (lookup("stiletto"), lookup("large_bag")):
        pass
    elif x.getp("tvalue") == 0 and random.randint(1, 100) <= 30:
        x.set_flag("invisible", False)
        x.moveto(rm)
        if not flg and rm == player.here():
            print("The robber, rummaging through his bag, dropped a few items he found\nvalueless.")
            flg = True
    x = n
