#!moo verb find_in --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import lookup
# ZIL routine: FIND-IN
# params: WHERE, WHAT
# aux: W

where = args[0] if len(args) > 0 else None
what = args[1] if len(args) > 1 else None
w = 0

w = where.contents.first()
if not w:
    return False
while True:
    if w.flag(what) and not w == lookup("adventurer"):
        return w
    elif not (w := _.next_sibling(w)):
        break
