#!moo verb fix_boat --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import lookup
# ZIL routine: FIX-BOAT

punctured_boat = lookup("punctured_boat")

print("Well done. The boat is repaired.")
lookup("inflatable_boat").moveto(punctured_boat.location)
return _.remove(punctured_boat)
