#!moo verb fix_maint_leak --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: FIX-MAINT-LEAK

player = context.player

player.zstate_set("WATER-LEVEL", -1)
# ZIL: <QUEUE ...>
_.zork_thing.queue(_.zork_thing.i_maint_room(), 0)
print("By some miracle of Zorkian technology, you have managed to stop the\nleak in the dam.")
return
