#!moo verb go --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: GO

player = context.player

_.queue("i-fight", -1)
# ZIL: <QUEUE ...>
_.zork_thing.queue(_.zork_thing.i_sword(), -1)
_.queue("i-thief", -1)
# ZIL: <QUEUE ...>
_.zork_thing.queue(_.zork_thing.i_candles(), 40)
# ZIL: <QUEUE ...>
_.zork_thing.queue(_.zork_thing.i_lantern(), 200)
lookup("inflated_boat").set_property("vtype", player.zstate_get("NONLANDBIT"))
# ZIL: <PUT ...>
_.table_put(player.zstate_get("DEF1-RES"), 1, rest(player.zstate_get("DEF1"), 2))
# ZIL: <PUT ...>
_.table_put(player.zstate_get("DEF1-RES"), 2, rest(player.zstate_get("DEF1"), 4))
# ZIL: <PUT ...>
_.table_put(player.zstate_get("DEF2-RES"), 2, rest(player.zstate_get("DEF2B"), 2))
# ZIL: <PUT ...>
_.table_put(player.zstate_get("DEF2-RES"), 3, rest(player.zstate_get("DEF2B"), 4))
# ZIL: <PUT ...>
_.table_put(player.zstate_get("DEF3-RES"), 1, rest(player.zstate_get("DEF3A"), 2))
# ZIL: <PUT ...>
_.table_put(player.zstate_get("DEF3-RES"), 3, rest(player.zstate_get("DEF3B"), 2))
player.zstate_set("HERE", lookup("west_of_house"))
# ZIL: <THIS-IS-IT ...>
_.zork_thing.this_is_it(lookup("mailbox"))
if not player.here().flag("touchbit"):
    # ZIL: <V-VERSION ...>
    _.zork_thing.version()
    print()
player.zstate_set("LIT", True)
player.zstate_set("WINNER", lookup("adventurer"))
player.zstate_set("PLAYER", player)
player.moveto(player.here())
# ZIL: <V-LOOK ...>
_.zork_thing.look()
# ZIL: <MAIN-LOOP ...>
_.zork_thing.main_loop()
# ZIL: <AGAIN ...>
return lookup("again")
