#!moo verb hack_hack --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: HACK-HACK
# params: STR

player = context.player
parser = context.parser
str_v = args[0] if len(args) > 0 else None
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if parser.get_dobj().location == lookup("global_objects") and the_player_verb in ["wave", "raise", "lower"]:
    print("The " + parser.get_dobj().desc() + " isn't here!")
    return
else:
    print(str_v + parser.get_dobj().desc() + _.pick(player.zstate_get("HO-HUM")))
    return
