#!moo verb hit_spot --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: HIT-SPOT

player = context.player
parser = context.parser

if parser.get_dobj() == lookup("water") and not lookup("global_water").global_in(player.here()):
    _.remove(parser.get_dobj())
print("Thank you very much. I was rather thirsty (from all this talking,\nprobably).")
return
