#!moo verb idrop --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: IDROP

player = context.player
parser = context.parser

if not parser.get_dobj().location == player and not parser.get_dobj().location.location == player:
    print("You're not carrying the " + parser.get_dobj().desc() + ".")
    return False
elif not parser.get_dobj().location == player and not parser.get_dobj().location.flag("open"):
    print("The " + parser.get_dobj().desc() + " is closed.")
    return False
else:
    parser.get_dobj().moveto(player.location)
    return True
