#!moo verb inbuf_stuff --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

# ZIL routine: INBUF-STUFF
# params: SRC, DEST
# aux: CNT

src = args[0] if len(args) > 0 else None
dest = args[1] if len(args) > 1 else None
cnt = 0

cnt = _.table_get(src, 0) - 1
while True:
    # ZIL: <PUTB ...>
    putb(dest, cnt, _.table_get(src, cnt))
    if dless_p(cnt, 0):
        break
