#!moo verb itake --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

import random
from moo.sdk import context
# ZIL routine: ITAKE
# params: VB
# aux: CNT, OBJ

player = context.player
parser = context.parser
vb = args[0] if len(args) > 0 else True
cnt = 0
obj = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

player.zstate_get("#DECL")
if player.zstate_get("DEAD"):
    if vb:
        print("Your hand passes through its object.")
    return False
elif not parser.get_dobj().flag("takeable"):
    if vb:
        print(_.pick(player.zstate_get("YUKS")))
    return False
elif _.zork_thing.null_f():
    return False
elif parser.get_dobj().location.flag("contbit") and not parser.get_dobj().location.flag("open"):
    return False
elif not parser.get_dobj().location.location == player and _.zork_thing.weight(parser.get_dobj()) + _.zork_thing.weight(
    player
) > player.zstate_get("LOAD-ALLOWED"):
    if vb:
        print("Your load is too heavy", end="")
        if player.zstate_get("LOAD-ALLOWED") < player.zstate_get("LOAD-MAX"):
            print(", especially in light of your condition.", end="")
        else:
            print(".", end="")
        print()
    # ZIL: <RFATAL ...>
    return 2
elif (
    the_player_verb in ["take", "get", "pick"]
    and (cnt := _.zork_thing.ccount(player)) > player.zstate_get("FUMBLE-NUMBER")
    and random.randint(1, 100) <= cnt * player.zstate_get("FUMBLE-PROB")
):
    print("You're holding too many things already!")
    return False
else:
    parser.get_dobj().moveto(player)
    parser.get_dobj().set_flag("obvious", False)
    parser.get_dobj().set_flag("touchbit", True)
    if player.zstate_get("ZORK-NUMBER") == 2:
        if player.zstate_get("SPELL?") == player.zstate_get("S-FILCH"):
            if ripoff(parser.get_dobj(), player.zstate_get("WIZARD-CASE")):
                print("When you touch the " + parser.get_dobj().desc() + " it immediately disappears!")
                return False
    else:
        # ZIL: <NULL-F ...>
        _.zork_thing.null_f()
    if player.zstate_get("ZORK-NUMBER") == 1 or player.zstate_get("ZORK-NUMBER") == 2:
        # ZIL: <SCORE-OBJ ...>
        _.zork_thing.score_obj(parser.get_dobj())
    else:
        # ZIL: <NULL-F ...>
        _.zork_thing.null_f()
    return True
