#!moo verb lkp --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

# ZIL routine: LKP
# params: ITM, TBL
# aux: CNT, LEN

itm = args[0] if len(args) > 0 else None
tbl = args[1] if len(args) > 1 else None
cnt = 0
len_v = _.table_get(tbl, 0)

while True:
    if (cnt := cnt + 1) > len_v:
        return False
    elif _.table_get(tbl, cnt) == itm:
        if cnt == len_v:
            return False
        else:
            return _.table_get(tbl, cnt + 1)
