#!moo verb min --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

# ZIL routine: MIN
# params: N1, N2

n1 = args[0] if len(args) > 0 else None
n2 = args[1] if len(args) > 1 else None

if n1 < n2:
    return n1
else:
    return n2
