#!moo verb move_all --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

# ZIL routine: MOVE-ALL
# params: FROM, TO
# aux: X, N

from_v = args[0] if len(args) > 0 else None
to = args[1] if len(args) > 1 else None
x = 0
n = 0

if x := from_v.contents.first():
    while True:
        if not x:
            break
        n = _.next_sibling(x)
        x.set_flag("invisible", False)
        x.moveto(to)
        x = n
