#!moo verb prep_find --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: PREP-FIND
# params: PREP
# aux: CNT, SIZE

player = context.player
prep = args[0] if len(args) > 0 else None
cnt = 0
size = 0

size = _.table_get(player.zstate_get("PREPOSITIONS"), 0) * 2
while True:
    if igrtr_p(cnt, size):
        return False
    elif _.table_get(player.zstate_get("PREPOSITIONS"), cnt) == prep:
        return _.table_get(player.zstate_get("PREPOSITIONS"), cnt - 1)
