#!moo verb queue --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: QUEUE
# params: RTN, TICK
# aux: CINT

player = context.player
rtn = args[0] if len(args) > 0 else None
tick = args[1] if len(args) > 1 else None
cint = 0

player.zstate_get("#DECL")
# ZIL: <PUT ...>
_.table_put((cint := _.zork_thing.int(rtn)), player.zstate_get("C-TICK"), tick)
return cint
