#!moo verb randomize_objects --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

import random
from moo.sdk import context, lookup
# ZIL routine: RANDOMIZE-OBJECTS
# aux: R, F, N, L

player = context.player
coffin = lookup("coffin")
lamp = lookup("lamp")
r = 0
f = 0
n = 0
l = 0

if lamp.location == player:
    return lamp.moveto(lookup("living_room"))
if coffin.location == player:
    return coffin.moveto(lookup("egypt_room"))
lookup("sword").set_property("tvalue", 0)
n = player.contents.first()
l = _.table_get(player.zstate_get("ABOVE-GROUND"), 0)
while True:
    f = n
    if not f:
        break
    n = _.next_sibling(f)
    if f.getp("tvalue") > 0:
        while True:
            if not r:
                r = player.zstate_get("ROOMS").contents.first()
            if r.flag("outdoor") and not r.flag("onbit") and random.randint(1, 100) <= 50:
                f.moveto(r)
                break
            else:
                r = _.next_sibling(r)
    else:
        return f.moveto(_.table_get(player.zstate_get("ABOVE-GROUND"), random.randint(1, l)))
