#!moo verb random_element --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

import random
# ZIL routine: RANDOM-ELEMENT
# params: FROB

frob = args[0] if len(args) > 0 else None

# ZIL: <GET ...>
return _.table_get(frob, random.randint(1, _.table_get(frob, 0)))
