#!moo verb recover_stiletto --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import lookup
# ZIL routine: RECOVER-STILETTO

stiletto = lookup("stiletto")
thief = lookup("thief")

if stiletto.location == thief.location:
    stiletto.set_flag("obvious", True)
    return stiletto.moveto(thief)
