#!moo verb stuff --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: STUFF
# params: SRC, DEST, MAX
# aux: PTR, CTR, BPTR

player = context.player
src = args[0] if len(args) > 0 else None
dest = args[1] if len(args) > 1 else None
max_v = args[2] if len(args) > 2 else 29
ptr = player.zstate_get("P-LEXSTART")
ctr = 1
bptr = 0

# ZIL: <PUTB ...>
putb(dest, 0, _.table_get(src, 0))
# ZIL: <PUTB ...>
putb(dest, 1, _.table_get(src, 1))
while True:
    # ZIL: <PUT ...>
    _.table_put(dest, ptr, _.table_get(src, ptr))
    bptr = ptr * 2 + 2
    # ZIL: <PUTB ...>
    putb(dest, bptr, _.table_get(src, bptr))
    bptr = ptr * 2 + 3
    # ZIL: <PUTB ...>
    putb(dest, bptr, _.table_get(src, bptr))
    ptr = ptr + player.zstate_get("P-LEXELEN")
    if igrtr_p(ctr, max_v):
        break
