#!moo verb take_check --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: TAKE-CHECK

player = context.player
parser = context.parser

if _.zork_thing.itake_check(
    parser.get_dobj(), _.table_get(player.zstate_get("P-SYNTAX"), player.zstate_get("P-SLOC1"))
):
    # ZIL: <ITAKE-CHECK ...>
    return _.zork_thing.itake_check(
        (parser.get_iobj() if parser.has_iobj() else None),
        _.table_get(player.zstate_get("P-SYNTAX"), player.zstate_get("P-SLOC2")),
    )
