#!moo verb touch_all --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

# ZIL routine: TOUCH-ALL
# params: OBJ
# aux: F

obj = args[0] if len(args) > 0 else None
f = 0

f = obj.contents.first()
while True:
    if not f:
        break
    else:
        f.set_flag("touchbit", True)
        if f.contents.first():
            # ZIL: <TOUCH-ALL ...>
            _.zork_thing.touch_all(f)
    f = _.next_sibling(f)
