#!moo verb untie_from --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: UNTIE-FROM

player = context.player
parser = context.parser

if (
    parser.get_dobj() == lookup("rope")
    and player.zstate_get("DOME-FLAG")
    and (parser.get_iobj() if parser.has_iobj() else None) == lookup("railing")
):
    return _.perform(player.zstate_get("V?UNTIE"), parser.get_dobj(), None)
else:
    print("It's not attached to that!")
    return
