#!moo verb weight --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: WEIGHT
# params: OBJ
# aux: CONT, WT

player = context.player
obj = args[0] if len(args) > 0 else None
cont = 0
wt = 0

if cont := obj.contents.first():
    while True:
        if obj == player and cont.flag("wearbit"):
            wt = wt + 1
        else:
            wt = wt + _.zork_thing.weight(cont)
        if not (cont := _.next_sibling(cont)):
            break
return wt + obj.getp("size")
