#!moo verb axe-f --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import lookup
# ZIL routine: AXE-F

if _.zil_sdk.zstate_get("TROLL-FLAG"):
    pass
else:
    # ZIL: <WEAPON-FUNCTION ...>
    return _.zork_thing.invoke_verb("weapon-function", _.get_property("axe"), lookup("troll"))
