#!moo verb troll_room_f --on "Zork Thing" --dspec this
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: TROLL-ROOM-F
# params: RARG

player = context.player
troll = lookup("troll")
rarg = args[0] if len(args) > 0 else None

if rarg == "M-ENTER" and troll.location == player.here():
    # ZIL: <THIS-IS-IT ...>
    return _.zork_thing.this_is_it(troll)
