#!moo verb break crack describe destroy examine get give hear hello hi listen move mung pick smash take tell throw toss what x --on $troll --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
import random
from moo.sdk import context, lookup
# ZIL routine: TROLL-FCN
# params: MODE

mode = args[0] if len(args) > 0 else None

if player_verb in ["tell"]:
    _.zil_sdk.zstate_set("P-CONT", None)
    return print("The troll isn't much of a conversationalist.")
elif mode == _.zil_sdk.zstate_get("F-BUSY?"):
    if _.get_property("axe").location == lookup("troll"):
        pass
    elif _.get_property("axe").location == context.player.location and random.randint(1, 100) <= 75:
        _.zil_sdk.set_flag(_.get_property("axe"), "obvious", True)
        _.zil_sdk.set_flag(_.get_property("axe"), "weapon", False)
        _.zil_sdk.move(_.get_property("axe"), lookup("troll"))
        lookup("troll").set_property(
            "description", "A nasty-looking troll, brandishing a bloody axe, blocks all passages out\nof the room."
        )
        if lookup("troll").location == context.player.location:
            print(
                "The troll, angered and humiliated, recovers his weapon. He appears to have\nan axe to grind with you."
            )
        return True
    elif lookup("troll").location == context.player.location:
        lookup("troll").set_property("description", "A pathetically babbling troll is here.")
        print("The troll, disarmed, cowers in terror, pleading for his life in\nthe guttural tongue of the trolls.")
        return True
elif mode == _.zil_sdk.zstate_get("F-DEAD"):
    if _.get_property("axe").location == lookup("troll"):
        _.zil_sdk.move(_.get_property("axe"), context.player.location)
        _.zil_sdk.set_flag(_.get_property("axe"), "obvious", False)
        _.zil_sdk.set_flag(_.get_property("axe"), "weapon", True)
    return _.zil_sdk.zstate_set("TROLL-FLAG", True)
elif mode == _.zil_sdk.zstate_get("F-UNCONSCIOUS"):
    _.zil_sdk.set_flag(lookup("troll"), "hostile", False)
    if _.get_property("axe").location == lookup("troll"):
        _.zil_sdk.move(_.get_property("axe"), context.player.location)
        _.zil_sdk.set_flag(_.get_property("axe"), "obvious", False)
        _.zil_sdk.set_flag(_.get_property("axe"), "weapon", True)
    lookup("troll").set_property(
        "description", "An unconscious troll is sprawled on the floor. All passages\nout of the room are open."
    )
    return _.zil_sdk.zstate_set("TROLL-FLAG", True)
elif mode == _.zil_sdk.zstate_get("F-CONSCIOUS"):
    if lookup("troll").location == context.player.location:
        _.zil_sdk.set_flag(lookup("troll"), "hostile", True)
        print("The troll stirs, quickly resuming a fighting stance.")
    if _.get_property("axe").location == lookup("troll"):
        lookup("troll").set_property(
            "description", "A nasty-looking troll, brandishing a bloody axe, blocks\nall passages out of the room."
        )
    elif _.get_property("axe").location == _.get_property("troll_room"):
        _.zil_sdk.set_flag(_.get_property("axe"), "obvious", True)
        _.zil_sdk.set_flag(_.get_property("axe"), "weapon", False)
        _.zil_sdk.move(_.get_property("axe"), lookup("troll"))
        lookup("troll").set_property(
            "description", "A nasty-looking troll, brandishing a bloody axe, blocks\nall passages out of the room."
        )
    else:
        lookup("troll").set_property("description", "A troll is here.")
    return _.zil_sdk.zstate_set("TROLL-FLAG", None)
elif mode == _.zil_sdk.zstate_get("F-FIRST?"):
    if random.randint(1, 100) <= 33:
        _.zil_sdk.set_flag(lookup("troll"), "hostile", True)
        _.zil_sdk.zstate_set("P-CONT", None)
        return True
elif not mode:
    if player_verb in ["examine", "x", "describe", "what"]:
        return print(_.zil_sdk.getp(lookup("troll"), "description"))
    elif (
        player_verb in ["throw", "toss", "give"]
        and context.parser.get_dobj()
        and context.parser.get_iobj() == lookup("troll")
        or player_verb in ["take", "get", "pick", "move", "mung", "destroy", "break", "smash", "crack"]
    ):
        # ZIL: <AWAKEN ...>
        _.zork_thing.invoke_verb("awaken", lookup("troll"))
        if player_verb in ["throw", "toss", "give"]:
            if context.parser.get_dobj() == _.get_property("axe") and _.get_property("axe").location == context.player:
                print("The troll scratches his head in confusion, then takes the axe.")
                _.zil_sdk.set_flag(lookup("troll"), "hostile", True)
                _.zil_sdk.move(_.get_property("axe"), lookup("troll"))
                return True
            elif context.parser.get_dobj() in (lookup("troll"), _.get_property("axe")):
                print(
                    "You would have to get the "
                    + _.zil_sdk.desc(context.parser.get_dobj())
                    + " first, and that seems unlikely."
                )
                return True
            if player_verb in ["throw", "toss"]:
                return print(
                    "The troll, who is remarkably coordinated, catches the "
                    + _.zil_sdk.desc(context.parser.get_dobj()),
                    end="",
                )
            else:
                return print("The troll, who is not overly proud, graciously accepts the gift", end="")
            if random.randint(1, 100) <= 20 and context.parser.get_dobj() in (
                _.get_property("knife"),
                _.get_property("sword"),
                _.get_property("axe"),
            ):
                _.zil_sdk.remove(context.parser.get_dobj())
                print(
                    " and eats it hungrily. Poor troll, he dies from an internal hemorrhage\nand his carcass disappears in a sinister black fog."
                )
                _.zil_sdk.remove(lookup("troll"))
                # ZIL: <APPLY ...>
                apply(_.zil_sdk.getp(lookup("troll"), "action"), _.zil_sdk.zstate_get("F-DEAD"))
                return _.zil_sdk.zstate_set("TROLL-FLAG", True)
            elif context.parser.get_dobj() in (_.get_property("knife"), _.get_property("sword"), _.get_property("axe")):
                _.zil_sdk.move(context.parser.get_dobj(), context.player.location)
                print(
                    " and, being for the moment sated, throws it back. Fortunately, the\ntroll has poor control, and the "
                    + _.zil_sdk.desc(context.parser.get_dobj())
                    + " falls to the floor. He does\nnot look pleased."
                )
                return _.zil_sdk.set_flag(lookup("troll"), "hostile", True)
            else:
                print(" and not having the most discriminating tastes, gleefully eats it.")
                return _.zil_sdk.remove(context.parser.get_dobj())
        elif player_verb in ["take", "get", "pick", "move"]:
            return print(
                'The troll spits in your face, grunting "Better luck next time" in a\nrather barbarous accent.'
            )
        elif player_verb in ["mung", "destroy", "break", "smash", "crack"]:
            return print("The troll laughs at your puny gesture.")
    elif player_verb in ["listen", "hear"]:
        return print("Every so often the troll says something, probably uncomplimentary, in\nhis guttural tongue.")
    elif _.zil_sdk.zstate_get("TROLL-FLAG") and player_verb in ["hello", "hi"]:
        return print("Unfortunately, the troll can't hear you.")
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
