apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "termiverse.fullname" . }}-shell
  labels:
    {{- include "termiverse.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "termiverse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "termiverse.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "termiverse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["manage.py", "termiverse_shell"]
          env:
          - name: DJANGO_SETTINGS_MODULE
            value: {{ .Values.termiverse.django.settings }}
          - name: AWS_DEFAULT_REGION
            value: {{ .Values.termiverse.aws.region }}
          - name: AWS_STS_REGIONAL_ENDPOINTS
            value: regional
          ports:
            - name: ssh
              containerPort: {{ .Values.sshService.port }}
              protocol: TCP
          # livenessProbe:
          #   tcpSocket:
          #     port: {{ .Values.sshService.port }}
          # readinessProbe:
          #   tcpSocket:
          #     port: {{ .Values.sshService.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
