#!moo verb chasm-pseudo --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: CHASM-PSEUDO

if (
    player_verb in ["leap"]
    or player_verb in ["put", "place", "insert"]
    and context.parser.get_dobj() == _.get_property("me")
):
    return print("You look before leaping, and realize that you would never survive.")
elif player_verb in ["cross"]:
    return print("It's too far to jump, and there's no bridge.")
elif player_verb in ["put", "place", "insert", "throw-off"] and context.parser.get_iobj() == _.get_property(
    "pseudo_object"
):
    print("The " + _.zil_sdk.desc(context.parser.get_dobj()) + " drops out of sight into the chasm.")
    return _.zil_sdk.remove(context.parser.get_dobj())
