#!moo verb gas-pseudo --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: GAS-PSEUDO

if player_verb in ["breathe"]:
    return print("There is too much gas to blow away.")
elif player_verb in ["smell", "sniff"]:
    return print("It smells like coal gas in here.")
