#!moo verb gate-pseudo --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: GATE-PSEUDO

if player_verb in ["through"]:
    _.zil_sdk.walk(_.zil_sdk.zstate_get("P?IN"))
    return True
else:
    return print("The gate is protected by an invisible force. It makes your\nteeth ache to touch it.")
