#!moo verb stream-pseudo --on $zork_thing
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL routine: STREAM-PSEUDO

if player_verb in ["swim", "through"]:
    return print("You can't swim in the stream.")
elif player_verb in ["cross"]:
    return print("The other side is a sheer rock cliff.")
