#!moo verb look --on $mirror_room_2
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
# ZIL: MIRROR-ROOM / M-LOOK

print(
    "You are in a large square room with tall ceilings. On the south wall\nis an enormous mirror which fills the entire wall. There are exits\non the other three sides of the room."
)
if _.zil_sdk.zstate_get("MIRROR-MUNG"):
    print("Unfortunately, the mirror has been destroyed by your recklessness.")
