#!moo verb open mung destroy break smash crack --on "jewel-encrusted egg" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: EGG-OBJECT (open/mung branch)

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if parser.get_dobj() == this:
    if parser.get_dobj().flag("open"):
        print("The egg is already open.")
        return
    elif not (parser.get_iobj() if parser.has_iobj() else None):
        print("You have neither the tools nor the expertise.")
        return
    elif (parser.get_iobj() if parser.has_iobj() else None) == lookup("hands"):
        print("I doubt you could do that without damaging it.")
        return
    elif (
        (parser.get_iobj() if parser.has_iobj() else None).flag("weapon")
        or (parser.get_iobj() if parser.has_iobj() else None).flag("toolbit")
        or the_player_verb in ["mung", "destroy", "break", "smash", "crack"]
    ):
        print(
            "The egg is now open, but the clumsiness of your attempt has seriously\ncompromised its esthetic appeal.",
            end="",
        )
        # ZIL: <BAD-EGG ...>
        _.zork_thing.bad_egg()
        print()
        return
    elif parser.get_dobj().flag("hostile"):
        print(
            "Not to say that using the "
            + (parser.get_iobj() if parser.has_iobj() else None).desc()
            + " isn't original too..."
        )
        return
    else:
        print(
            "The concept of using a "
            + (parser.get_iobj() if parser.has_iobj() else None).desc()
            + " is certainly original."
        )
        return parser.get_dobj().set_flag("hostile", True)
return passthrough()
