# Generated by extras/zork_import
import pytest
from moo.sdk import lookup


@pytest.mark.parametrize(
    "routine_name",
    [
        "TREASURE-INSIDE",
        "GRATING-EXIT",
        "CANYON-VIEW-F",
        "GO",
        "WEST-HOUSE",
        "EAST-HOUSE",
        "OPEN-CLOSE",
        "BOARD-F",
        "TEETH-F",
        "GRANITE-WALL-F",
        "SONGBIRD-F",
        "WHITE-HOUSE-F",
        "GO-NEXT",
        "FOREST-F",
        "MOUNTAIN-RANGE-F",
        "WATER-F",
        "KITCHEN-WINDOW-F",
        "GHOSTS-F",
        "BASKET-F",
        "BAT-F",
    ],
)
def test_stub_verb_exists(zork_world, routine_name):
    """Each ACTION routine stub should exist as a verb on the Zork Room class."""
    zork_room = lookup("Zork Room")
    assert zork_room is not None
    # Verb may be on the room class or a specific object — just check it was loaded
    # (full dispatch testing requires individual test cases per verb)
