#!moo verb climb-down --on "rope" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context
# ZIL routine: ROPE-FUNCTION (climb-down branch)

player = context.player
parser = context.parser
rloc = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if parser.get_dobj() in (this, player.zstate_get("ROOMS")) and player.zstate_get("DOME-FLAG"):
    return _.walk(player.zstate_get("P?DOWN"))
return passthrough()
