# pylint: disable=undefined-variable
containers, containers_created = bootstrap.get_or_create_object("Generic Container", unique_name=True)
if containers_created:
    containers.add_verb("accept", code="return True")
containers.owner = wizard
containers.save()
sys.set_property("container", containers)
containers.set_property("open_key", None)
containers.set_property("open", False, inherit_owner=True)
containers.set_property("opaque", False, inherit_owner=True)

root, root_created = bootstrap.get_or_create_object("Root Class", unique_name=True)
if root_created:
    root.add_verb("accept", code="return True")
sys.set_property("root_class", root)
root.set_property("description", "")
root.set_property("key", None)

rooms, _ = bootstrap.get_or_create_object("Generic Room", unique_name=True, parents=[root])
sys.set_property("room", rooms)
rooms.set_property("blessed_object", None)
rooms.set_property("blessed_task_id", None)
rooms.set_property("description", "There's not much to see here.")
rooms.set_property("exits", [])
rooms.set_property("victim_ejection_message", "You have been ejected from %s by %s.")
rooms.set_property("ejection_message", "You have ejected %s.")
rooms.set_property("room_ejection_message", "%s has been ejected by %s.")
rooms.set_property("residents", [])
rooms.set_property("free_entry", True)
rooms.set_property("entrances", [])
rooms.set_property("dark", False)
rooms.set_property("content_list_type", 3)

mail_room, _ = bootstrap.get_or_create_object("Mail Distribution Center", unique_name=True, parents=[rooms])

player, _ = bootstrap.get_or_create_object("Generic Player", unique_name=True, parents=[root])
sys.set_property("player", player)
player.set_property("last_connect_time", time())
player.set_property("last_connected_time", None)
player.set_property("ownership_quota", 1000)
player.set_property("ps", "they", inherit_owner=True)
player.set_property("po", "them", inherit_owner=True)
player.set_property("pp", "their", inherit_owner=True)
player.set_property("pr", "themselves", inherit_owner=True)
player.set_property("pq", "theirs", inherit_owner=True)
player.set_property("psc", "They", inherit_owner=True)
player.set_property("poc", "Them", inherit_owner=True)
player.set_property("ppc", "Their", inherit_owner=True)
player.set_property("prc", "Themselves", inherit_owner=True)
player.set_property("pqc", "Theirs", inherit_owner=True)
player.set_property("home", None)
player.set_property("gaglist", [])
player.set_property("paranoid", False)
player.set_property("responsible", [])
player.set_property("lines", 10)
player.set_property("wrap_column", "auto")
player.set_property("object_gaglist", [])
player.set_property("page_absent_msg", "%n is not currently logged in.")
player.set_property("page_origin_msg", "You sense that %n is looking for you in %x(location).")
player.set_property("page_echo_msg", "Your message has been sent.")
player.set_property("whereis_location_msg", "%N is in %x(location).")
player.set_property("who_location_msg", "%x(location)")
player.set_property("victim_ejection_msg", "You have been ejected from %s by %s.")

programmers, _ = bootstrap.get_or_create_object("Generic Programmer", unique_name=True, parents=[player])
sys.set_property("programmer", programmers)
wizards, _ = bootstrap.get_or_create_object("Generic Wizard", unique_name=True, parents=[programmers])
sys.set_property("wizard", wizards)
if not wizard.parents.filter(pk=wizards.pk).exists():
    wizard.parents.add(wizards)

thing, _ = bootstrap.get_or_create_object("Generic Thing", unique_name=True, parents=[root])
sys.set_property("thing", thing)
thing.set_property("otake_succeeded_msg", "%N picks up %t.")
thing.set_property("otake_failed_msg", "")
thing.set_property("take_succeeded_msg", "You take %t.")
thing.set_property("take_failed_msg", "You can't pick that up.")
thing.set_property("odrop_succeeded_msg", "%N drops %t.")
thing.set_property("odrop_failed_msg", "%N tries to drop %t but fails!")
thing.set_property("drop_succeeded_msg", "You drop %t.")
thing.set_property("drop_failed_msg", "You can't seem to drop %t here.")
thing.set_property("alight", False, inherit_owner=True)
if not containers.parents.filter(pk=thing.pk).exists():
    containers.parents.add(thing)

furniture, _ = bootstrap.get_or_create_object("Generic Furniture", unique_name=True, parents=[thing])
sys.set_property("furniture", furniture)
furniture.set_property("take_failed_msg", "It's not possible to move something like this.")
furniture.set_property("otake_failed_msg", "%N tries to pick up %t, but it won't budge.")
furniture.set_property("sit_succeeded_msg", "You sit on %t.")
furniture.set_property("osit_succeeded_msg", "%N sits on %t.")
furniture.set_property("sit_failed_msg", "You are already sitting on %t.")
furniture.set_property("stand_succeeded_msg", "You stand up from %t.")
furniture.set_property("ostand_succeeded_msg", "%N stands up from %t.")
furniture.set_property("stand_failed_msg", "You aren't sitting on %t.")

exits, _ = bootstrap.get_or_create_object("Generic Exit", unique_name=True, parents=[root])
sys.set_property("exit", exits)
exits.set_property("source", None)
exits.set_property("dest", None)
exits.set_property("nogo_msg", "You can't go that way.")
exits.set_property("onogo_msg", "{actor} can't go that way.")
exits.set_property("arrive_msg", "You arrive at {subject}.")
exits.set_property("oarrive_msg", "{actor} arrives at {subject}.")
exits.set_property("oleave_msg", "{actor} leaves {subject}.")
exits.set_property("leave_msg", "You leave {subject}.")

notes, _ = bootstrap.get_or_create_object("Generic Note", unique_name=True, parents=[thing])
sys.set_property("note", notes)
notes.set_property("text", "")
notes.set_property("read_key", None)

letters, _ = bootstrap.get_or_create_object("Generic Letter", unique_name=True, parents=[notes])
sys.set_property("letter", letters)

bulletin_board, _ = bootstrap.get_or_create_object("Generic Bulletin Board", unique_name=True, parents=[thing])
sys.set_property("bulletin_board", bulletin_board)
bulletin_board.set_property("entries", [])

book, _ = bootstrap.get_or_create_object("Generic Book", unique_name=True, parents=[thing])
sys.set_property("book", book)
book.set_property("notes", {})
