#!moo verb raise --on "basket (RAISED-BASKET)" --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison,unnecessary-pass,expression-not-assigned

from moo.sdk import context, lookup
# ZIL routine: BASKET-F (raise branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.zstate_get("CAGE-TOP"):
    print(_.pick(player.zstate_get("DUMMY")))
    return
else:
    this.moveto(lookup("shaft_room"))
    lookup("lowered_basket").moveto(lookup("lower_shaft"))
    player.zstate_set("CAGE-TOP", True)
    # ZIL: <THIS-IS-IT ...>
    _.zork_thing.this_is_it(this)
    print("The basket is raised to the top of the shaft.")
    return
return passthrough()
