#!moo verb dig --on $sand --dspec either
# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,pointless-statement,unnecessary-negation,disallowed-name,using-constant-test,redefined-outer-name,no-else-return,unused-variable,redefined-builtin,singleton-comparison
from moo.sdk import context
# ZIL routine: SAND-FUNCTION

if player_verb in ["dig"] and context.parser.get_iobj() == _.get_property("shovel"):
    _.zil_sdk.zstate_set("BEACH-DIG", 1 + _.zil_sdk.zstate_get("BEACH-DIG"))
    if _.zil_sdk.zstate_get("BEACH-DIG") > 3:
        _.zil_sdk.zstate_set("BEACH-DIG", -1)
        if _.get_property("scarab").location == context.player.location:
            _.zil_sdk.set_flag(_.get_property("scarab"), "invisible", True)
        return _.zil_sdk.jigs_up("The hole collapses, smothering you.")
    elif _.zil_sdk.zstate_get("BEACH-DIG") == 3:
        if _.zil_sdk.flag(_.get_property("scarab"), "invisible"):
            print("You can see a scarab here in the sand.")
            # ZIL: <THIS-IS-IT ...>
            _.zork_thing.invoke_verb("this-is-it", _.get_property("scarab"))
            return _.zil_sdk.set_flag(_.get_property("scarab"), "invisible", False)
    else:
        return print(_.zil_sdk.table_get(_.zil_sdk.zstate_get("BDIGS"), _.zil_sdk.zstate_get("BEACH-DIG")))
# Auto-generated fallthrough to standard V-<player_verb>
_.zil_sdk.run_v_routine(player_verb)
